All done
frontend-park-mail-ru/homework_2023_1 pull request #1
Opened 2023-02-07 15:43 UTC by mihaillatyshov

ДЗ №0 Вариант 6 
Латышов Михаил

2023-02-08 19:05 UTC, AntonElagin requested changes
Привет, я буду проверять твое ДЗ0. 

Решение получилось неплохое, вижу, что с большей частью языка и code style удалось разобрать, но решение надо еще чуточку доработать)

- [ ] нужно добавить документацию
- [ ] исправить недочеты, которые я указал в коде
- [ ] найти кейс, когда твоя функция будет работать неверно(Он есть, и в ревью я этот нюанс немного затронул)

2023-02-09 10:37 UTC, AntonElagin commented
А еще предлагаю привести названия пр-а вот в такой вид:

Фамилия Имя - Вариант

2023-02-11 12:35 UTC, AntonElagin requested changes

2023-02-11 12:35 UTC, AntonElagin commented on source/tree.js
> +        }
в js есть функция, которая позволяет создать строку из одинаковых символов нужной длинны https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat

2023-02-11 12:35 UTC, AntonElagin commented on source/tree.js
> +        return spaces + chars + spaces + "\n";
```\n``` тоже можно убрать в константы

2023-02-13 12:15 UTC, AntonElagin requested changes

2023-02-13 12:15 UTC, AntonElagin commented on source/tree.js
> + * @returns {string} The string with ASCII tree
Возвращаемое значение в доке не соответствует действительности

2023-02-13 13:45 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Хорошая работа, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 13:45 UTC, DPeshkoff commented on source/tree.js
> +	if (!isFinite(height) || height < MIN_HEIGHT) {
А чем отличается [isFinite()](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/isFinite) от [Number.isFinite()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isFinite)?

2023-02-13 13:45 UTC, DPeshkoff commented on source/tree.js
> +'use strict';
Можешь, пожалуйста, объяснить в реплае, зачем нужен use strict и почему он используется в работе?

2023-02-13 14:59 UTC, mihaillatyshov commented on source/tree.js
> +'use strict';
use strict нужен для строго поведения языка. JS стал строже (например this вне объекта) и поменял свое поведение в одном из обновлений. use strict нужен для обратной совместимости старого кода

2023-02-13 15:02 UTC, mihaillatyshov commented on source/tree.js
> +	if (!isFinite(height) || height < MIN_HEIGHT) {
isFinite() сначала приводит тип к number, а уже потом проверяет по нужным критериям 
Number.isFinite() не делает этого преобразования, он более строгий

2023-02-13 15:39 UTC, mihaillatyshov commented on source/tree.js
> +	if (!isFinite(height) || height < MIN_HEIGHT) {
Исправил

2023-02-13 15:50 UTC, closed without merging