Котков Олег. Вариант 2.
frontend-park-mail-ru/homework_2023_1 pull request #10
Opened 2023-02-08 18:58 UTC by Ogrebatel

2023-02-09 11:21 UTC, AntonElagin requested changes
Привет, приветствую тебя на курсе фронтенда. Я буду проверять твое дз0.

У тебя получилось неплохое решение, но его все равно можно чуточку улуяшить

- [x]  Давай добавим JsDoc. Он поможет задокументировать твой код, чтобы любой мог понять, зачем твоя функция нужна и как ей пользоваться. https://jsdoc.app/
- [ ] Давай приведем код в порядок. Нужно стараться оформлять код в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для этих целей можно использовать [eslint](https://eslint.org/)
- [x]  Стоит пробрасывать ошибки для неверных входных данных и в целом обрабатывать все возможные случаи с  возможными ошибками

PS Если будут какие-то вопросы, пиши тут или мне в телегу [@Anton_ELagin](https://t.me/Anton_Elagin)

2023-02-09 11:21 UTC, AntonElagin commented on source/euclid.js
> +const euclid = function() {
Предлагаю использовать более современный вариант функций(Стрелочные функции)

Подробнее про них тут: https://learn.javascript.ru/arrow-functions-basics

2023-02-09 11:21 UTC, AntonElagin commented on source/euclid.js
> +    if (arguments.length === 0){
Работа через arguments достаточно устаревший подход. Советую использовать rest оператор

подробнее тут: https://learn.javascript.ru/rest-parameters-spread-operator#ostatochnye-parametry

2023-02-09 11:21 UTC, AntonElagin commented on source/euclid.js
> +    for (let i = 1; i < arguments.length; i++){
В js принято использовать методы массивов для итерации и для их изменения/модификации

Подробнее тут: https://learn.javascript.ru/array-methods

2023-02-09 11:21 UTC, AntonElagin commented on tests/euclid.js
> +	QUnit.test('На входе два числа', function (assert) {
Предлагаю написать тесты и на отрицательные кейсы. Например невалидные для сравнения данные, неверные типы и тп

2023-02-09 11:21 UTC, AntonElagin commented on source/euclid.js
> +const gcd = function(a, b) {
Предлагаю даже в функциях хелперах стараться использовать более говорящие названия для переменных.

2023-02-10 08:00 UTC, AntonElagin requested changes
осталось еще немного)

2023-02-10 08:00 UTC, AntonElagin commented on source/euclid.js
> +    if (!args.every(arg => {
Однострочные функции стрелки удобнее писать упрощенным синтаксисом.

Первые примеры тут как раз показывают, как этот упрощенный синтаксис выглядит: https://learn.javascript.ru/arrow-functions-basics

2023-02-10 08:00 UTC, AntonElagin commented on source/euclid.js
> +    if (args.length === 0) {
в js  данную проверку можно написать чуть короче.

2023-02-10 08:00 UTC, AntonElagin commented on source/euclid.js
> + * @param {number} args натуральные числа, для которых находится наибольший общий делитель
тут не совсем верный параметр получается, надо как-то иначе описать, сейчас складывается ощущения, что функция принимает только 1 параметр

2023-02-10 08:00 UTC, AntonElagin commented on source/euclid.js
> +        return Number.isInteger(arg) && (arg > 0)
```(arg > 0)``` - это уже скорее вкусовщина, но скобки необязательно ставить

2023-02-10 08:00 UTC, AntonElagin commented on source/euclid.js
> +    args.forEach(next => res = gcd(res, next));
Классно, что переписал на forEach, но можно сделать еще круче, почитай про ```reduce``` 

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

2023-02-11 11:21 UTC, AntonElagin requested changes

2023-02-11 11:21 UTC, AntonElagin commented on source/euclid.js
> +}
тут не хватает ```;```

2023-02-13 11:27 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Неплохая работа, молодец, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 11:27 UTC, DPeshkoff commented on source/euclid.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это такое и что оно делает)

2023-02-13 11:27 UTC, DPeshkoff commented on source/euclid.js
> +        throw new Error("Function requires at least one input parameter.");
Традиционно принято заключать в одиночные кавычки - `''`

2023-02-13 11:27 UTC, DPeshkoff commented on source/euclid.js
> +        throw new Error("Bad input parameters.");
А тут, кажется, выглядит [как...](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-02-13 11:27 UTC, DPeshkoff commented on tests/euclid.js
> -	});
Здесь не должно быть изменений - даже стилистических. Давай вернем, как было)

2023-02-13 15:51 UTC, Ogrebatel commented on source/euclid.js
> +        throw new Error("Bad input parameters.");
А будет ли это являться TypeError, если тут помимо типа переменной также проверяется его значение? Или лучше разделить эти проверки?

2023-02-13 18:07 UTC, DPeshkoff approved these changes

2023-02-13 18:07 UTC, closed without merging