Вяткин Александр
frontend-park-mail-ru/homework_2023_1 pull request #11
Opened 2023-02-08 19:10 UTC by MoraPresence

как настроить тесты в git action сходу не понял.........

2023-02-09 13:01 UTC, grishbar requested changes
Привет, добро пожаловать на курс фронтенда. Я буду проверять твое дз0.

В целом работа прекрасная, есть небольшие стилевые замечания, в остальном ок.

- [ ] добавить пустые строчки в конце файлов
- [ ] выкидывать ошибку вместо возвращения null
- [ ] перестать обрабатывать строки с числами

Если что-то непонятно или будут вопросы, пиши здесь или мне в телегу - https://t.me/niazox000

2023-02-09 20:49 UTC, grishbar requested changes
все норм давай только уберем ненужный код с ci и с кармой, почистим package.json и все будет ок

2023-02-10 15:46 UTC, grishbar requested changes
Отличная работа проделана, давай удалим ненужный код в gitignore учитывая, что в package.json сейчас ничего нет, то кажется можно весь файл удалить и кажется на этом все

2023-02-10 15:46 UTC, grishbar commented on .gitignore
> +lerna-debug.log
я понимаю, что ты откуда-то скопировал этот гитигнор, но на будущее в программирование принято, код который сейчас не используется не пушить в мастер, то есть создавай ты в работе такой гитигнор, учитывая что у тебя нет лерны некста и прочих штук, то этот код был бы излишним и ревью бы не прошел.
Потому что потом другому разработчику понадобится добавить что-то в гитигнор а там куча этих строчек не нужных и он либо потратит время на их чтение либо потратит время на рефакторинг чтобы удалить все лишнее (с гитигнором может не так страшно но будт этой какой-то продуктовый файл то было бы совсем не очень)

2023-02-13 03:08 UTC, grishbar requested changes
Уже на финишной прямой) Давай немножко еще подшаманим тесты и будет готово)

2023-02-13 03:08 UTC, grishbar commented on tests/rle.test.js
> +  });
тут получился тест аналогичный тесту на 19 строке, надо удалить один

2023-02-13 03:08 UTC, grishbar commented on tests/rle.test.js
> +  QUnit.test('rle отрабатывает верно без аргументов', function (assert) {
я бы поправил формулировку, что не отрабатывает верно, а выкидывает ошибку, если аргументов не было передано

2023-02-13 03:08 UTC, grishbar commented on tests/rle.test.js
> +  QUnit.test('rle отрабатывает верно на строке с одной заменой в начале', function (assert) {
Нужно переписать называние всех тестов, обычно в блоке ты называешь, что именно проверяют твои следующие тесты, соответственно, тут нужно везде написать - "rle с одной заменой" не стоит везде писать "отрабатывает верно", так как это добавляет лишнюю нагрузку на человека при чтении кода, что нужно избегать

2023-02-13 03:08 UTC, grishbar commented on tests/rle.test.js
> +  QUnit.test('rle отрабатывает верно без аргументов', function (assert) {
или еще лучше "rle без аргументов"

2023-02-13 03:08 UTC, grishbar commented on tests/rle.test.js
> +  QUnit.test('rle отрабатывает верно без аргументов', function (assert) {
и еще было бы правильно объединить все тесты с неправильным вводом в один блок

2023-02-13 08:20 UTC, grishbar approved these changes
Все, огонь 🔥 , передаю работу дальше

2023-02-13 11:38 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Хорошая работа, но есть пара вопросов к твоему решению (и очень много диффов там, где их быть не должно - может, откатим?))

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 11:38 UTC, DPeshkoff commented on source/rle.js
> +'use strict';
Можешь, пожалуйста, объяснить в реплае, зачем нужен use strict и почему он используется в работе?

2023-02-13 11:38 UTC, DPeshkoff commented on source/rle.js
> +  if (str == null || typeof str != 'string') {
[Строгие проверки лучше нестрогих](https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness)

А еще...

Такая проверка хорошая, но мы поймаем не все строки... а только их часть)
Подумай, что можно добавить в эту проверку, чтобы она стала полной

![изображение](https://user-images.githubusercontent.com/31134795/218446396-985b497d-0e22-41c7-a4a4-c42277c4a251.png)

2023-02-13 11:38 UTC, DPeshkoff commented on source/rle.js
> +    throw new Error("wrong input");
Кажется, [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError) подойдет лучше)

А еще традиционно строки заключаются в одиночные кавычки - `''`

2023-02-13 11:38 UTC, DPeshkoff commented on source/rle.js
> +  return str.replace(/(.)\1+/g, function (internalStr, symbol) {
А почему обычная функция, а не стрелочная?)

2023-02-13 14:04 UTC, MoraPresence commented on source/rle.js
> +'use strict';
Это говорит интерпретатору, что потенциально опасные конструкции JS будут запрещены и приведут к исключению. например нельзя присваивать значение в неопределенную переменную в этом режиме

Эта директива возникла вследствие того, что было необходимо исключить работу старого кода. use strict изменяет ранее принятый «плохой синтаксис» на настоящие ошибки

2023-02-13 15:04 UTC, DPeshkoff approved these changes

2023-02-13 15:08 UTC, closed without merging