Билалов Азат | Домашнее задание №0
frontend-park-mail-ru/homework_2023_1 pull request #12
Opened 2023-02-08 20:05 UTC by Azat-Bilalov

2023-02-09 13:19 UTC, grishbar requested changes
Привет, добро пожаловать на курс фронтенда. Я буду проверять твое дз0.

Получилось неплохое решение, вижу, что есть понимания основ языка, но пока, что еще не готов принять работу, нужные некоторые изменения:

- [ ] надо добавить JSDOC к функции - https://jsdoc.app/about-getting-started.html
- [ ] Нужно обработать все случаи некорректных данных
- [ ] Вынести функцию addLayer, написать на нее тесты, сделать ее чистой функцией

Если что-то непонятно или будут вопросы, пиши здесь или мне в телегу - https://t.me/niazox000

2023-02-09 13:19 UTC, grishbar commented on source/tree.js
> +    const trunk = '|';
небольшое улучшение: Такие константы можно вынести из функции и именовать их в SNAKE_CASE, так в мире js принятно делать с никогда не изменяемыми какими-либо магическими переменными

2023-02-09 13:19 UTC, grishbar commented on source/tree.js
> +    }
не все случаи обработал, подумай еще какие некорректные данные могут прийти

2023-02-09 13:19 UTC, grishbar commented on source/tree.js
> +    }
эту функцию лучше вынести из твоего метода tree, так как на каждый вызов твоей функции будет заново создаваться экземпляр функции addLayer, это лишняя работа, которая тебе не нужна, + отдельные функции проще читаются.
Также надо переделать эту функцию, чтобы она возвращала новый слой, а не мутировала какой-то внешний объект, в идеальном мире старайся всегда избегать написания не [чистых функций](https://habr.com/ru/post/437512/) потому что тогда ты создаешь пространство для багов, и не чистые функции очень сложно тестировать. Также предлагаю, тебе написать тесты и на эту отдельную функцию

2023-02-09 13:19 UTC, grishbar commented on tests/tree.js
> +	});
давай напишем побольше тестов на различные некорректные входные данные

2023-02-09 13:19 UTC, grishbar commented on tests/tree.js
> +	});
можно еще написать тест на елочку очень большой высоты и простестить последние две строки и верхние два строки

2023-02-09 13:19 UTC, grishbar commented on source/tree.js
> +const tree = (height) => {
надо добавить JSDOC к функции - https://jsdoc.app/about-getting-started.html

2023-02-13 03:12 UTC, grishbar approved these changes
Да, все круто!) Передаю работу дальше

2023-02-13 11:43 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Молодец, классная работа, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 11:43 UTC, DPeshkoff commented on source/tree.js
> +'use strict';
Можешь, пожалуйста, объяснить в реплае, зачем нужен use strict и почему он используется в работе?

2023-02-13 11:43 UTC, DPeshkoff commented on source/tree.js
> +const addLayer = (element, n, width) => {
А что будет, если приедет неправильный аргумент? Давай будем проверять входные значения)

2023-02-13 11:43 UTC, DPeshkoff commented on source/tree.js
> + * @param {Integer} n - Номер слоя.
Упс, у нас такого нет :с

Зато [есть...](https://developer.mozilla.org/en-US/docs/Glossary/Primitive)

2023-02-13 11:43 UTC, DPeshkoff commented on source/tree.js
> +    }
Кажется, будет лучше и здесь использовать что-то покруче простого цикла for)

2023-02-13 11:43 UTC, DPeshkoff commented on tests/tree.js
> +	});
Давай добавим еще тесты на некорректный ввод)

2023-02-13 19:07 UTC, Azat-Bilalov commented on source/tree.js
> +'use strict';
use strict нужен для включения строгого режима, т.е. активации стандарта ES6. Дело в том, что новые функциональные возможности в JS появлялись, а убирать старые стоило больших проблем из-за обратной совместимости (старые версии браузеров, насколько знаю, отваливаться). Поэтому строгий режим автоматически не подключается (не учитывая случаев, когда в коде используются классы и модули), а включается директивой use strict.
В работе строгий режим применяется для того, чтобы как раз задействовать новые возможности языка и отказаться от устаревших. Например, если раньше можно присвоить значение ранее не существовавшей переменной (x = 10), то стандарт ES6 гарантирует, что переменная обязательно будет создана с помощью let перед использованием

2023-02-13 19:46 UTC, DPeshkoff approved these changes

2023-02-13 19:46 UTC, closed without merging