Фикслер Леонид, Вариант №3
frontend-park-mail-ru/homework_2023_1 pull request #13
Opened 2023-02-08 20:19 UTC by reddiridabl666

2023-02-09 17:04 UTC, AntonElagin requested changes
Привет, добро пожаловать на курс фронтенда. Я буду проверять твое дз0.

Получилось неплохое решение, вижу, что есть понимания основ языка, но код можно еще слегка улучшить:

- [ ] Давай добавим JsDoc для всех функций
- [ ]  Давай приведем код в порядок. Нужно стараться оформлять код в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для этих целей можно использовать [eslint](https://eslint.org/)

PS Если будут какие-то вопросы, пиши тут или мне в телегу [@Anton_ELagin](https://t.me/Anton_Elagin)

2023-02-09 17:04 UTC, AntonElagin commented on source/roman.js
> +            if (digit == 4) {
лучше использовать строгую проверку равенств и неравенств

2023-02-10 20:50 UTC, reddiridabl666 commented on source/roman.js
> +        input === undefined || typeof input === 'object') {
Так функция будет возвращать NaN, а не падать при передаче в неё объектов или массивов

2023-02-11 11:45 UTC, AntonElagin requested changes
Остались буквально последние штрихи:

- [ ] проверь свой код на соответсвие кодстайлку, который ты для себя выбрал. (См. оформление ветвления(if-ов). может быть еще что-то найдешь, но основное if-ы)
- [x] обычно принято ставить ; после стрелочной функции, тк по сути мы просто объявили переменную. РS речь про случай, когда мы сохраняем функцию в пременную (```const func = (arg) => arg + 1;```) 
- [ ] Тут уже более спорная штука, но я бы вынес вспомогательные функции из основной и положил бы их на одном уровне вложенности. КМК так просто удобнее читать код.

2023-02-11 11:45 UTC, AntonElagin commented on source/roman.js
> +            return NaN;
Нужно стараться оформлять код в едином стиле

2023-02-13 12:07 UTC, AntonElagin requested changes

2023-02-14 11:26 UTC, AntonElagin requested changes

2023-02-14 16:41 UTC, AntonElagin commented on source/roman.js
> +    if (Number.isNaN(input) || input === null ||
Все-таки предлагаю переписать чуть проверку типов. Долго думал и сейчас дошло, сейчас например для boolean типа твоя функция упадет с ошибкой. Давай пойдем от обратного и проверим, что тип либо строк, либо число. Ну и докинем тест на бул)

2023-02-15 12:47 UTC, AntonElagin requested changes

2023-02-15 12:47 UTC, AntonElagin commented on source/roman.js
> +    if (typeof input !== 'string' && !Number.isFinite(input)) {
<img width="336" alt="Снимок экрана 2023-02-15 в 15 39 19" src="https://user-images.githubusercontent.com/49658104/219029640-86224c76-3229-468d-a943-803a29aa9df7.png">

1.Сейчас кейс с фото вызовет ошибку, хотя технически это тоже строка, но представленная объектом оберткой String

<img width="210" alt="Снимок экрана 2023-02-15 в 15 41 26" src="https://user-images.githubusercontent.com/49658104/219030070-424478dd-28d2-4b5b-b82c-300fea6e7577.png">
 
 а вот пример с объектом оберткой Number)
 
<img width="235" alt="Снимок экрана 2023-02-15 в 15 46 37" src="https://user-images.githubusercontent.com/49658104/219031097-44cca139-27ad-419c-a38d-172b689f841d.png">

 а вот пример с римским числом и объектом оберткой String

2023-02-15 17:21 UTC, AntonElagin commented on source/roman.js
> +    if (!input || !(input['constructor'] === String || (input['constructor'] === Number && isFinite(input)))) {
Я бы лучше проверял классы обертки через  instanceOf, а примитивы через typeof

2023-02-15 18:17 UTC, AntonElagin commented on source/roman.js
> +    return obj instanceof String || typeof obj === 'string'
Проверь ```;``` в конце строк

2023-02-15 18:24 UTC, AntonElagin requested changes

2023-02-15 18:24 UTC, AntonElagin commented on source/roman.js
> +    return obj instanceof String || typeof obj === 'string'
А вообще можно было написать однострочной стрелкой

2023-02-16 10:33 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-16 10:33 UTC, DPeshkoff commented on source/roman.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-16 10:33 UTC, DPeshkoff commented on source/roman.js
> +    if (Number.isNaN(numberInput)) {
А чем отличаются между собой `Number.isNaN()` и `isNaN()` ? Почему выбрал именно первое?

2023-02-16 18:17 UTC, reddiridabl666 commented on source/roman.js
> +'use strict';
"use strict" запрещает использование устаревших/небезопасных конструкций, например, объявление переменных без var/let/const

2023-02-16 18:25 UTC, reddiridabl666 commented on source/roman.js
> +    if (Number.isNaN(numberInput)) {
В данном случае разницы нет, но Number.isNaN( ) строже, т.к. он не конвертирует передаваемое значение в число, и поэтому возвращает true только именно для NaN. А метод isNaN( ), например, вернёт true для undefined или строки, не содержащей числа

2023-02-16 19:30 UTC, closed without merging