Кулькина Дарья Вариант 4
frontend-park-mail-ru/homework_2023_1 pull request #14
Opened 2023-02-08 20:29 UTC by staurran

2023-02-09 10:45 UTC, grishbar requested changes
Привет, добро пожаловать на курс фронтенда. Я буду проверять твое дз0.

Получилось неплохое решение, вижу, что есть понимания основ языка, но нужно немного переделать дз:

- [ ] Можно еще написать немного тестов, например с повторяющимися элементами массива или же с объектами внутри массива, попробуй придумать еще какие-нибудь тесты)
- [ ] И нужно избавиться от использования встроенной функции reverse 
- [ ] Давай добавим JsDoc. Он поможет задокументировать твой код. https://jsdoc.app/

Если что-то непонятно или будут вопросы, пиши здесь или мне в телегу - https://t.me/niazox000

2023-02-09 10:45 UTC, grishbar commented on source/inverse.js
> +};
Отличное решение, прекрасное использование встроенных функций массива 👍 Если бы это было в настоящем проекте, то так бы и пошло в прод, но это учебное задание и тут не стоит пользоваться функцией reverse, так, что давай реализуем ее самостоятельно.

2023-02-09 12:55 UTC, staurran commented
Запушен новый вариант решения без использования reverse

2023-02-09 22:42 UTC, grishbar requested changes
Работа стала намного лучше, есть еще два пункта, которые надо доработать:

- [x] Обрабаотать некорректные входные параметры и написать на это тесты
- [ ] Избавиться от let там, где можно использовать const

2023-02-09 22:42 UTC, grishbar commented on source/inverse.js
> +const inverse = (numbers, stop = 0) => {
Забыл указать, надо добавить проверку входных данных, что они пришли корректные, в противном случае выкидывать ошибку, и не забыть покрыть тестами

2023-02-09 22:42 UTC, grishbar commented on source/inverse.js
> +    let newNumbers = numbers.slice()
если переменную не переопределяешь то всегда лучше использовать const

2023-02-10 09:05 UTC, staurran commented
Здравствуйте, у меня остался вопрос по документации: нужно ли указывать в строчке с return ошибку и ее описание при неправильно введенных данных?

2023-02-10 15:26 UTC, grishbar commented
> 

не обязательно, можешь написать любой стандартный метод и провалить в него и посмотреть как документацию описывают сами разработчики js (единственное там у них typescript а у нас jsdoc но смысл одинаковый), они обычно не описывают что возвращает функция, и не описывают ошибки

2023-02-10 15:34 UTC, grishbar requested changes
Отличная работа проделана, работа почти готова, остался один недочет:

- [ ] Разбить тесты по группам и дать осмысленное названия этим группам

2023-02-10 15:34 UTC, grishbar commented on source/inverse.js
> +    }
надо не возвращать ошибку, а выкидывать ее

2023-02-10 15:34 UTC, grishbar commented on source/inverse.js
> +    const newNumbers = numbers.slice()
можно скопировать деструктуризацией:
```
const newNumbers = [...numbers];
```

2023-02-10 15:34 UTC, grishbar commented on tests/inverse.js
> +	QUnit.test('Дополнительно написанные тесты', function (assert) {
Каждый блок тестов ты как-то группируешь, чтобы потом, во время разработки было проще, дебажить, тебе в консоль будет падать называние блока тестов, которые упали, и ты сразу знаешь куда идти искать, и про что эти тесты. Так, что давай разделим все твои тесты на осмысленные блоки и дадим им соответствующие названия, которые соотносятся с тем, что твои тесты проверяют

2023-02-10 20:55 UTC, staurran commented
Получается деструктуризация лучше чем slice()?

2023-02-11 16:01 UTC, grishbar commented
> Получается деструктуризация лучше чем slice()?

Не, тут нет особой разницы, просто предложил чуть более привичный метод копирования массива

2023-02-11 16:11 UTC, staurran commented
Хорошо, а по коду нужны исправления еще?

2023-02-11 16:16 UTC, grishbar requested changes
еще чуть чуть осталось добить, смотри новые комментарии

2023-02-11 16:16 UTC, grishbar commented on tests/inverse.js
> +		assert.throws(function () {
можно еще добавить тестов, например на NaN, Infinity, -Infinity, можешь подумать еще какие edge кейсы надо учесть

2023-02-11 16:16 UTC, grishbar commented on source/inverse.js
> +        throw "The second parameter is not integer"
почему тут не обернула классом ошибки?

2023-02-11 16:16 UTC, grishbar commented on source/inverse.js
> +        throw "The second parameter is not integer"
Давай, еще тогда напишем тест, что при некорректных данных твоя функция вовзращает экземпляр класса ошибки

2023-02-11 16:54 UTC, staurran commented on source/inverse.js
> +        throw "The second parameter is not integer"
Так надо возвращать или выбрасывать ошибку? Или одну так другую так ошибку обработать?

2023-02-13 02:41 UTC, grishbar commented on source/inverse.js
> +        throw "The second parameter is not integer"
Не совсем корректно выразился, исправлюсь, надо написать тест, что твоя функция выбрасывает объект являющийся экземпляром класса Error

2023-02-13 02:46 UTC, grishbar commented on source/inverse.js
> +        throw "The second parameter is not integer"
Так, что давай добавим такой тест, раз уж в этом была ошибка во время разработки и готово будет

2023-02-13 14:25 UTC, grishbar approved these changes
Отлично, прекрасная работа проделана! Передаю дальше

2023-02-13 15:47 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Хорошая работа, но есть вопросы к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 15:47 UTC, DPeshkoff commented on source/inverse.js
> +        throw new Error("The first parameter is not array")
Кажется, [лучше...](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-02-13 15:47 UTC, DPeshkoff commented on source/inverse.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовала в работе?

2023-02-13 15:47 UTC, DPeshkoff commented on source/inverse.js
> +    const newNumbers = [...numbers]
Не пренебрегай ; - здесь и на всех нужных строчках

Иначе может произойти кое-что грустное:

![изображение](https://user-images.githubusercontent.com/31134795/218504658-c7509dad-0af5-4278-9826-bea8c597bcf4.png)

2023-02-13 15:51 UTC, staurran commented on source/inverse.js
> +    const newNumbers = [...numbers]
Исправила)

2023-02-13 18:41 UTC, staurran commented on source/inverse.js
> +'use strict';
честно, я столкнулась с этой строчкой в примере первый раз. Загуглила, что это более строгий режим выполнения и решила, что возможно мне это будет полезнее, т к я фактически не имела дела с js, поэтому лучше сразу привыкать к более строгому варианту

2023-02-13 19:47 UTC, DPeshkoff approved these changes

2023-02-13 19:47 UTC, closed without merging