Роменский Игнат Вариант 17
frontend-park-mail-ru/homework_2023_1 pull request #15
Opened 2023-02-08 20:46 UTC by KolobokMysnoy

Игнат Роменский Вариант 17

2023-02-09 21:54 UTC, rflban commented
Привет! Я буду проверять твое ДЗ0! Перенеси, пожалуйста, имя, фамилию и номер варианта в названия пулл реквеста

2023-02-11 14:56 UTC, rflban requested changes

2023-02-11 14:56 UTC, rflban commented on source/plainify.js
> +function plainify(objectToSimplify) {
какие еще способы объявления функций знаешь? чем они отличаются друг от друга?

2023-02-11 14:56 UTC, rflban commented on source/plainify.js
> +function plainify(objectToSimplify) {
давай добавим валидацию и jsdoc

2023-02-11 14:56 UTC, rflban commented on source/plainify.js
> +    for (let key in objectToSimplify) {
перепиши пожалуйста с использованием встроенных в язык методов массивов вместо циклов

2023-02-11 14:56 UTC, rflban commented on source/plainify.js
> +        if (typeof(objectToSimplify[key]) == 'object') {
это точно исчерпывающая проверка? протестируй на разных входных данных

2023-02-11 14:56 UTC, rflban commented on source/plainify.js
> +    let simpleObj = {}
почему именно let? какие есть альтернативы и чем они отличаются?

2023-02-11 14:56 UTC, rflban commented on tests/plainify.js
> +
не хватает тест кейсов, в которых на вход подается всякий мусор

2023-02-12 00:48 UTC, KolobokMysnoy commented on tests/plainify.js
> +
Добавил в самом конце тест на разные данные

2023-02-12 00:49 UTC, KolobokMysnoy commented on source/plainify.js
> +        if (typeof(objectToSimplify[key]) == 'object') {
Добавил тесты на разных входных данных. Добавил проверку в самом начале выполнения функции.

2023-02-12 00:49 UTC, KolobokMysnoy commented on source/plainify.js
> +function plainify(objectToSimplify) {
Добавил jsdoc и сделал валидацию данных на входе

2023-02-12 00:56 UTC, KolobokMysnoy commented on source/plainify.js
> +    let simpleObj = {}
let, const, var
let и const взаимодействую с лексическим окружением, то есть если прописаны внутри { }, то они видны только там. Var игнорирует лексическое окружение и выходи наружу, также его объявление перемещается в самое начало блока выше, то есть поднимается. У var можно делать два объявления. 

const говорит, что мы не будем изменять данную переменную, а также мы не сможем её поменять, если не касается объектов. Они указывают на определённую память, поэтому внутри значения можно менять, а саму ссылку нет.

let позволяет объявить переменную, более новый способ.

2023-02-12 00:57 UTC, KolobokMysnoy commented on source/plainify.js
> +    for (let key in objectToSimplify) {
переписал с использованием  .forEach

2023-02-12 02:05 UTC, KolobokMysnoy commented on source/plainify.js
> +function plainify(objectToSimplify) {
function(Input) {} -- обычная
(Input) => {} -- стрелочная

this у стрелочной функции берётся из внешнего контекста
стрелочная не может быть конструктором
У обычной функции нет неявного return.
Стрелочные функции не имеют arguments.

2023-02-12 08:16 UTC, rflban commented on source/plainify.js
> +function plainify(objectToSimplify) {
добавь примеры использования пожалуйста, без контекста неочевидно как функция вложенные поля разворачивает

2023-02-12 08:29 UTC, rflban requested changes

2023-02-12 08:29 UTC, rflban commented on source/plainify.js
> +        return {}
давай придерживаться этого стиля написания кода
https://learn.javascript.ru/coding-style

2023-02-12 08:29 UTC, rflban commented on source/plainify.js
> +    fieldsFromObject.forEach(fieldOfObject => {
вместо forEach можно использовать другой метод, чтобы не писать 
```js
const simpleObj = {};
```
а в результате вызова этого метода сразу получить нужный объект

2023-02-12 08:29 UTC, rflban commented on source/plainify.js
> +        return {}
в случае невалидных входных данных лучше кидать исключение

2023-02-12 08:29 UTC, rflban commented on source/plainify.js
> +                simpleObj[fieldOfObject[0] + '.' + innerField[0]] = innerField[1]
лучше использовать интерполяцию строк

2023-02-12 08:29 UTC, rflban commented on tests/plainify.js
> +			alert('hi')
а зачем алерт?

2023-02-12 12:22 UTC, KolobokMysnoy commented on source/plainify.js
> +function plainify(objectToSimplify) {
Добавил пример использования. Нормально ли показывать структуру таким образом?
`* //structure of simple object`
`* //structure of simple object`
`* //'nestFirstLayer.nestSecondLayer.valueInSecondLayer': 3;`
`* //'nestFirstLayer.valueInFirstLayer': 2;`
`* //'valueInObject': 1`

2023-02-12 12:23 UTC, KolobokMysnoy commented on source/plainify.js
> +        return {}
Исправил. Хотел уточнить, когда мы выполняем присваивание и переносим строку, должны мы делать отступ или нет? Не смог найти ответ на этот вопрос.

2023-02-12 12:24 UTC, KolobokMysnoy commented on source/plainify.js
> +    fieldsFromObject.forEach(fieldOfObject => {
Изменил на reduce.

2023-02-12 12:24 UTC, KolobokMysnoy commented on source/plainify.js
> +        return {}
Изменил, теперь кидается исключение

2023-02-12 12:24 UTC, KolobokMysnoy commented on source/plainify.js
> +                simpleObj[fieldOfObject[0] + '.' + innerField[0]] = innerField[1]
Исправлено

2023-02-12 12:26 UTC, KolobokMysnoy commented on tests/plainify.js
> +			alert('hi')
До этого писал alert, когда что то изучал. По привычке написал. Убрал.

2023-02-12 19:15 UTC, rflban commented on source/plainify.js
> +        return {}
лучше переносить

2023-02-12 19:23 UTC, rflban requested changes

2023-02-12 19:23 UTC, rflban commented on source/plainify.js
> +            fieldOfObject[1] !== null
вместо обращения по индексу к элементам `fieldOfObject` лучше использовать деструктуризацию

2023-02-12 22:19 UTC, KolobokMysnoy commented on source/plainify.js
> +            fieldOfObject[1] !== null
Исправил, также для innerField.

2023-02-13 12:00 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Хорошая работа, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 13:53 UTC, KolobokMysnoy commented on source/plainify.js
> +    if (typeof(objectToSimplify) !== "object" || objectToSimplify === null) {
Исправил, добавил данные случаи в тесты

2023-02-13 13:54 UTC, KolobokMysnoy commented on source/plainify.js
> +        throw Error("Not object or null");
Исправил

2023-02-13 13:54 UTC, KolobokMysnoy commented on source/plainify.js
> +            typeof(valueOfField) === "object"
Добавил функцию для проверки

2023-02-13 13:54 UTC, KolobokMysnoy commented on tests/plainify.js
> +		let nested = {}
Исправил

2023-02-13 13:55 UTC, KolobokMysnoy commented on tests/plainify.js
> +			'deep.nested.object.fields.hi': functionToInputInObjects
Показать, что он функцию оставляет в объекте тоже, нужно было убрать это?

2023-02-13 14:11 UTC, KolobokMysnoy commented on source/plainify.js
> +'use strict';
Данная строка служит для включения современного режима в JS. 
* Превращает предупреждения в ошибки.
* Убирает возможность дублировать имена переменных и функций

2023-02-13 14:42 UTC, DPeshkoff commented on tests/plainify.js
> +			'deep.nested.object.fields.hi': functionToInputInObjects
Понял, не, можем оставить

2023-02-13 14:46 UTC, DPeshkoff approved these changes

2023-02-13 14:47 UTC, closed without merging