Данила Поляков
frontend-park-mail-ru/homework_2023_1 pull request #16
Opened 2023-02-08 21:59 UTC by qqq4u

2023-02-09 20:59 UTC, wd055 requested changes

2023-02-09 20:59 UTC, wd055 commented on source/set.js
> +const set = function (object, path, value) {
Почему именно так объявлена функция? Есть ли другой способ ее проинициализировать, в чем разница?

2023-02-09 20:59 UTC, wd055 commented on source/set.js
> +}
Не хватает еще одной строчки

2023-02-09 20:59 UTC, wd055 commented on source/set.js
> +    let lastField = fields[fields.length - 1];
Может как-то по-другому можешь получить последний элемент?

2023-02-09 20:59 UTC, wd055 commented on source/set.js
> +        console.log(fields[i]);
Кажется, это отладочная консоль, может она лишняя?

2023-02-09 20:59 UTC, wd055 commented on source/set.js
> +    for (let i = 1; i < fields.length - 1; i++) {
Лучше использовать не цикл, а встроенный метод

2023-02-09 20:59 UTC, wd055 commented on source/set.js
> +const set = function (object, path, value) {
Давай добавим JSDoc

2023-02-09 21:00 UTC, wd055 commented
Привет! Я буду проверять твоё ДЗ0. Хорошая первая итерация, давай займемся улучшениями!

2023-02-09 21:07 UTC, wd055 commented on source/set.js
> +    let fields = path.split('.');
Тут и еще в паре мест стоит по-другому объявлять переменные? Можешь сказать почему?

2023-02-10 06:40 UTC, qqq4u commented on source/set.js
> +    let fields = path.split('.');
Вы имеете в виду константы? 
если так, то стоит объявить некоторые переменные константами поскольку далее по коду никаких изменений к ним не применяется

2023-02-10 06:43 UTC, qqq4u commented on source/set.js
> +}
Не до конца понимаю

2023-02-10 07:32 UTC, qqq4u commented on source/set.js
> +const set = function (object, path, value) {
В моём случае я использую функциональное выражение. Создаётся анонимная функция, значение которой присвается в переменную
Можно ещё вот так:
1) "function set(object, path, value)" - инициализировать функцию
2) const set = function setFunc (object, path, value) - тут я задал имя функции, но это может быть необходимо только в случае, если мы хотим рекурсивно вызвать эту функцию внутри неё, ведь с анонимной мы так сделать не можем.
Поскольку set возвращает значение функции, которая пробегает под копотом(тоесть установленное значение),  я принял set как константу, поскольку менять его мы не можем и не должны. Функция анонимна поскольку её вызов внутри самой себя не предусматрвиается.

2023-02-10 07:37 UTC, qqq4u commented on source/set.js
> +    let lastField = fields[fields.length - 1];
fields.slice(-1), поправил в коде

2023-02-10 08:03 UTC, wd055 commented on source/set.js
> +    let fields = path.split('.');
Да, именно!)

2023-02-10 08:05 UTC, wd055 commented on source/set.js
> +const set = function (object, path, value) {
Хороший ответ! Больше имел в виду стрелочную функцию, предлагаю объявить ее именно так

2023-02-10 08:07 UTC, wd055 commented
И, пожалуйста, не резолвь треды, так будет легче и быстрее перепроверять

2023-02-10 08:08 UTC, qqq4u commented
> И, пожалуйста, не резолвь треды, так будет легче и быстрее перепроверять

сори)

2023-02-10 08:08 UTC, wd055 commented on source/set.js
> +    let lastField = fields[fields.length - 1];
Лучше используй `.at(-1)`. Опять же, можешь сказать почему?

2023-02-10 08:15 UTC, qqq4u commented on source/set.js
> +    let lastField = fields[fields.length - 1];
Потому что slice создаёт в памяти копию?

2023-02-10 08:17 UTC, qqq4u commented on source/set.js
> +    let lastField = fields[fields.length - 1];
Да, и ещё slice возвращает массив

2023-02-10 09:20 UTC, wd055 commented
Супер!

2023-02-10 11:34 UTC, wd055 commented
Убери папку out, пожалуйста. А то снему аппрув)

2023-02-12 11:33 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-12 11:33 UTC, DPeshkoff commented on source/set.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-12 11:33 UTC, DPeshkoff commented on source/set.js
> + * @constructor
А это разве конструктор?)

2023-02-12 11:33 UTC, DPeshkoff commented on source/set.js
> +const set = (object, path, value) => {
А если на вход будут поданы переменные с неправильными типами? К примеру, path, которая будет Function?)

Нужны проверки + тесты на некорректный ввод)

2023-02-12 11:33 UTC, DPeshkoff commented on tests/set.js
> +		assert.deepEqual(set({ foo: 'bar' }, '.foo', 'baz'), { foo: 'baz' });
Не очень понял, зачем здесь изменения

2023-02-12 11:49 UTC, qqq4u commented on tests/set.js
> +		assert.deepEqual(set({ foo: 'bar' }, '.foo', 'baz'), { foo: 'baz' });
Просто как-то интересно я видимо комментил/раскоменчивал код, образовались пробелы

2023-02-12 11:50 UTC, qqq4u commented on source/set.js
> + * @constructor
function)

2023-02-12 11:51 UTC, qqq4u commented on source/set.js
> +'use strict';
Если вкратце - то включает строгий режим без совместимости со старыми версии ECMAScript, открывает больше функционала современного js-а. Рекомендовали включать, ибо совместимость ненужна и функционал побольше. Но, как я понимаю, конкретно здесь это не необходимо

2023-02-12 11:58 UTC, DPeshkoff commented on source/set.js
> +'use strict';
Да нет, новый код лучше как раз писать в новом режиме) 
Остальное в целом ок)

2023-02-12 12:20 UTC, DPeshkoff requested changes

2023-02-12 12:20 UTC, DPeshkoff commented on source/set.js
> +        throw Error('Path need to be a string!');
Лучше [вот это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError))

2023-02-12 12:20 UTC, DPeshkoff commented on source/set.js
> +    if (typeof path !== 'string'){
Такая проверка хорошая, но мы поймаем не все строки... а только их часть)
Подумай, что можно добавить в эту проверку, чтобы она стала полной
![изображение](https://user-images.githubusercontent.com/31134795/218310631-1ab0a7e2-48f2-44be-8f4e-da868f6f0fcf.png)

2023-02-12 12:20 UTC, DPeshkoff commented on tests/set.js
> +	});
Давай добавим тесты на некорректный ввод)

2023-02-12 12:20 UTC, DPeshkoff commented on tests/set.js
> +		assert.deepEqual(set({ foo: 'bar' }, '.foo', 'baz'), { foo: 'baz' });
Гоу починим?)

2023-02-13 20:08 UTC, DPeshkoff requested changes

2023-02-13 20:08 UTC, DPeshkoff commented on tests/set.js
> +		assert.deepEqual(set({foo:'bar'}, '.foo', 'baz'), {foo:'baz'});
diff(

2023-02-13 20:08 UTC, DPeshkoff commented on source/set.js
> +        throw new TypeError(`Wrong object type`);
Кажется, можно просто одиночные кавычки здесь и на 30-й)

2023-02-14 14:38 UTC, closed without merging