Ярослав Кузьмин, вариант 3
frontend-park-mail-ru/homework_2023_1 pull request #17
Opened 2023-02-08 22:16 UTC by yarikTri

2023-02-09 19:09 UTC, wd055 requested changes

2023-02-09 19:09 UTC, wd055 commented on source/roman.js
> +    for (let pos = romanDict.length - 1; arabicNum > 0; --pos) {
Тут так же может можно обойтись без цикла?

2023-02-09 19:09 UTC, wd055 commented on source/roman.js
> +const arabicDict = [1,   4,    5,   9,    10,  40,   50,  90,   100, 400,  500, 900,  1000];
Почему Dict?

2023-02-09 19:09 UTC, wd055 commented
Привет! Я буду проверять твоё ДЗ0. Хорошая первая итерация, давай займемся улучшениями!

2023-02-10 08:32 UTC, yarikTri commented on source/roman.js
> +const roman = input => {
Вопрос: правильнее внести все 4 вспомогательные функции внутрь основной функции roman или оставить их снаружи? И если второй вариант, то JSDoc логично же всё равно написать только для основной функции? Спасибо

2023-02-10 08:46 UTC, yarikTri commented on source/roman.js
> +const arabicDict = [1,   4,    5,   9,    10,  40,   50,  90,   100, 400,  500, 900,  1000];
Dict не в смысле словарь как структура, а словарь всех возможных значений, соответсвующих в рамках задачи словарю всех возможных римских чисел
Но вообще, согласен, поменял на arabicNums :)

2023-02-10 08:47 UTC, yarikTri commented on source/roman.js
> +        if (!romanArabicBind.has(str[i])) return false;
RegExp

2023-02-10 09:23 UTC, wd055 commented on source/roman.js
> +const roman = input => {
Можешь JSDoc написать только для основной функции. Вносить их во внутрь особо смысла не вижу

2023-02-10 09:23 UTC, wd055 commented on source/roman.js
> +        if (!romanArabicBind.has(str[i])) return false;
Именно)

2023-02-10 09:25 UTC, wd055 requested changes

2023-02-10 09:25 UTC, wd055 commented on source/roman.js
> +    const arabicNums = [1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000];
Не стоило их заносить во внутрь функции. Понимаешь, почему?

2023-02-10 09:26 UTC, yarikTri commented on source/roman.js
> +    while (pos > 0) {
Не могу разобраться, какой метод подходит в этом случае, ведь мы идём с конца вперёд и работаем с несколькими символами (curr, prev). Хотя, можно и перевернуть строку... В общем, был бы рад наставлению на верный путь)

2023-02-10 09:27 UTC, yarikTri commented on source/roman.js
> +    const arabicNums = [1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000];
Хотел избавиться от глобальных переменых

2023-02-11 10:31 UTC, wd055 commented on source/roman.js
> +    const arabicNums = [1, 4, 5, 9, 10, 40, 50, 90, 100, 400, 500, 900, 1000];
Она не совсем глобальная была бы. Глобальной только для этого файла

2023-02-11 10:34 UTC, wd055 requested changes

2023-02-11 10:34 UTC, wd055 commented on source/roman.js
> +    while (pos > 0) {
Ответил в лс, что reduceRight может подходит

2023-02-11 10:34 UTC, wd055 commented on source/roman.js
> +    if (!Number.isInteger(num) || num < 0) return false;
Ты ведь можешь сразу возвращать значение, просто инвертируй его

2023-02-12 11:42 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Неплохая работа, молодец, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-12 11:42 UTC, DPeshkoff commented on source/roman.js
> +'use strict';
Можешь, пожалуйста, объяснить в реплае, зачем нужен use strict и почему он используется в работе?

2023-02-12 11:42 UTC, DPeshkoff commented on source/roman.js
> +const isValidRomanNum = (str) => {
Я думаю, что JSDoc должен быть ко всем функциям в работе

Добавишь, пожалуйста?

2023-02-12 11:42 UTC, DPeshkoff commented on source/roman.js
> +    if (isValidArabicToRomanNum(input)) return arabicToRoman(input);
Очень хочется разнести на новые строчки - это повысит читаемость кода)

Ниже тоже такое есть

2023-02-12 11:49 UTC, yarikTri commented on source/roman.js
> +const isValidRomanNum = (str) => {
Окей!
Говорил с ментором по этому поводу, посчитали иначе
Скопирую из своего предыдущего коммита)

2023-02-12 11:51 UTC, yarikTri commented on source/roman.js
> +    if (isValidArabicToRomanNum(input)) return arabicToRoman(input);
С фигурными скобками или без является лучшим решением в таком случае?

2023-02-12 11:57 UTC, DPeshkoff commented on source/roman.js
> +    if (isValidArabicToRomanNum(input)) return arabicToRoman(input);
С фигурными, так нагляднее)

2023-02-12 12:03 UTC, yarikTri commented on source/roman.js
> +'use strict';
Строгий режим выполнения
Если объяснять своими словами, нужен для того, чтобы разработчик не смог сломать совместимость со старыми браузерами. Так интерпретатор будет определять небезопасные конструкции и функции, запутывающие код, и предотвращать использование слов, которые в будущем могут стать ключевыми. На все перечисленные действия будут выкидваться ошибки, которых не было бы без строгого режима.
Использую в работе в качестве good practice)

2023-02-12 12:23 UTC, DPeshkoff requested changes

2023-02-12 12:23 UTC, DPeshkoff commented on source/roman.js
> +    if (typeof str !== 'string') return false;
Еще вот тут,

2023-02-12 12:23 UTC, DPeshkoff commented on source/roman.js
> +    if (typeof num === 'string') num = Number(num);
и тут

2023-02-12 12:28 UTC, DPeshkoff commented on source/roman.js
> +    if (typeof num === 'string') {
Такая проверка хорошая, но мы поймаем не все строки... а только их часть)
Подумай, что можно добавить в эту проверку, чтобы она стала полной
![изображение](https://user-images.githubusercontent.com/31134795/218311031-2a397f62-2087-439d-987d-a5b3968f2bd0.png)

2023-02-12 12:30 UTC, yarikTri commented on source/roman.js
> +    if (typeof num === 'string') {
num instanceof String!

2023-02-12 12:38 UTC, DPeshkoff commented on source/roman.js
> +    if (typeof str !== 'string' || str instanceof String) {
Верно, но здесь нам нужны как раз не строки - поэтому нужно проверять, что оно _не_ `instanceof String `

2023-02-12 12:39 UTC, yarikTri commented on source/roman.js
> +    if (typeof str !== 'string' || str instanceof String) {
Поторопился...

2023-02-12 12:43 UTC, DPeshkoff commented on source/roman.js
> +    if (typeof str !== 'string' || !(str instanceof String)) {
А еще у нас здесь такое условие не сработает, потому что оно "или")

Для корректной работы нужно "и"

2023-02-12 12:43 UTC, DPeshkoff commented on source/roman.js
> +    if (typeof str !== 'string' || str instanceof String) {
Бывает, я вот тоже не сразу заметил, что там "или")

2023-02-12 12:46 UTC, DPeshkoff approved these changes

2023-02-12 12:46 UTC, closed without merging