Винокуршин Валерий, вариант 9
frontend-park-mail-ru/homework_2023_1 pull request #18
Opened 2023-02-08 22:33 UTC by vvinokurshin

2023-02-12 12:27 UTC, Nikita-Boyarskikh requested changes
Привет, добро пожаловать на курс фронтенда!
Меня зовут Никита, я буду проверять твое дз0

Классная работа) хорошо продуманы тесты, код подробно задокументирован
Есть несколько небольших замечаний по стилю, а так всё круто!

PS По любым вопросам можешь писать тут или мне в телегу [@Nikita_Boyarskikh](https://t.me/Nikita_Boyarskikh)

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> + * @param {Array} words массив строк
Можно более точно указать тип параметра: не "какой-то массив", а именно "массив строк"
Дока: https://jsdoc.app/tags-param.html

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> + * @example
Лайк за примеры использования, во многих документациях их очень не хватает 👍

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on tests/anagram.js
> +		assert.throws(function() {
Тут тоже лаконичнее использовать arrow function

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +    if (!(words instanceof Array)) {
Проверку на массив трушнее производить встроенным методом 
Тут рассказано, почему: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray#instanceof_vs._array.isarray

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +    let result = {};
Переменная `result` не перезаписыватся дальше по коду, так что тут уместнее использовать `const`
Да, это непривычно, что ты можешь модифицировать `const` переменную, но, на самом деле, значение самой переменной-то как раз и не изменяется, потому что объект остаётся тот же, ссылка на него постоянна

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +        let cleaned = word.split('').sort().join('');
Тут тоже уместнее `const`

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +        }
Это можно чуть короче написать с помощью новомодного [Nullish coalescing assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment) (но это вкусовщина, поэтому не настаиваю :)

```suggestion
        result[cleaned] ??= [];
        result[cleaned].push(word);
```

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +    words.forEach(word => {
Это отличный пример для использования `reduce`, давай попробуем на `reduce` переписать!

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +    return groups.filter(group => group.length != 1);
В JS почти всегда стоит использовать строгое равенство и неравенство, потому что `'1' != 1` даст `false`, например, что потом очень сложно дебажить будет
Понятно, что в данном примере такое почти невозможно, но лучше взять за привычку и всегда использовать строгое сравнение

2023-02-12 12:27 UTC, Nikita-Boyarskikh commented on tests/anagram.js
> +		const input = ['марш', 'шарм', 'шрам'];
Давай тут и дальше добавим пробелы внутри квадратных скобок по аналогии с уже существующим кодом. Нужно стараться оформлять код в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для автоматизации проверки стиля кода можно использовать [eslint](https://eslint.org/)

2023-02-13 08:21 UTC, Nikita-Boyarskikh requested changes

2023-02-13 08:21 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +    if (!(Array.isArray(words))) {
Тут скобочки больше не нужны

2023-02-13 08:21 UTC, Nikita-Boyarskikh commented on tests/anagram.js
> +		assert.throws(function() {
Ну и здесь тоже нужно по-аналогии с тем, как выше ты поправил, заменить на arrow function

2023-02-13 08:22 UTC, Nikita-Boyarskikh commented
Последний рывок!

2023-02-14 07:43 UTC, Nikita-Boyarskikh requested changes

2023-02-14 07:43 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +    words.forEach(word => {
Лучше всегда оборачивать аргументы в () - так проще добавлять новые аргументы + для однообразия кода

2023-02-14 07:43 UTC, Nikita-Boyarskikh commented on source/anagram.js
> +    })
Тут не хватает точки с запятой
JS позволяет не писать в конце выражения точку с запятой, но лучше весь код писать одинаково - либо везде писать точку с запятой, либо - нет
[Вот советы по оформлению кода](https://learn.javascript.ru/coding-style)
В дальнейшем, для автоматизации проверки стиля кода можно использовать [eslint](https://eslint.org/)

2023-02-14 07:55 UTC, Nikita-Boyarskikh approved these changes

2023-02-14 15:05 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-14 15:05 UTC, DPeshkoff commented on source/anagram.js
> +        if (typeof word !== 'string') {
Кажется, проверка не полная:

![изображение](https://user-images.githubusercontent.com/31134795/218775955-50bd012b-83ad-4d8d-bed1-4ad2e64c4cb4.png)

2023-02-14 15:05 UTC, DPeshkoff commented on tests/anagram.js
> +	QUnit.test('Функция работает правильно (обычный тест)', function (assert) {
Давай уберем отсюда разницу с изначальным кодом, ее быть не должно)

2023-02-14 15:05 UTC, DPeshkoff commented on tests/anagram.js
> +	});
А если ввод будет совсем некорректным? NaN, undefined, null? Давай напишем на это тесты)

2023-02-14 15:05 UTC, DPeshkoff commented on source/anagram.js
> +const anagram = (words) => {
Можешь, пожалуйста, объяснить, чем обычные функции отличаются от стрелочных?

2023-02-14 15:05 UTC, DPeshkoff commented on source/anagram.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-14 15:05 UTC, DPeshkoff commented on source/anagram.js
> +}
1) Почему решил написать обычную функцию, а не стрелочную?
2) Сюда тоже бы добавить JSDoc)

2023-02-14 16:51 UTC, vvinokurshin commented on source/anagram.js
> +const anagram = (words) => {
1. У стрелочных функций более удобный и компактный синтаксис
2. У стрелочных функций нет "this"

2023-02-14 16:55 UTC, vvinokurshin commented on source/anagram.js
> +'use strict';
Это строчка означает использование строго режима 
В этом режиме интерпретатор явно выбрасывает ошибки на действия, которые раньше пропускал (небезопасные конструкции, предотвращает использование ключевых слов как названий)

Использовал в коде , это позволяет заранее предотвратить некоторые ошибки, ну и считается хорошим тоном)

2023-02-14 16:57 UTC, vvinokurshin commented on source/anagram.js
> +}
Показалось, что отдельная функция будет тут уместнее, нежели стрелочная)

2023-02-14 19:40 UTC, DPeshkoff requested changes

2023-02-14 19:40 UTC, DPeshkoff commented on source/anagram.js
> +}
Ну, если у них более компактный и удобный синтаксис... я бы сделал стрелочной)

2023-02-14 19:40 UTC, DPeshkoff commented on source/anagram.js
> +const anagram = (words) => {
Почти верно, но this там есть. Найдешь, какой?)

![изображение](https://user-images.githubusercontent.com/31134795/218840043-7cadb44e-65e8-4a97-a36b-2f7704ec3ac4.png)

2023-02-14 20:07 UTC, vvinokurshin commented on source/anagram.js
> +const anagram = (words) => {
Значение this в стрелочных функциях наследуется от родительской внешней функции

2023-02-14 20:59 UTC, DPeshkoff approved these changes

2023-02-14 20:59 UTC, closed without merging