DZ#0
frontend-park-mail-ru/homework_2023_1 pull request #2
Opened 2023-02-07 21:09 UTC by WhoIsYgim

Ларкин Егор WEB-21

2023-02-08 20:30 UTC, AntonElagin requested changes
Привет, добро пожаловать на курс фронтенда. Я буду проверять твое дз0.

Получилось неплохое решение, вижу, что есть понимания основ языка, но код можно еще слегка улучшить:

- [ ] Давай добавим JsDoc. (См. подробнее в ревью)
- [ ] Давай исправим недостатки в коде. (См. ревью)
- [ ] Давай приведем код в порядок. Нужно стараться оформлять код в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для этих целей можно использовать [eslint](https://eslint.org/)

PS Если будут какие-то вопросы, пиши тут или мне в телегу [@Anton_ELagin](https://t.me/Anton_Elagin)

2023-02-08 20:30 UTC, AntonElagin commented on source/chess.js
> +const chess = dim => {
Давай добавим к твоему коду документацию. Для этого идеально подойдет JsDoc.

Ссылочки:
https://jsdoc.app/

2023-02-08 20:30 UTC, AntonElagin commented on source/chess.js
> +    if (dim < 2) return null;
а что тут будет, если ```dim``` число?

2023-02-08 20:30 UTC, AntonElagin commented on source/chess.js
> +    let row_1 = '* '.repeat(Math.floor(dim/2));
1) В js принято использовать camelCase.
2) ```"* "``` для удобства можно унести в константу. И дальше тоже

2023-02-08 20:30 UTC, AntonElagin commented on source/chess.js
> +    if (dim%2 !== 0) {
Тут код повторяется, может сделать для этого отдельную функцию или объединить?

2023-02-08 20:30 UTC, AntonElagin commented on tests/chess.js
> +	QUnit.test('Строковые входные данные', function (assert) {
Стоит добавить тесты на другие типы. 
что будет если передадут число с плавающей точкой?
А если ```Infinity```?

2023-02-08 20:30 UTC, AntonElagin commented on .gitignore
> +.idea
давай уберем все лишние файлы

2023-02-09 09:05 UTC, AntonElagin requested changes
Осталось совсем немного)

2023-02-09 09:05 UTC, AntonElagin commented on source/chess.js
> +    if (dim < 2) return null;
В js чаще всего принято даже однострочный иф писать с кавычками
```
if (booleanValue) {
    // one code string 
}
```

2023-02-09 09:05 UTC, AntonElagin commented on source/chess.js
> +    const normalizeRow = row => (dim%2 !== 0 ? row + row[0] : row) + '\n';
Я бы еще написал так: ```dim % 2 !== 0```. Так читаемость будет чуть лучше. и дальше тоже

2023-02-09 09:05 UTC, AntonElagin commented on source/chess.js
> +    let board = (row1 + row2).repeat(Math.floor(dim/2));
Тут кажется лучше использовать ```const```

2023-02-09 10:37 UTC, AntonElagin commented
А еще предлагаю привести названия пр-а вот в такой вид:

Фамилия Имя - Вариант

2023-02-09 15:39 UTC, AntonElagin requested changes
и еще немного.

внимательно проверь код на style guide

2023-02-09 15:39 UTC, AntonElagin commented on source/chess.js
> +    const normalizeRow = row => (dim % 2 !== 0 ? row + row[0] : row) + '\n';
давай ```'\n'``` тож в константы, а то странно получается, часть строк в константах, часть нет

2023-02-09 15:39 UTC, AntonElagin commented on source/chess.js
> + * @returns {string} A string representing a chess board
тут возвращаемые данные слегка не соответствуют реальности

2023-02-09 15:39 UTC, AntonElagin commented on source/chess.js
> +    let row2 = PATTERN_2.repeat(Math.floor(dim/2));
```dim/2``` выбивается из общего стиля кода. Проверь весь код на соответствие стилю

2023-02-12 11:11 UTC, DPeshkoff commented on source/chess.js
> +'use strict';
Привет!
Классная работа! А можешь, пожалуйста, объяснить в реплае, что же все-таки делает `use strict` и зачем ты его использовал?

2023-02-12 11:23 UTC, WhoIsYgim commented on source/chess.js
> +'use strict';
'use strict' активирует для файла строгий режим выполнения js.
такой режим будет выбрасывать ошибки для некоторых конструкций и заставляет писать более безопасный код. например, нельзя использовать необъявленные переменные.

2023-02-12 11:27 UTC, DPeshkoff approved these changes

2023-02-12 11:27 UTC, closed without merging