anagram
frontend-park-mail-ru/homework_2023_1 pull request #20
Opened 2023-02-08 22:43 UTC by mmikhail2001

2023-02-12 13:03 UTC, Nikita-Boyarskikh requested changes
Привет, добро пожаловать на курс фронтенда!
Меня зовут Никита, я буду проверять твое дз0

Очень здорово, что ты предоставил несколько вариантов решений, да ещё и со сравнением плюсов и минусов обоих вариантов!

Мысли интересные, могу лишь предложить использовать в качестве ключей не объекты с подсчётом символов, а просто строки из отсортированных символов, тогда сравнения будут производится гораздо проще, без прохода по ключам объекта простым равенством + использовать их как ключи в хэш-мапке
Ну и несколько традиционных придирок к стилю кода)
- [ ] стоит изменить стиль именования переменных и файлов на принятый в мире фронтенда camelCase
- [ ] стоит обработать использование функции с неправильными входными данными (например, если на вход придёт `undefined` код не должен крашнуться. Можно, как вариант, бросить исключение), а также написать на это тесты
- [ ] мне кажется, имеет смысл разбить файл с тестами на 2 различных файла, потому что они тестируют отдельные функции, и если одна из них перестанет работать, по текущим тестам сразу не будет понятно, какая из двух сломалась. Тесты можно оставить аналогичные, но раз функции 2 отдельные, то и тесты лучше на них писать отдельно

PS По любым вопросам можешь писать тут или мне в телегу [@Nikita_Boyarskikh](https://t.me/Nikita_Boyarskikh)

2023-02-14 16:13 UTC, mmikhail2001 commented
Здравствуйте, исправил замечания.
- стили файлов и переменных переведены в camelCase
- функция кидает исключение при неверном типе аргументов
- тесты для 2 функций поиска анаграмм разделены на 2 файла
- тест на отсутствие анаграмм и на присутствие единственное группы анаграмм разделены на 2 теста
- все кавычки заменены на одинарные
- для сравнения строк использую String.localeCompare
- побитовое или (|) заменено на || 
- forEach в функции anagramMap для заполнения словаря заменена на reduce
- равенство "==" заменено на равенство с учетом типа "==="
- функция addAnagram преобразована в чистую (входные аргументы не изменяются, работаем с копией, ее и возвращаем)
- try {} catch {} в функции addAnagram заменен на if {} else {}
- трансформация строк в массив символов [...str] заменена с использованием стандартных методов строк

2023-02-15 08:08 UTC, mmikhail2001 commented on source/anagram_sort.js
> +            [...group[0].toLowerCase()].sort().toString()
Сделал

2023-02-15 08:08 UTC, mmikhail2001 commented on source/anagram_sort.js
> +    try {
Сделал

2023-02-15 10:36 UTC, Nikita-Boyarskikh requested changes

2023-02-15 10:36 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +            === newString.toLowerCase().split('').sort().toString())
`.toString()` возвращает строковое представление объекта, например, для массива `['a', 'b', 'c'].toString() === 'a,b,c'`
Мне кажется, правильнее использовать явно собранную строку из массива с помощью метода `join`, а не полагаться на реализацию `toString`
Это сделает код более явным и потом проще будет понять, что имелось ввиду в данном месте
Почти во всех языках есть больше одного способа сделать одно и то же, при выборе между ними стоит полагаться не только на алгоритмическую сложность, но и на семантическую "понятность" кода, чтобы в дальнейшем было проще его поддерживать
Причём, если нет высоких требований по производительности кода, приоритет чаще всего отдают "понятности" кода

2023-02-15 10:36 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +const addAnagram = (groups, newString) => {
Возможно, будет эффективнее хранить группы в словаре (hash map), ключом может являться строка с отсортированными символами
Сейчас ты по сути так и делаешь, но собираешь эту строку (сортируешь символы) для каждой группы каждый раз при добавлении новой строки
А потом можно было бы просто вернуть `Object.values` от этого словаря, получится некое объединение твоих обоих решений в одно
Что скажешь?

2023-02-15 10:36 UTC, Nikita-Boyarskikh commented on source/anagramMap.js
> +        return typeof elem === 'string'
Строки могут быть не только примитивами, но и объектами `new String('abc')`, а `typeof new String('abc') === 'object'`

2023-02-15 10:36 UTC, Nikita-Boyarskikh commented on source/anagramMap.js
> +        return typeof elem === 'string'
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String

2023-02-15 10:36 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +    if (!Array.isArray(strings) || (!strings.every((elem) => {
скобочки вокруг `!strings.every(...)` лишние

2023-02-15 19:35 UTC, mmikhail2001 commented
Здравствуйте, Никита, отправляю отчет по исправлению замечаний второй итерации проверки.
- boolean в jsDoc написан с маленькой буквы
- функция isEqual изменена, теперь она проверяет совпадения имен атрибутов объектов (obj1.hasOwnProperty(key))
- точка с запятой посетила каждую строчку
- массив строк и двумерный массив явно зарегламентирован в jsDoc (Array.<string> и Array.<Array.<string>>)
- vs code был настроен на автоматическое добавление пустой строки в конец файла
- строка на 48 строку anagramMap.js теперь разбивается на символы через split (вместо [...str])
- unique_dicts переименован в соответствие с camelCase
- toString() заменен на join('') в угоду читаемость кода
- функция addAnagram в файле anagramSort.js теперь кэширует отсортированные строки, которые выступают ключами в объекте groups, значениями ключей являются массивы исходных строк, которое позже в вызывающей подпрограмме посредством Object.values(groups) преобразуются в двумерный массив 
- основные функции поиска анаграмм теперь знают о существовании new String("hello") через проверку instanceof String
- убраны скобочки лишние вокруг !strings.every(...) (34 строка anagramSort.js)

2023-02-15 20:21 UTC, Nikita-Boyarskikh requested changes
Круто, спасибо за такую большую проделанную работу!
Насколько я знаю, помимо тебя никто не предлагал больше одного решения)
Осталась финишная прямая: поправить всякие отступы и точки с запятой

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +    const foundGroup = Object.keys(groupsCopy).find(key => key === sortedNewString);
Прелесть использования объекта тут как раз в том, что можно не перебирать все ключи за O(N), а получить напрямую значение по ключу за O(1)

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on tests/anagramMapTest.js
> +		)
Тут потерялась точка с запятой

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on tests/anagramMapTest.js
> +			[ new String('Kk'), new String('KK')],
Тут пробел перед закрывающей скобкой в массиве потерялся и висящая запятая лишняя, потому что везде в остальном коде она не используется

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on tests/anagramMapTest.js
> +		const input = [new String('Aaa'), new String('aaA'), new String('Kk'), new String('Hello'), new String('KK'),];
Лишняя запятая в конце массива

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +        .sort((a, b) => a[0].localeCompare(b[0]))
Тут потерялась точка с запятой

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +        }, {})
Тут потерялась точка с запятой

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +
Тут многовато отступов, обычно принято оставлять один, очень редко, если сильно нужно выделить визуально различные части кода, то два

2023-02-15 20:21 UTC, Nikita-Boyarskikh commented on source/anagramMap.js
> +        .sort((a, b) => a[0].localeCompare(b[0]))
Тут потерялась точка с запятой

2023-02-15 20:34 UTC, mmikhail2001 commented
Исправил замечания. 
- точки с запятой
- поиск ключа в объекте

2023-02-15 20:49 UTC, Nikita-Boyarskikh commented on source/anagramSort.js
> +    groupsCopy[sortedNewString] ??= []
Здорово сделал, стало короче и проще
Но точку с запятой снова потерял)

2023-02-15 21:02 UTC, Nikita-Boyarskikh approved these changes

2023-02-16 10:24 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Круто, что сделал два решения - но по заданию этого не требовалось
Как думаешь, какое лучше?

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-16 10:24 UTC, DPeshkoff commented on source/anagramSort.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-16 12:45 UTC, mmikhail2001 commented on source/anagramSort.js
> +'use strict';
Эта директива из стандарта ES5, которая включает строгий режим. Она нужна для того, чтобы программисты писали на современном js с использованием безопасных функций, и чтобы любая ошибка не была проигнорирована. В старых браузерах этот режим не поддерживался, и ошибка в коде могла вызвать неправильную работу программы, о которой программисты не были оповещены. В этом режиме запрещены многие функции, потенциально опасные конструкции языка. Например, нельзя присваивать значение в неопределённую переменную, нельзя параметры функции называть одним именем, eval не может создавать переменные и тд. В моей работе она была использована по вышеназванным причинам, безопасный код, современный js и явное уведомление об ошибках.

2023-02-16 12:58 UTC, mmikhail2001 commented
В решении с мапой (первый способ) все операции выполняются за линию: обход строки и составление словаря символов строки, сравнение объектов словарей строк для нахождения представителя группы анаграмм, поиск в результирующем двумерном массиве представителя группы анаграмм. В другом решении представителем группы анаграмм выступает отсортированная строка. Посредством кэширования мы минимизируем количество сортировок, однако все же это сортировка, которая выполняется в лучшем случае за nlogn, а значит если длина строки стремиться к бесконечности первый способ однозначно возьмёт верх. Но второй способ более лаконичный, легкочитаемый и не требует много последовательных поисков. Возможно у первого способа константа в сложности будет большая, в связи с чем решение через сортировки будет выигрышным. Думаю, что при средних размерах строк да и в целом для обычных пользовательских задач я бы выбрал способ с сортировкой.

2023-02-16 19:30 UTC, closed without merging