Зеленко Даниил, вариант 19
frontend-park-mail-ru/homework_2023_1 pull request #21
Opened 2023-02-08 22:54 UTC by Zela2520

2023-02-12 12:06 UTC, Shureks-den commented
Привет, поздравляю с поступлением на второй семестр, самое сложное только впереди :)
Я буду проверять твое дз, если будут вопросы или нужно будет глянуть еще раз - можешь писать сюда https://t.me/alexklonov

2023-02-12 12:17 UTC, Shureks-den requested changes

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +'use strict';
Первый теоретический вопрос - для чего эта строка, изменится ли что-то если ее убрать?

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +const TYPE_ERROR = 'invalid arguments';
Не используешь константу кажется

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +], [ 'id', 'prop1', 'name' ]))
Забыл убрать лог

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +
Отступов многовато

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +        debugger
Забыл убрать деббагер

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +const sorting = (objects, properties) => {
Какие еще способы заданий функций ты знаешь, в чем их различия

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +    }
Ты тут используешь == для сравнения, в js принято использовать ===, прочитай про это оператор и расскажи почему так? Еще я бы предложил инвертировать условие через ! и тогда можно будет написать что то типо 
`if (условие) return` в одну строчку без скобок

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +    return objects?.sort((a,b) => {
Круто что используешь методы массивов, но что значит ?. для чего он тут(теор вопрос). И точно ли он тут нужен, у нас же в начале есть проверка isArray и length (не теор вопрос)

2023-02-12 12:17 UTC, Shureks-den commented on source/sorting.js
> +        return 0
Давай это заменим это на forEach и тернарный оператор (condition) ? :

2023-02-12 12:17 UTC, Shureks-den commented on tests/sorting.js
>  });
Добавь кейс с невалидными входными данными

2023-02-12 17:44 UTC, Zela2520 commented on source/sorting.js
> +'use strict';
Если с use strict работает, то вряд ли что-то изменится если уберу его )
Условно, интерпретатор в строгом режиме выбросил бы ошибку, если обратился бы к переменной без её объявления.

****Google*****
Строгий режим делает следующее:
Выбрасывает ошибки, когда в коде используются некоторые небезопасные конструкции.
Выключает функции языка, которые запутывают код и потому не должны использоваться.
Предотвращает использование слов, которые могут быть использованы в качестве ключевых в будущем.

2023-02-12 17:44 UTC, Zela2520 commented on source/sorting.js
> +const TYPE_ERROR = 'invalid arguments';
+

2023-02-12 17:44 UTC, Zela2520 commented on source/sorting.js
> +], [ 'id', 'prop1', 'name' ]))
+

2023-02-12 17:44 UTC, Zela2520 commented on source/sorting.js
> +
+

2023-02-12 17:44 UTC, Zela2520 commented on source/sorting.js
> +        debugger
+

2023-02-12 17:44 UTC, Zela2520 commented on source/sorting.js
> +const sorting = (objects, properties) => {
function declaration, function expression, стрелочные функции (по сути являются сокращением function expresion)
 Function Declaration: функция объявляется отдельной конструкцией «function…» в основном потоке кода.
 Function Expression: функция, созданная внутри другого выражения или синтаксической конструкции.
 
Function Expression создаётся, когда выполнение доходит до него, и затем уже может использоваться.
После того, как поток выполнения достигнет правой части выражения присваивания let sum = function… – с этого момента, функция считается созданной и может быть использована (присвоена переменной, вызвана и т.д. ).
С Function Declaration всё иначе.
Function Declaration может быть вызвана раньше, чем она объявлена.

Другими словами, когда движок JavaScript готовится выполнять скрипт или блок кода, прежде всего он ищет в нём Function Declaration и создаёт все такие функции. Можно считать этот процесс «стадией инициализации».

И только после того, как все объявления Function Declaration будут обработаны, продолжится выполнение.
В результате функции, созданные как Function Declaration, могут быть вызваны раньше своих определений.

2023-02-12 17:45 UTC, Zela2520 commented on source/sorting.js
> +    return objects?.sort((a,b) => {
1) Опциональная цепочка, проверка на undefined, null. Опциональная цепочка ?. останавливает вычисление и возвращает undefined, если значение перед ?. равно undefined или null
2) Да, тут нет необходимости её использовать.

2023-02-12 17:46 UTC, Zela2520 commented on source/sorting.js
> +    }
Теор. часть: Оператор строгого равенства === проверяет равенство без приведения типов.
Другими словами, если a и b имеют разные типы, то проверка a === b немедленно возвращает false без попытки их преобразования.

Почему так заиспользовал ? Array.prototype.length возвращает unsigned int, а перед тем как дойти до второго равенства у меня есть проверка на isArray, то есть undefined или null быть не может, поэтому так заиспользовал, но наверное лучше использовать ===

2023-02-12 18:44 UTC, Zela2520 commented on source/sorting.js
> +        return 0
У меня тут фишка в том что я return-ом выхожу из цикла, если будет forEach, то такого сделать не смогу. Если ставлю forEach, то сортировка всегда будет только по последнему полю.

С тернарным оператором тоже тут тяжело, поскольку у меня устойчивая сортировка по нескольким полям, то есть когда случай : 1 рассматривается в него не должен попадать случай с нулем - он должен отдельно быть рассмотрен.

2023-02-12 21:03 UTC, Zela2520 commented on tests/sorting.js
>  });
Невалидным сделал кейс, когда у массива, которые необходимо отсортировать все объекты пустые.

2023-02-13 06:04 UTC, Shureks-den requested changes

2023-02-13 06:04 UTC, Shureks-den commented on source/sorting.js
> +        }
Давай тогда заменим эту конструкцию на for (const key in obj)

2023-02-13 11:49 UTC, Zela2520 commented on source/sorting.js
> +        }
+

2023-02-13 11:51 UTC, Zela2520 commented on source/sorting.js
> +        if(JSON.stringify(value) ===  JSON.stringify({})) {
+

2023-02-13 12:00 UTC, Shureks-den requested changes

2023-02-13 12:00 UTC, Shureks-den commented on source/sorting.js
> +}
Слушай, а не можем всю эту функцию заменить на `objects.every(o => Object.keys(o).length)`
Кажется что это тоже подойдет, и решение будет в одну строчку

2023-02-13 12:00 UTC, Shureks-den commented on source/sorting.js
> + * @returns {(Array.<Object>|string)} - отсортированный массив либо сообщение об ошибке
Не добавил throws, еще если оставляешь вторую функу, то для нее тоже надо добавить похожую штуку

2023-02-13 12:17 UTC, Zela2520 commented on source/sorting.js
> +}
+

2023-02-13 12:17 UTC, Zela2520 commented on source/sorting.js
> + * @returns {(Array.<Object>|string)} - отсортированный массив либо сообщение об ошибке
+

2023-02-13 12:22 UTC, Shureks-den requested changes

2023-02-13 12:22 UTC, Shureks-den commented on source/sorting.js
> +    if (objects.every(o => Object.keys(o).length() === 0)) {
length это поле, а не метод, и давай сократим чуть чуть `(!objects.every(o => Object.keys(o).length))`

2023-02-13 12:28 UTC, Zela2520 commented on source/sorting.js
> +    if (objects.every(o => Object.keys(o).length() === 0)) {
+

2023-02-13 12:44 UTC, Shureks-den approved these changes

2023-02-13 13:11 UTC, Shureks-den approved these changes

2023-02-13 13:34 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр! 

Хорошее решение, но есть парочка вопросов к нему)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 13:34 UTC, DPeshkoff commented on source/sorting.js
> +    if (!properties?.length) return objects;
Предлагаю разнести по новым строчкам, чтобы стало читаемее)

2023-02-13 13:34 UTC, DPeshkoff commented on source/sorting.js
> +        return new Error('Invalid data. Array consists of empty objects');
Кажется, просится вот [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-02-13 13:34 UTC, DPeshkoff commented on source/sorting.js
> +const sorting = (objects, properties) => {
А что, если на входе будут некорректные данные? Давай проверим, являются ли они объектами (и покроем тестами)

2023-02-13 18:47 UTC, Zela2520 commented on source/sorting.js
> +    if (!properties?.length) return objects;
+

2023-02-13 18:47 UTC, Zela2520 commented on index.html
> +</html>
не оч понял

2023-02-13 18:57 UTC, Zela2520 commented on source/sorting.js
> +        return new Error('Invalid data. Array consists of empty objects');
+

2023-02-13 19:10 UTC, Zela2520 commented on source/sorting.js
> +const sorting = (objects, properties) => {
+

2023-02-13 19:35 UTC, DPeshkoff approved these changes

2023-02-13 19:36 UTC, closed without merging