Gevork Gabrielyan WEB-21
frontend-park-mail-ru/homework_2023_1 pull request #22
Opened 2023-02-08 22:55 UTC by Gev0rg

Здравствуйте, меня зовут Геворк, рад познакомиться ;)

2023-02-10 17:31 UTC, Shureks-den commented
Привет, поздравляю с переходом на второй семестр! Меня зовут Саша, я буду проверять твое дз, если будут вопросы - пиши в телегу https://t.me/alexklonov

2023-02-10 17:41 UTC, Shureks-den requested changes

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +'use strict';
Начнем с теоретического вопроса - для чего эта строчка и что изменится если ее не будет

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +const massiveFromString = str => str.split(' ').map(c => parseFloat(c)).filter(c => !isNaN(c));
Как называется способ, которым ты инициализируешь функцию, какие еще есть способы и в чем их различия?

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +const minmax = str => {
У тебя здесь нет никаких проверок на невалидные данные, что будет если str === null или undefined

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +const minmax = str => {
Так же стоит добавить и тесты для этого

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +const massiveFromString = str => str.split(' ').map(c => parseFloat(c)).filter(c => !isNaN(c));
Так же вопрос, что делает функция isNaN и что вообще такое NaN

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +}
Здесь можно было бы написать все в одну строку - не писать return и {}. Расскажи почему это возможно? (надеюсь тут услышать про особенности стрелочных функций и немного про тернарный оператор

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +const minmax = str => {
Изменяешь ли исходные данные или нет и почему?

2023-02-10 17:41 UTC, Shureks-den commented on source/minmax.js
> +const minmax = str => {
Также нет JSDoc, вроде бы про это должно было быть написано, даже если нет, то давай все равно добавим(на обе функции)

2023-02-11 16:33 UTC, Shureks-den commented on source/minmax.js
> +const minmax = str => {
Давай добавим проверку типов

2023-02-12 19:03 UTC, Gev0rg commented on source/minmax.js
> +'use strict';
use strict - это строгий режим, при котором работают новые возможности языка, перекрывающие некоторые более старые. Если убрать, то для поддержки существующего (ещё до ES5) кода будут работать старые решения. Главной особенностью режима является то, что мы можем использовать только ограниченный синтаксис и тем самым не допускать мелких ошибок.

2023-02-12 19:19 UTC, Gev0rg commented on source/minmax.js
> +const massiveFromString = str => str.split(' ').map(c => parseFloat(c)).filter(c => !isNaN(c));
Данный способ называется arrow function, есть еще function declaration и function expression.
function declaration - привычное нам создание функции function foo() {...}
function expression - создание функции через присваивание let func = function() {...}, то есть это функция созданная внутри другого выражение, и ее создание происходит тогда, когда выполнение кода доходит до этого выражения
arrow function - по сути сокращенная версия function expression, может как быть с фигурными скомками, так и без. У неё есть несколько особенностей: она не имеет this, arguments, super и не может быть вызвана с new (что в общем то очевидно, раз нет this)

2023-02-12 19:34 UTC, Gev0rg commented on source/minmax.js
> +const massiveFromString = str => str.split(' ').map(c => parseFloat(c)).filter(c => !isNaN(c));
Она проверяет на то, является ли переменная нечисловым значчением (NaN). А сам NaN - это такое свойсво, означающее не число (Not a number)

2023-02-12 19:43 UTC, Gev0rg commented on source/minmax.js
> +const minmax = str => {
Не изменяю, потому что все используемые методы (split, map, filter) создают новый массив и работают уже с ним.

2023-02-13 15:18 UTC, Gev0rg commented on source/minmax.js
> +}
Да, знаю, просто я игрался много внутри этой функции, тогда были необходимы скобки, потом в конце просто забыл упростить. Это возможно, потому что иногда нам нужно написать более сложную функцию, содержащую несколько инструкций, для этого нужно заключить тело функции в {} и для возврата значения использовать return. Теперь про тернарный оператор. В первую очередь он так называется, потому что единственный в своем роде оператор, который имеет три аргумента. Он необходим для того, чтобы упростить "условие" и не писать if ... else... Еще прикольной особенностью этого оператора является то, что можно использовать несколько "?" вместо if ... else if ... else if ...

2023-02-13 15:41 UTC, Gev0rg commented on source/minmax.js
> +const minmax = str => {
Добавил проверки и соответсвующие тесты, а также JSDoc

2023-02-13 19:07 UTC, Shureks-den requested changes

2023-02-13 19:07 UTC, Shureks-den commented on source/minmax.js
> +
Давай поправим отступы, чтобы чуть удобнее было читать: убери пробелы в конце, чтобы последняя строчка была пустой и давай сделаем отступ после `str => `

2023-02-14 08:05 UTC, Shureks-den requested changes

2023-02-14 08:05 UTC, Shureks-den commented on source/minmax.js
> +
Давай тут уберем отступы строчки

2023-02-14 08:05 UTC, Shureks-den commented on tests/minmax.js
> +		assert.throws( function () { minmax(false); } );
И заменим на стрелочные функции `throws(() => minmax(123))`

2023-02-14 08:09 UTC, Gev0rg commented on source/minmax.js
> +
готово

2023-02-14 08:09 UTC, Gev0rg commented on tests/minmax.js
> +		assert.throws( function () { minmax(false); } );
готово

2023-02-14 08:10 UTC, Shureks-den approved these changes

2023-02-14 15:01 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-14 15:01 UTC, DPeshkoff commented on source/minmax.js
> +        if (typeof str !== 'string') {
Кажется, проверка не полная)

![изображение](https://user-images.githubusercontent.com/31134795/218775485-4f6e072f-12f1-4e52-8f40-1b6f23fb9206.png)

2023-02-14 17:28 UTC, Gev0rg commented on source/minmax.js
> +        if (typeof str !== 'string') {
поправил и добавил соответсвующий тест

2023-02-14 19:41 UTC, closed without merging