HW-1
frontend-park-mail-ru/homework_2023_1 pull request #23
Opened 2023-02-08 23:03 UTC by marcussss1

Литвак Данила

2023-02-12 11:43 UTC, Nikita-Boyarskikh requested changes
Привет, добро пожаловать на курс фронтенда!
Меня зовут Никита, я буду проверять твое дз0

Здорово, что ты изучил встроенные возможности языка, очень метко использовал метод `flat`. Если бы это было не учебное ДЗ, а код для продакшена, это был бы наилучший вариант. А так как цель этого ДЗ, научиться писать на JS, давай представим, что у массива нет метода `flat` и реализуем аналогичный своими силами. Все остальные средства языка и методы доступны

Ещё у меня есть несколько небольших замечаний по оформлению кода, сразу их тебе тут напишу, чтобы ты мог всё вместе поправить:
- [ ] было бы неплохо написать документацию к функции, чтобы другие разработчикам было проще понимать, что делает функция, какие аргументы принимает, какой тип возвращает. Бонусом idea тоже сможет подсказвать тип данных при использовании задокументированной функции. Для этого можно использовать общепринятый инструмент - [jsDoc](https://jsdoc.app/about-getting-started.html)
- [ ] стоит обработать использование функции с неправильными входными данными (например, если на вход придёт `undefined` код не должен крашнуться. Можно, как вариант, бросить исключение), а также написать на это тесты
- [ ] у тебя idea заменила табы в уже существующем коде на пробелы, так что выглядит, будто ты изменил почти все строчки в файле с тестами. Понимаю, что тема tab vs space для горизонтальных отступов в коде холиварная, и я сам больше за пробелы, но со своим уставом в чужой монастырь не ходят, так что предлагаю всё же настроить idea, чтобы она использовала табы для отступов (https://www.jetbrains.com/help/webstorm/settings-code-style-javascript.html)
- [ ] стоит убрать файлы настроек idea из проекта, они не несут полезной нагрузки для проекта, поэтому коммитить их не стоит. Чтобы лишние файлы не попадали в репозиторий, можно воспользоваться [.gitignore файлом](https://git-scm.com/docs/gitignore)

PS По любым вопросам можешь писать тут или мне в телегу [@Nikita_Boyarskikh](https://t.me/Nikita_Boyarskikh)

2023-02-13 09:37 UTC, Nikita-Boyarskikh requested changes
Спасибо за исправления, осталось немного поправить jsdoc и настройки IDE

2023-02-13 09:37 UTC, Nikita-Boyarskikh commented on source/plain.js
> + * @function
Кажется, тут это лишний тег, хуже он не делает, он просто лишний, в принципе, можно не убирать)

Он нужен в том случае, когда парсер сам не может догадаться, что в переменной хранится функция
Например, что-то типа такого:
```js
const myFunction = getMyFunction();
```

А когда у нас объявление функции (неважно, через присвоение и стрелочную функцию или через ключевое слово `function`), парсер сам определяет переменную как функцию

2023-02-13 09:37 UTC, Nikita-Boyarskikh commented on source/plain.js
> + * @param {Array} ans - Общий массив
Тег `@param` задаёт аргументы функции, эта функция не принимает `ans` аргументом, поэтому этот тег нужно убрать

Дока: https://jsdoc.app/tags-param.html

2023-02-13 09:37 UTC, Nikita-Boyarskikh commented on source/plain.js
> + * Напишите функцию plain, которая будет принимать на вход массив массивов и создавать из них один общий массив. Массивы могут быть любой вложенности
Лучше в документации к функции описывать именно то, что делает функция, а не почему она была написана
Представь, что ты пишешь библиотеку, которой должны будут пользоваться другие разработчики. А в JsDoc пишется документация к библиотечным функциям. По этой документации должно быть понятно, зачем нужна эта функция и как ей пользоваться

2023-02-13 09:37 UTC, Nikita-Boyarskikh commented on source/plain.js
> +    while (arr.length) {
Элегантно 👍

2023-02-13 09:37 UTC, Nikita-Boyarskikh commented on tests/plain.js
> +});
Добавь перенос строки в конце файла, плиз
Общепринято в айти последним символом в файле оставлять перенос строки
Как минимум, так проще смотреть diff, если добавляются новые строки в конец файла

2023-02-13 09:37 UTC, Nikita-Boyarskikh commented on tests/plain.js
> +});
Тут последняя настройка: https://www.jetbrains.com/help/webstorm/settings-editor-general.html

2023-02-13 11:22 UTC, Nikita-Boyarskikh commented
Лучше не использовать `push --force` при работе с репозиторием
Форс пуши перезаписывают историю коммитов, теряется хронология
К тому же, как только ты начинаешь работать не один над кодом (или даже один, но с двух устройств), форс пуши порождают огромное количество конфликтов
В общем, если есть возможность не использовать форс пуши, рекомендую их не использовать)

2023-02-13 11:27 UTC, Nikita-Boyarskikh approved these changes

2023-02-13 12:23 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр! 

Есть пара вопросов по ДЗ

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 12:23 UTC, DPeshkoff commented on source/plain.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-13 12:23 UTC, DPeshkoff commented on source/plain.js
> +const plain = arr => {
Лучше оборачивать аргументы в скобки - чтобы было проще добавлять новые)

2023-02-13 12:23 UTC, DPeshkoff commented on source/plain.js
> +		throw new Error('Incorrect data');
Лучше использовать [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-02-13 16:42 UTC, marcussss1 commented on source/plain.js
> +'use strict';
'use strict' - директива js, включающая строгий режим в текущем скрипте или какой-либо функции, в моем случае директива работает во всем скрипте т.к. объявлена вначале файла. В строгом режиме интерпретатор будет явно выбрасывать ошибки на действия, которые ранее пропускал, например, если обратиться к переменной без её объявления. Эта директива позволяет предотвращать «тихие» ошибки и повышать безопасность приложений.

2023-02-13 18:08 UTC, DPeshkoff approved these changes

2023-02-13 18:09 UTC, closed without merging