Авельев Максим ДЗ 0, вариант 2
frontend-park-mail-ru/homework_2023_1 pull request #24
Opened 2023-02-09 00:09 UTC by CyTb-On-Fire

2023-02-12 12:20 UTC, Shureks-den commented
Привет! Добро пожаловать на самый интересный курс в технопарке - курс по фронтенду :)
Меня зовут Саша, я буду проверять твое дз, если будут вопросы - пиши в телегу https://t.me/alexklonov

2023-02-12 12:27 UTC, Shureks-den requested changes

2023-02-12 12:27 UTC, Shureks-den commented on source/euclid.js
> +"use strict";
Начнем с традиционного вопроса - для чего эта строка, на что она влияет? Измениться ли в твоем случае что-то?

2023-02-12 12:27 UTC, Shureks-den commented on source/euclid.js
> +
Нужно добавить jsDoc каждой функции которую используешь

2023-02-12 12:27 UTC, Shureks-den commented on source/euclid.js
> +function euclid(...nums) {
Какие еще способы инициализации функции ты знаешь? В чем их различия?

2023-02-12 12:27 UTC, Shureks-den commented on source/euclid.js
> +    }
Давай заменим это все парой строчек с помощью метода some или any у массива.

2023-02-12 12:27 UTC, Shureks-den commented on source/euclid.js
> +    return pair_GCD;
Кажется это все можно заменить методом reduce, он позволяет аккумулировать значение в цикле.

2023-02-12 12:27 UTC, Shureks-den commented on source/euclid.js
> +    let CountGCD = function(first, second){
Значения которые ты не изменяешь следует делать константными

2023-02-12 12:27 UTC, Shureks-den commented on tests/euclid.js
> +	QUnit.test('Функция должна возвращать null, если были переданы не натуральные числа', function (assert){
Добавь тест на отрицательные еще

2023-02-12 12:27 UTC, Shureks-den commented on source/euclid.js
> +    return pair_GCD;
Прочитай про стрелочные функции, они очень полезные и использовать их в методах по типу forEach, reduce и тд  мастхеф

2023-02-13 16:48 UTC, CyTb-On-Fire commented on source/euclid.js
> +"use strict";
Включает строгий режим, т.е. позволяет использовать новые механизмы языка и усовершенствованные старые. 
Для этого файла если ее убрать - отключится строгий режим, так как в нем не используются классы и модули, которые включают его по умолчанию.

2023-02-13 22:40 UTC, CyTb-On-Fire commented on source/euclid.js
> +function euclid(...nums) {
Еще можно использовать функциональные выражения и стрелочные функции. Они отличаются тем, что функциональные выражения можно создавать внутри других конструкций.

2023-02-14 17:36 UTC, Shureks-den requested changes

2023-02-14 17:36 UTC, Shureks-den commented on source/euclid.js
> + * @param  nums - Массив натуральных чисел
Укажи тип number

2023-02-14 17:36 UTC, Shureks-den commented on source/euclid.js
> +function euclid(...nums) {
Давай тут заюзаем function expression

2023-02-14 17:36 UTC, Shureks-den commented on source/euclid.js
> +    }
Кажется что это проверка не нужна, проверь с одним числом

2023-02-14 17:36 UTC, Shureks-den commented on source/euclid.js
> +    }
А вот проверка пустого массива нужна, иначе в ошибку сваливаемся

2023-02-14 17:36 UTC, Shureks-den commented on source/euclid.js
> +    };
Я предлагаю прямо скопировать с { и вставить в стрелочную функцию в reduce, ну или иначе давай ее тоже стрелочной просто сделаем

2023-02-14 17:36 UTC, Shureks-den commented on source/euclid.js
> +        let temp;
Давай делать константной внутри цикла

2023-02-14 17:36 UTC, Shureks-den commented on source/euclid.js
> +    const CountGCD = function(first, second){
Добавь везде отступ перед {

2023-02-15 05:41 UTC, Shureks-den requested changes

2023-02-15 05:41 UTC, Shureks-den commented on source/euclid.js
> +    if (nums.some(number => !Number.isInteger(number) || number <= 0)) {
Два условия можно объединить через логическое 'или' если первое условие выполнится, то второе уже не будет. То есть будет что-то вроде `!nums.length || ... {return null}`

2023-02-15 05:41 UTC, Shureks-den commented on source/euclid.js
> +    return nums.reduce((pair_GCD, currentValue) => {
Давай переименуем pair_GCD, название какое то не джаваскриптовское :), как минимум, давай camelCase заюзаем

2023-02-15 05:41 UTC, Shureks-den commented on source/euclid.js
> +        while (lowest !== 0) {
В js 0 тайпкастится к нулю, так что можно написать while (lowest)

2023-02-15 07:13 UTC, Shureks-den requested changes

2023-02-15 07:13 UTC, Shureks-den commented on source/euclid.js
> +const euclid = function(...nums) {
Давай тут на стрелочную еще заменим, этот синтаксис по-современее будет

2023-02-15 10:34 UTC, DPeshkoff approved these changes

2023-02-15 10:34 UTC, closed without merging