Stukalov Ivan done hw
frontend-park-mail-ru/homework_2023_1 pull request #26
Opened 2023-02-09 06:06 UTC by IvanStukalov

2023-02-09 08:42 UTC, IvanStukalov commented
Стукалов Иван, вариант 19

2023-02-13 11:38 UTC, Nikita-Boyarskikh commented on source/sorting.js
> + * @param {Array} arr - Array you want to sort
Хорошо бы более детально тип расписать, например, указать, что это не "какой-то массив", а "массив объектов"

2023-02-13 12:39 UTC, Nikita-Boyarskikh requested changes
Привет, добро пожаловать на курс фронтенда!
Меня зовут Никита, я буду проверять твое дз0

Код в целом неплохо оформлен, интересные тест-кейсы придуманы
Я написал несколько замечаний по коду + давай обработаем негативные сценарии использования функции и сразу тесты на них напишем (например, если её вызвать с одним массивом вместо двух или вообще без аргументов, или передать туда не массивы, а, например, числа, код упадёт, а должен как-нибудь справиться с этим, вернуть дефолт какой-нибудь или бросить исключение)

PS По любым вопросам можешь писать тут или мне в телегу [@Nikita_Boyarskikh](https://t.me/Nikita_Boyarskikh)

2023-02-13 12:40 UTC, Nikita-Boyarskikh commented
А, и ещё небольшая просьба: добавь номер варианта в название пулрика, так проверять удобнее будет)

2023-02-13 17:39 UTC, IvanStukalov commented
по поводу function expression / function declaration / стрелочных функций немного почитал, пришел к выводу, что лучше использовать function declaration, так как обычно при использовании function expression функции можно применять только после их объявления (а function declaration можно вызывать и до объявления), а стрелочные функции не имеют в параметрах массива args и необходимо использовать деструктуризацию ...args. Плюс в моей функции следует иметь явный return (который иногда опускают в коротких стрелочных функциях)

В целом, наверное в данном случае можно было всеми тремя способами сделать, но в каких то других условиях function declaration для данной функции будет лучше.

2023-02-13 17:46 UTC, IvanStukalov commented
остальное подправил (и справил на function declaration)

2023-02-14 07:15 UTC, Nikita-Boyarskikh commented on source/sorting.js
> + * @param {Array} arr - Array you want to sort
Я имел ввиду не в комментарии написать это, а тип более детальный указать
JsDoc позволяет указывать тип массива, поищи в документации, как это сделать
Начать можно отсюда: https://jsdoc.app/tags-param.html

2023-02-14 07:21 UTC, Nikita-Boyarskikh requested changes

2023-02-14 07:21 UTC, Nikita-Boyarskikh commented on source/sorting.js
> +        let comparator = 0;
Можно упростить и избавиться от этой переменной
Если присмотреться, то она изменяется только перед возвратом, а остальное время остаётся равной 0
Заодно, можно избавиться от лишнего if, станет поменьше кода = проще поддерживать, проще исправлять)

2023-02-14 07:21 UTC, Nikita-Boyarskikh commented on source/sorting.js
> +        for (let p = 0; p < params.length; ++p) {
Смотри, тут ты перебираешь индексы массива, но по дальше везде сам индекс тебе не нужен
JS позволяет перебрать не индексы, а сами элементы, попробуй использовать `for ... of` цикл

2023-02-15 07:41 UTC, Nikita-Boyarskikh approved these changes

2023-02-15 08:01 UTC, Nikita-Boyarskikh requested changes

2023-02-15 08:01 UTC, Nikita-Boyarskikh commented on source/sorting.js
> + * @param {Array<Object.<string, any>} arr - Array of objects you want to sort
Ошибочку допустил: забыл закрывающую угловую скобку
Прежде чем пушить код, имеет смысл его проверить: прогнать тесты, линтеры, генерацию документации, а в идеале, это всё автоматизировать с помощью CI
Сейчас этого точно не нужно делать, но когда вы будете над проектом работать, без CI вам будет трудно, так что поизучать можно уже сейчас)
А как сгенерировать документацию, можно тут почитать: https://github.com/jsdoc/jsdoc
Сейчас генерация падает из-за синтаксической ошибки

2023-02-15 08:01 UTC, Nikita-Boyarskikh commented on source/sorting.js
> + * @param {Array<Object.<string, any>} arr - Array of objects you want to sort
И, кстати, jsdoc кушает такое, но лучше писать канонично - не `Array<...>`, а `Array.<...>` или `...[]`

2023-02-15 08:09 UTC, Nikita-Boyarskikh commented on source/sorting.js
> + * @param {Array<Object.<string, any>} arr - Array of objects you want to sort
Ну и `any` тогда для однообразия лучше заменить на `?` или `*`
Дело в том, что jsdoc поддерживает несколько видов типизации: [typescript](https://www.typescriptlang.org/static/TypeScript%20Types-ae199d69aeecf7d4a2704a528d0fd3f9.png) и [google closure](https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System)
Так что давай придерживать либо одного вида типизации, либо другого, не смешивая

2023-02-15 10:15 UTC, Nikita-Boyarskikh requested changes

2023-02-15 10:15 UTC, Nikita-Boyarskikh commented on .gitignore
> +source/out/
Добавь переносы строки в концы файлов, плиз
Общепринято в айти последним символом в файле оставлять перенос строки
Как минимум, так проще смотреть diff, если добавляются новые строки в конец файла
Проще всего настроить свой редактор, чтобы он автоматически добавлял перенос, если него нет, чтобы потом с этим не возникало проблем при работе над проектом

2023-02-15 11:31 UTC, Nikita-Boyarskikh requested changes

2023-02-15 11:31 UTC, Nikita-Boyarskikh commented on source/sorting.js
> +}
сюда тоже

2023-02-15 14:00 UTC, Nikita-Boyarskikh commented on source/sorting.js
> +"use strict";
Нужно как везде на одинарные кавычки поменять

2023-02-15 17:20 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-15 17:20 UTC, DPeshkoff commented on source/sorting.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-15 17:20 UTC, DPeshkoff commented on source/sorting.js
> +function sorting(arr, params) {
А какие еще бывают функции в языке?

2023-02-15 17:20 UTC, DPeshkoff commented on source/sorting.js
> +	arr.sort((a, b) => {
А что будет, если на вход придет что-то некорректное? Не массив? 

Давай проверим + добавим тесты на это

2023-02-15 17:20 UTC, DPeshkoff commented on source/sorting.js
> +		}
У массивов есть свои методы, давай воспользуемся ими)

2023-02-15 17:55 UTC, IvanStukalov commented on source/sorting.js
> +'use strict';
use strict - это специальная директива, которая включает "строгий режим". Он позволяет пользоваться более ограниченным синтаксисом, и поэтому не дает допускать даже мелкие ошибки, которые мог пропустить стандартный режим, такие как присваивание неопределенной переменной значения или назначение объекту свойств с одинаковыми именами.

2023-02-15 17:59 UTC, IvanStukalov commented on source/sorting.js
> +function sorting(arr, params) {
у меня используется function declaration, еще есть function expression ( const sorting = function(args) {expressions}; ) и стрелочные функции ( const sorting = (args) => {expressions}; )

2023-02-16 09:32 UTC, DPeshkoff commented on source/sorting.js
> +function sorting(arr, params) {
давай сделаем стрелочные)

Кстати, чем они отличаются от обычных?

2023-02-16 09:34 UTC, DPeshkoff requested changes

2023-02-16 09:34 UTC, DPeshkoff commented on source/sorting.js
> +		for (let p of params) {
а гоу попробуем методы массива заюзать)

2023-02-16 09:34 UTC, DPeshkoff commented on source/sorting.js
> +			if (typeof(a[p]) != typeof(b[p])){
Строгие проверки лучше нестрогих

2023-02-16 09:34 UTC, DPeshkoff commented on tests/sorting.js
> +	QUnit.test('sorting: сортирует массив по численному свойству', function (assert) {
diff в оригинальных тестах не нужен

2023-02-16 11:17 UTC, IvanStukalov commented on source/sorting.js
> +function sorting(arr, params) {
это сокращенная версия function expression
обычные функции могут создавать объекты, так как имеют собственный this (а стрелочные - нет)
у обычных функций результат возвращается только через return, а стрелочные функции могут сами вернуть результат, если содержат только одно выражение

2023-02-16 11:18 UTC, IvanStukalov commented on source/sorting.js
> +		for (let p of params) {
я пробовал) написал в телеге, почему не получилось

2023-02-16 11:28 UTC, IvanStukalov commented on source/sorting.js
> +		for (let p of params) {
как я понял, foreach не может вернуть значение изнутри себя, а у every return работает, как break (если return false) или как continue (если return true)
а мне нужно именно изнутри цикла возрващать значение

2023-02-16 19:31 UTC, DPeshkoff approved these changes

2023-02-16 19:31 UTC, closed without merging