Аюшиев Тимур, 4 вариант
frontend-park-mail-ru/homework_2023_1 pull request #27
Opened 2023-02-09 08:54 UTC by SicParv1sMagna

Функция inverse

2023-02-13 11:07 UTC, inerc commented
Привет, добро пожаловать на курс фронтенда!
Меня зовут Женя, я буду проверять твое дз0

[] Здорово, что у тебя получилось реализовать функцию чтобы прошли тесты. Если бы эта задача была в рабочем порядке код бы ушел в прод. Но Давай самостоятельно реализуем функцию reverse не используя встроенные возможности js (.reverse)

[] Также я бы очень хотел увидеть тесты написанные тобой на эту функцию.
[] Давай сделаем проверку и валидацию входящих данных для фнкции.
Подробнее по коду написать в ревью.

PS По любым вопросам можешь писать тут или мне в телегу [@inerc](https://t.me/inerc)

2023-02-13 11:10 UTC, inerc requested changes

2023-02-13 11:10 UTC, inerc commented on source/inverse.js
> +
Вот тут JsDoc

2023-02-13 11:10 UTC, inerc commented on source/inverse.js
> +const inverse = (array, number) => {
Проверки входящих данных для функции.

2023-02-13 11:10 UTC, inerc commented on source/inverse.js
> +    return array.reverse();
Давай сделаем свой reverse с блэкджеком и ...
![бендер-футурама](https://user-images.githubusercontent.com/15797209/218442500-7bc83c7a-a6c7-42c5-a664-29fb8747a7f1.png)

2023-02-13 19:50 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 19:50 UTC, DPeshkoff commented on index.html
> -
Зачем тут убирать строчку?

2023-02-13 19:50 UTC, DPeshkoff commented on source/inverse.js
> +        throw new Error('First argument must be an array');
Кажется, что [лучше](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-02-13 19:50 UTC, DPeshkoff commented on source/inverse.js
> +    if (typeof pos !== 'number') {
Кажется, проверка не будет полной:

![изображение](https://user-images.githubusercontent.com/31134795/218560126-f9081fc4-dee2-49c4-bf86-a20e5a4e18fd.png)

2023-02-13 19:50 UTC, DPeshkoff commented on source/inverse.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-14 12:46 UTC, SicParv1sMagna commented on source/inverse.js
> +'use strict';
'use strict' это директива , которая используется для включения строгого режима. На все ошибки, которые могут пройти в стандартном режиме, строгий выдаст исключение. В случае возникновения "тихой" ошибки, программа выдаст исключение, а процесс ее выполнения остановится.

2023-02-14 14:46 UTC, DPeshkoff requested changes

2023-02-14 14:46 UTC, DPeshkoff commented on index.html
> -<script src="source/max.js"></script>
Давай оставим оригинальным и без изменений)

2023-02-14 14:46 UTC, DPeshkoff commented on tests/inverse.js
> +		}, 'Функция не принимает пустой массив');
а это не пустой массив

2023-02-14 19:42 UTC, DPeshkoff approved these changes

2023-02-14 19:42 UTC, closed without merging