Опарин Александр, 12 Вариант
frontend-park-mail-ru/homework_2023_1 pull request #29
Opened 2023-02-09 09:59 UTC by AleksandrOparin

2023-02-13 12:55 UTC, AntonElagin requested changes
Привет, приветствую тебя на курсе фронтенда. Я буду проверять твое дз0.

У тебя получилось неплохое решение, но его все равно можно чуточку улучшить

- [ ]  Давай приведем код в порядок. Нужно стараться оформлять код в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для этих целей можно использовать [eslint](https://eslint.org/)
- [ ]  Стоит пробрасывать ошибки для неверных входных данных и в целом обрабатывать все возможные случаи со всеми возможными ошибками

PS Если будут какие-то вопросы, пиши тут или мне в телегу [@Anton_ELagin](https://t.me/Anton_Elagin)

2023-02-13 12:55 UTC, AntonElagin commented on source/minmax.js
> +    const numbers = str.split(' ').filter(Boolean).map(Number).filter((value) => !Number.isNaN(value))
Расскажи, пожалуйста, для каких целей используешь ```filter(Boolean)```?

2023-02-13 12:55 UTC, AntonElagin commented on source/minmax.js
> +const max = numbers => Math.max(...numbers);
Круто, что ты нашел встроенные функции, но давай все-таки реализуем сами функции max и min

2023-02-13 12:55 UTC, AntonElagin commented on source/minmax.js
> + * @returns {Array} Массив, содержащий минимальное и максимальное числа
Кажется, тут можно расписать чуть точнее, мы же возвращаем не просто массив, а скорее даже кортеж из 2 определенных значений.

2023-02-13 12:55 UTC, AntonElagin commented on tests/minmax.js
> +		assert.deepEqual(minmax(null), [ undefined, undefined ]);
вижу тесты на невалидные данные, но точно ли они у тебя проходят?

2023-02-13 12:56 UTC, AntonElagin commented on index.html
> +    <!-- <script src="source/max.js"></script> -->
Давай уберем все лишние изменения кода и комментарии, чтоб в пр-е отображались только нужные изменения

2023-02-13 14:35 UTC, AleksandrOparin commented on source/minmax.js
> +    const numbers = str.split(' ').filter(Boolean).map(Number).filter((value) => !Number.isNaN(value))
filter(Boolean) использовал для того, чтобы обработать случай, когда приходит пустая строка. Так как в этом случае split по пробелу вернёт [ '' ], а map(Number) от этого вернёт [ 0 ], то есть пустая строка преобразуется в 0, что даёт нам в результате непустой массив при пустой входной строке. Таким образом в результате проверки длины массива при возврате, мы бы не попадали в нужную ветку.

2023-02-13 14:36 UTC, AleksandrOparin commented on source/minmax.js
> +    const numbers = str.split(' ').filter(Boolean).map(Number).filter((value) => !Number.isNaN(value))
Но я этот код изменил. Ты посмотрел старую версию. Я убрал filter(Boolean) в следующих коммитах.

2023-02-13 14:37 UTC, AleksandrOparin commented on tests/minmax.js
> +		assert.deepEqual(minmax(null), [ undefined, undefined ]);
Да, тесты проходят. Так как код файла minmax.js тоже был изменён относительно того, который ты прокомментировал.

2023-02-13 14:40 UTC, AleksandrOparin commented on source/minmax.js
> +    const numbers = str.split(' ').filter(Boolean).map(Number).filter((value) => !Number.isNaN(value))
Я проверил. Я сначала изменил код, но потом случайно вернул старый вариант и не заметил.

2023-02-14 07:40 UTC, AntonElagin requested changes
и еще раз обрати внимание на оформление твоего кода. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style).

2023-02-14 07:40 UTC, AntonElagin commented on source/minmax.js
> +  if (isNullOrUndefined(str)) {
Кажется, что нам могут случайно передать и другие типы, а их мы никак не обрабатываем

2023-02-14 07:40 UTC, AntonElagin commented on source/minmax.js
> +    throw new Error('Неверный аргумент: ожидалась строка!');
Как будто больше похоже на [TypeError](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-02-14 07:40 UTC, AntonElagin commented on tests/min.js
> +QUnit.module('Тестируем функцию min', function () {
В данном случае нет смысла отдельно тестировать функцию ```min```, достаточно ее протестировать через```minmax```

2023-02-14 07:40 UTC, AntonElagin commented on source/minmax.js
> +  for (let i = 1; i < numbers.length; i++) {
В js принято использовать [методы массивов](https://learn.javascript.ru/array-methods) для итерации/изменения массивов

2023-02-14 07:40 UTC, AntonElagin commented on source/minmax.js
> +const isNullOrUndefined = value => {
в большинстве style guide-ов принято оборачивать в скобки аргумент функции(даже когда он один). Давай сделаем так же.
Вот доказательство из google-ового гайда: https://google.github.io/styleguide/jsguide.html#features-functions-arrow-functions (см. Tips)

2023-02-14 07:40 UTC, AntonElagin commented on source/minmax.js
> +  return value === null || value === undefined;
Однострочные функции стрелки чаще всего пишут в сокращенном виде, [примеры тут](https://learn.javascript.ru/arrow-functions-basics)

2023-02-14 07:40 UTC, AntonElagin commented on source/minmax.js
> + * @param {Array} numbers - массив чисел
Надо бы уточнить, что за массив мы получаем на вход

2023-02-14 07:40 UTC, AntonElagin commented on tests/minmax.js
> +	QUnit.test('minmax возвращает ошибку при невалидных данных', function (assert) {
Сейчас тесты покрывают только обработанные ошибки, но что будет, если нам передадут ```{}``` или ````123```, например?

2023-02-14 07:40 UTC, AntonElagin commented on index.html
> +</html>
Давай оставим только важный дифф, где действительном менялся/добавлялся код, а все стилистические правки вернем как было

2023-02-14 11:19 UTC, AleksandrOparin commented
Поправил все замечания.

2023-02-14 13:59 UTC, AntonElagin requested changes

2023-02-14 13:59 UTC, AntonElagin commented on index.html
> +</html>
тут что-то осталось

2023-02-14 13:59 UTC, AntonElagin commented on tests/minmax.js
> +		assert.deepEqual(minmax(``), [ undefined, undefined ]);
отдельно тестировать "шаблонные" строки нет смысла, это все те же строки. Правильнее будет использовать "обычные" строки(те обычные кавычки)

2023-02-14 13:59 UTC, AntonElagin commented on tests/minmax.js
> +        assert.throws(
не соответсвует оформлению этого файла

2023-02-14 14:37 UTC, AleksandrOparin commented on tests/minmax.js
> +		assert.deepEqual(minmax(``), [ undefined, undefined ]);
Ты как будто по старому коммиту index.html смотрел. Я вернул начальную структуру (там теперь как и было 2 
1 строчка).

2023-02-14 14:38 UTC, AleksandrOparin commented
Отредактировал замечания.

2023-02-14 14:39 UTC, AleksandrOparin commented on index.html
> +</html>
Вроде, нет. 21 строчка, как и было в начальном репозитории.

2023-02-14 16:14 UTC, AntonElagin commented on index.html
> +</html>
Нужно вернуть пустую строку в конце файла, если верить github-у

2023-02-14 19:47 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-14 19:47 UTC, DPeshkoff commented on index.html
> -<script src="source/max.js"></script>
Пример не нужно было удалять)

2023-02-14 19:47 UTC, DPeshkoff commented on source/max.js
> -const max = numbers => Math.max(...numbers);
Аналогично, давай вернем)

2023-02-14 19:47 UTC, DPeshkoff commented on source/minmax.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-14 19:47 UTC, DPeshkoff commented on source/minmax.js
> +  if (typeof str !== 'string') {
Кажется, проверка не полная:

![изображение](https://user-images.githubusercontent.com/31134795/218842497-1e383aa1-8a62-48af-97e2-b77d23648917.png)

2023-02-14 19:47 UTC, DPeshkoff commented on source/minmax.js
> +  const numbers = str.split(' ').filter(Boolean).map(Number).filter((value) => !Number.isNaN(value));
Круто! А чем отличаются между собой `Number.isNaN()` и `isNaN()` ? Почему выбрал именно первое?

2023-02-14 21:16 UTC, AleksandrOparin commented on index.html
> -<script src="source/max.js"></script>
Изначально я хотел оставить этот файл. Однако получается следующая ситуация. Если существуют два файла с одинаковым именем функции, то они начинают конфликтовать, так как это переопределение и я не могу их подключить сразу оба. Да и к тому же, зачем нужен файл max.js, если есть minmax.js, где описана та же функция. Можно, конечно, удалить описание max из minmax.js и вернуть файл max.js и подключать на странице два скрипта. Но я не думаю, что это того стоит.

2023-02-14 21:17 UTC, AleksandrOparin commented on source/max.js
> -const max = numbers => Math.max(...numbers);
Хорошо, вернём. Тренировался с другим ментором использовать другие методы JS.

2023-02-14 21:18 UTC, AleksandrOparin commented on source/minmax.js
> +'use strict';
Конечно могу. Держи: 'use strict' - строгий режим. Он добавляет в семантику JavaScript некоторые изменения. Без него синтаксические правила не так строги и код может выполняться даже если в нём присутствуют ошибки. Система же не предупредит разработчика об этих ошибках. Строгий режим как раз ужесточает эти правила, выдавая соответствующие исключения.

2023-02-14 21:19 UTC, AleksandrOparin commented on source/minmax.js
> +  if (typeof str !== 'string') {
Согласен, проверка была неполной, добавил дополнительную проверку в этом месте.

2023-02-14 21:25 UTC, AleksandrOparin commented on source/minmax.js
> +  const numbers = str.split(' ').filter(Boolean).map(Number).filter((value) => !Number.isNaN(value));
Вопрос хороший. Основное отличие в том, что `isNaN()` сначала выполняет каст содержимого в число, а потом выполняет проверку, в то время как `Number.isNaN()` ничего не кастит и выполняет проверку над переданным значением. Вот пример:
![image](https://user-images.githubusercontent.com/89871310/218866095-b8df8d44-cde9-4fef-8fc6-13e7b4a7712e.png)
То есть в первом случае функция преобразует сначала строку в число и получает `NaN`, после чего применяется к `NaN` и выдаёт `true`. Во втором случае такого не происходит и проверяется пришедшее значение, а оно не `NaN`, поэтому получаем `false`.

2023-02-15 09:30 UTC, DPeshkoff approved these changes

2023-02-15 09:30 UTC, closed without merging