Variant 5
frontend-park-mail-ru/homework_2023_1 pull request #3
Opened 2023-02-08 12:25 UTC by BazaleevFedor

Базалеев Фёдор

2023-02-08 21:43 UTC, AntonElagin requested changes
Привет, добро пожаловать на курс фронтенда. Я буду проверять твое дз0.

Получилось неплохое решение, вижу, что есть понимания основ языка, но код можно еще слегка улучшить:

- [ ] Давай добавим JsDoc. Он поможет задокументировать твой код. https://jsdoc.app/
- [ ]  Давай исправим недостатки в коде. (См. ревью)
- [ ] Давай приведем код в порядок. Нужно стараться оформлять код в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для этих целей можно использовать [eslint](https://eslint.org/)

PS Если будут какие-то вопросы, пиши тут или мне в телегу [@Anton_ELagin](https://t.me/Anton_Elagin)

2023-02-08 21:43 UTC, AntonElagin commented on source/chess.js
> +    if (!Number(numbers) | numbers < 2 | numbers % 1 > 0) return null;
Какое странное условие,

Почему решил использовать побитовое ИЛИ(```|```), почему не логическое(```||```) ?
Крайне странные выбор остатка для деления, возможно в побитовых операциях оно и имеет смысл(хотя все равно сомневаюсь), но в обычном коде выглядит странно.

2023-02-08 21:43 UTC, AntonElagin commented on source/chess.js
> +    let oddLines = " *".repeat(numbers / 2) + " ".repeat(numbers % 2) + "\n";
Почему тут и выше выбрал именно ```let```? Может ```const``` подойдет лучше?
Может стоит вынести "магические строки " в константы?

2023-02-08 21:43 UTC, AntonElagin commented on tests/chess.js
> +	QUnit.test('Шахматной доски qwerty на qwerty не бывает', function (assert) {
Я бы добавил еще 1-2 тестика на другие типы данных и крайние кейсы.
Что будет если numbers будет ```Infinity```?

2023-02-08 21:43 UTC, AntonElagin commented on source/chess.js
> +const chess = function (numbers) {
Предлагаю использовать функции стрелки, это более современный подход в js.

Подробнее про них:
https://learn.javascript.ru/arrow-functions-basics

2023-02-09 10:56 UTC, AntonElagin requested changes
Уже практически идеально)

Но есть пару моментов по style guide-у.
1) Используешь разные кавычки, нужно привести все к одному виду(Я бы советовал использовать ```'```)
2) Отличается оформление стрелочных функций(Пример: ```(arg1) =>``` и ```arg1 =>```) Нужно писать в едином стиле (мой фаворит вариант 1)

2023-02-09 10:56 UTC, AntonElagin commented on source/chess.js
> +const chess = (numbers) => {
Не хватает описания в JSDoc входных/выходных данных.

Смотри пример 3: https://jsdoc.app/about-getting-started.html

2023-02-09 10:56 UTC, AntonElagin commented on source/chess.js
> +const getEvenLine = numbers => "* ".repeat(numbers / 2) + "*".repeat(numbers % 2) + "\n";
Я бы все еще унес "магические строки " в константы

2023-02-09 10:56 UTC, AntonElagin commented on tests/chess.js
> +		assert.strictEqual(chess('undefined'), null);
Думаю, можно не повторять все тесты на строки для разных данных. Достаточно написать 1 тест и проверить в нем несколько кейсов на разные строки. Например кейс: 'undefined'  не будет отличаться от кейса 'true', поэтому достаточно одной проверки в этом случае

2023-02-09 15:28 UTC, AntonElagin requested changes
Давай добьем оставшиеся мелочи, и можно будет принять твое решение)

2023-02-09 15:28 UTC, AntonElagin commented on source/chess.js
> +const chess = (numbers) => {
а возвращаемые значение?

2023-02-09 15:28 UTC, AntonElagin commented on tests/chess.js
> +		assert.strictEqual(chess('undefined'), null);
Снова обращу внимание, что тесты на строках 30, 25 и 20 идентичны с точки зрения покрытия кода. Я бы все-таки не стал оставлять лишние тесты

2023-02-09 15:28 UTC, AntonElagin commented on source/chess.js
> +const getOddLine = (numbers) => ODD_LINE_PART.repeat(numbers / 2) + SPACE.repeat(numbers % 2) + '\n';
Давай еще в константы уберем ```'\n'```, а то забавно получается, часть убрали в константы, а часть оставили.

И еще скорее мои мысли чем недостаток. Я бы либо отказался от констант EVEN_LINE_PART и ODD_LINE_PART(заменил на STAR + SPACE и SPACE + STAR). Либо оставил, но формировал значение из тех же SPACE и STAR

2023-02-10 08:06 UTC, AntonElagin requested changes
И еще парочка правок

2023-02-10 08:06 UTC, AntonElagin commented on source/chess.js
> + * @returns {string} chessboard of stars and spaces.
не соответсвует действительности. Мы еще и другие типы вернуть можем

2023-02-10 08:06 UTC, AntonElagin commented on source/chess.js
> +    if ( !Number.isInteger(+numbers) || numbers < 2) {
обрати внимание на оформление кода тут и в других местах.

2023-02-12 11:26 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-12 11:26 UTC, DPeshkoff commented on source/chess.js
> + * @param {int} numbers - size of line.
Кажется, в JS такого типа нет, зато [есть...](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#primitive_values)

2023-02-12 11:26 UTC, DPeshkoff commented on source/chess.js
> +'use strict';
Можешь, пожалуйста, объяснить в реплае, зачем нужен use strict и почему он используется в работе?

2023-02-12 13:00 UTC, BazaleevFedor commented on source/chess.js
> + * @param {int} numbers - size of line.
Да, неправ) исправил

2023-02-12 13:07 UTC, BazaleevFedor commented on source/chess.js
> +'use strict';
Данная директива указывает на то, что в скрипте будет использован строгий режим. Данный режим более современный, устраняет ряд ошибок js, которые были в предыдущих версиях языка. Его добавили для поддержания обратной совместимости. Без указания этой директивы, скрипт обрабатывается как "нестрогий"

2023-02-12 13:29 UTC, DPeshkoff approved these changes

2023-02-12 13:29 UTC, closed without merging