HW done. Вячеслав Шагалов WEB-21
frontend-park-mail-ru/homework_2023_1 pull request #30
Opened 2023-02-09 11:16 UTC by SlavaShagalov

2023-02-12 12:59 UTC, Shureks-den requested changes

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +'use strict';
Для чего это строка нужна? Что изменится если ее не будет?

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +
Давай добавим jsDoc

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +const chess = function (n) {
Как называется способ, которым ты задал функцию? Какие еще есть и в чем их различия

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +    }
Давай добавим проверку что n это действительно число

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +    let is_even = n % 2;
Принятый нейминг стайл в js camelCase, давай будем его придерживаться

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +    let is_even = n % 2;
Значения которые ты не меняешь стоит сделать const

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +    }
Давай попробуем заменить циклы на методы строк, прочитай про методы padStart/padEnd и repeat. Они точно помогут упростить код, например сделать `result.repeat(' *')` и тд

2023-02-12 12:59 UTC, Shureks-den commented on source/chess.js
> +const chess = function (n) {
Еще один теоретический вопрос - как типы данных есть в js и в чем различия между примитивными типами и сложными?

2023-02-12 13:00 UTC, Shureks-den commented
Привет! Добро пожаловать на курс по фронтенду, меня зовут Саша, я буду проверять твое дз, если будут вопросы - пиши в телегу https://t.me/alexklonov

2023-02-15 10:00 UTC, SlavaShagalov commented on source/chess.js
> +const chess = function (n) {
Существует два синтаксиса создания функций - Function Expression и Function Declaration. В данном случае, я задал функцию с помощью  Function Expression, т. к. она создается внутри выражения, а именно выражения присваивания =. Function Declaration - функция объявляется отдельной конструкцией в основном потоке кода. Function Expression создаётся, когда выполнение доходит до него, и затем уже может использоваться. Function Declaration может быть вызвана раньше, чем она объявлена, потому что создается на этапе инициализации движком JS. В строгом режиме, когда Function Declaration находится в блоке {...}, функция доступна везде внутри блока, но не снаружи него.

2023-02-15 10:12 UTC, SlavaShagalov commented on source/chess.js
> +const chess = function (n) {
В JS есть 7 примитивных типов данных: number для любых чисел: (целочисленных или чисел с плавающей точкой), bigint(для целых чисел произвольной длины), string (для строк, строка может содержать ноль или больше символов, нет отдельного символьного типа), boolean, null(неизвестное значение – отдельный тип, имеющий одно значение null), undefined (для неприсвоенных значений – отдельный тип, имеющий одно значение undefined), symbol (для уникальных идентификаторов).
И 8-й тип Object, который является сложным, т. к. является ассоциативным массивом, хранящим пары ключ-значение, причем значения могут быть любых типов. Т. е. Object - составной, поэтому и яявляется сложным. Также свойством объекта может быть функция, которую в таком случае принято назыать методом объекта.

2023-02-15 10:15 UTC, SlavaShagalov commented on source/chess.js
> +'use strict';
Директива "use strict" активирует изменения, сделанные в ECMAScript. По умолчанию эти изменения отключены. При включенной директиве "use strict" говорят, что код расположенный под ней работает в современном режиме. Чтобы по максимуму использовать возможности современного JavaScript, все скрипты рекомендуется начинать с добавления директивы"use strict". Если строки не будет - будет использоваться старый режим.

2023-02-15 10:15 UTC, SlavaShagalov commented on source/chess.js
> +    }
Добавил

2023-02-15 10:15 UTC, SlavaShagalov commented on source/chess.js
> +    let is_even = n % 2;
Исправил

2023-02-15 10:16 UTC, SlavaShagalov commented on source/chess.js
> +    }
Переделал решение с использование padStart

2023-02-15 12:00 UTC, Shureks-den requested changes

2023-02-15 12:33 UTC, SlavaShagalov commented on source/chess.js
> +    const blackRow = "".padStart(num, "* ") + "\n";
Сделал

2023-02-15 12:35 UTC, Shureks-den approved these changes

2023-02-15 13:06 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-15 13:06 UTC, DPeshkoff commented on source/chess.js
> +    if (isNaN(num) || num <= 1) {
А чем отличается [isNaN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/isNaN) от [Number.isNaN](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Number/isNaN) ?

2023-02-15 13:06 UTC, DPeshkoff commented on source/chess.js
> +const chess = function (n) {
А какие еще бывают виды функций в языке?

2023-02-15 13:06 UTC, DPeshkoff commented on tests/chess.js
> +	QUnit.test('Размер доски - строка, непреобразуемая в число', function (assert) {
Давай добавим больше тестов на некорректный ввод - что будет, если я передам undefined, null, NaN, object?

2023-02-15 14:15 UTC, SlavaShagalov commented on source/chess.js
> +    if (isNaN(num) || num <= 1) {
Number.isNaN считается более надёжной версией оригинальной глобальной функции isNaN, потому что не имеет проблемы принудительного преобразования параметра в число. Т. е. Number.isNaN возвращает true только для числовых значений, имеющих значение NaN, в отличие от isNaN, который вовращает true для значений, которые при преобразовании в число дают NaN. Например,
Number.isNaN('blabla');   // false
isNaN('blabla');   // true

2023-02-15 14:24 UTC, SlavaShagalov commented on source/chess.js
> +const chess = function (n) {
Еще бывают стрелочные функции. Они задаются следующим синтаксисом:
`
let func = (arg1, arg2, ...argN) => expression;
`

2023-02-15 15:12 UTC, DPeshkoff commented on source/chess.js
> +    if (isNaN(num) || num <= 1) {
А здесь какую лучше использовать функцию?)

2023-02-15 15:12 UTC, DPeshkoff commented on source/chess.js
> +const chess = function (n) {
А давай перепишем на стрелочную функцию. Кстати, чем они отличаются от обычных?

2023-02-15 16:27 UTC, SlavaShagalov commented on source/chess.js
> +    if (isNaN(num) || num <= 1) {
Здесь лучше было использовать Number.isNaN, так как на предыдущей строчке уже была произведена конвертация входного параметра в число.

2023-02-15 17:08 UTC, SlavaShagalov commented on source/chess.js
> +const chess = function (n) {
Переписал. Отличия стрелочных от обычных:
1. Не имеет this. Не имеет значения как она была вызвана, значение this внутри стрелочной функции всегда эквивалентно значению this внешней функции. Другими словами функция не создает собственный контекст исполнения, она использует внешний.
2. Не имеют arguments. Работает аналогично this.
3. Не могут быть вызваны с new, так как нет своего this. Другими словами стрелочные функции не могут быть конструкторами.
4. Неявный return. Если стрелочная функция содержит в теле одну инструкцию и опущены фигурные скобки, то выражение будет возвращено автоматически.
5. Стрелочную функцию можно использовать как метод класса. В таком случае, стрелочную функцию, в отличие от обычной, будет удобнее использовать в качестве колбека, так как не придется вручную с помощью bind привязывать this к объекту, метод которого вызывается.

2023-02-15 17:16 UTC, DPeshkoff approved these changes

2023-02-15 17:16 UTC, closed without merging