Долгих Артём Вариант 17
frontend-park-mail-ru/homework_2023_1 pull request #32
Opened 2023-02-09 13:31 UTC by Hareshutit

2023-02-13 11:45 UTC, inerc commented
Привет Артем, добро пожаловать на курс фронтенда!
Меня зовут Женя, я буду проверять твое дз0

Здорово, что у тебя получилось реализовать функцию чтобы прошли тесты. Очень круто что ты сделал новый кейс для тестов.
![image](https://user-images.githubusercontent.com/15797209/218448629-edd9b0a5-3fa1-41f4-a571-6bd2c5e5c49c.png)

Предлагаю сделать твое решение красивей:
- [ ] Давай добавим JsDoc
- [ ] Сделаем валидацию входных параметров функции и обработчик ошибки
- [ ] Исправим нюансы в коде. (смотри верью)

Подробнее по коду написал в ревью.

PS По любым вопросам можешь писать тут или мне в телегу [@inerc](https://t.me/inerc)

2023-02-13 11:47 UTC, inerc requested changes

2023-02-13 11:47 UTC, inerc commented on source/plainify.js
> +function  plainify(object) {
JsDoc

2023-02-13 11:47 UTC, inerc commented on source/plainify.js
> +    function iterate(path, obj) {
Может стрелочные функции заюзаем?
https://learn.javascript.ru/arrow-functions-basics

2023-02-13 11:47 UTC, inerc commented on source/plainify.js
> +    function iterate(path, obj) {
Может вынести ее из plainify вдруг она еще кому пригодится?

2023-02-13 11:47 UTC, inerc commented on source/plainify.js
> +    iterate('', object);
тут можно передать первым параметром null а в функции использовать дефолтный параметр.

2023-02-13 19:54 UTC, Hareshutit commented on source/plainify.js
> +function  plainify(object) {
+

2023-02-13 19:54 UTC, Hareshutit commented on source/plainify.js
> +    function iterate(path, obj) {
+

2023-02-13 19:54 UTC, Hareshutit commented on source/plainify.js
> +    function iterate(path, obj) {
+

2023-02-13 19:54 UTC, Hareshutit commented on source/plainify.js
> +    iterate('', object);
+

2023-02-13 20:00 UTC, inerc approved these changes

2023-02-13 20:28 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 20:28 UTC, DPeshkoff commented on source/plainify.js
> +let iterate = (obj, obj_plain, path = "") => {
[Let, const, var?](https://t.me/makingweb/148)

2023-02-13 20:28 UTC, DPeshkoff commented on source/plainify.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-13 20:28 UTC, DPeshkoff commented on source/plainify.js
> + * @param {obj_plain} - пустой объект предназначенный для содержания  plain-объекта
Таких примитивов в языке [нет](https://developer.mozilla.org/ru/docs/Glossary/Primitive)

2023-02-13 20:28 UTC, DPeshkoff commented on source/plainify.js
> +    iterate(object, obj_plain);
А давай попробуем сделать это [методами](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)(1) [языка](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array)(2)

2023-02-13 20:28 UTC, DPeshkoff commented on source/plainify.js
> +}
В конце лучше делать [перенос строки](https://semakin.dev/2020/05/no_newline_at_end_of_file/)

2023-02-13 20:28 UTC, DPeshkoff commented on tests/plainify.js
> +		let plain = {}
Не пренебрегай ;

Иначе могут случится вот такие забавные (не очень) ситуации:

![изображение](https://user-images.githubusercontent.com/31134795/218567098-5d11cde5-ffdd-48c5-bb75-ecf26f62b90b.png)

2023-02-13 20:28 UTC, DPeshkoff commented on tests/plainify.js
> +			'deep.nested.wer': functionalObject(2)
А зачем тут функции?)

2023-02-13 20:28 UTC, DPeshkoff commented on source/plainify.js
> +    if (object === null || Object.getPrototypeOf(object) !== Object.getPrototypeOf({})) {
Кажется, проверка не полная...

![изображение](https://user-images.githubusercontent.com/31134795/218567385-2fa0fa35-ceb3-4749-8f44-93cd21b78d51.png)

2023-02-13 20:28 UTC, DPeshkoff commented on tests/plainify.js
> +
Нужны тесты на некорректный ввод

2023-02-13 20:28 UTC, DPeshkoff commented on source/plainify.js
> +let plainify = (object) => {
А чем функции-стрелки отличаются от обычных функций?

2023-02-13 20:51 UTC, Hareshutit commented on source/plainify.js
> +let plainify = (object) => {
Поведение this внутри стрелочной функции отличается от поведения this внутри обычной функции. Не имеет значения как она была вызвана, значение this внутри стрелочной функции всегда эквивалентно значения this внешней функции. Более компактный синтаксис. Как следствие того, что стрелочные функции не имеют собственного this они не могут быть использованы для создания объектов.

2023-02-13 20:54 UTC, Hareshutit commented on source/plainify.js
> +'use strict';
Директива: "use strict" или 'use strict'. Когда она находится в начале скрипта, весь сценарий работает в «современном» режиме.

2023-02-13 22:35 UTC, Hareshutit commented on tests/plainify.js
> +
Сделал

2023-02-13 22:36 UTC, Hareshutit commented on source/plainify.js
> +    if (object === null || Object.getPrototypeOf(object) !== Object.getPrototypeOf({})) {
Неправильная формулировка)

2023-02-13 22:36 UTC, Hareshutit commented on tests/plainify.js
> +			'deep.nested.wer': functionalObject(2)
Исправил

2023-02-13 22:36 UTC, Hareshutit commented on tests/plainify.js
> +		let plain = {}
Поправил

2023-02-13 22:36 UTC, Hareshutit commented on source/plainify.js
> +}
Сделано

2023-02-13 22:36 UTC, Hareshutit commented on source/plainify.js
> +    iterate(object, obj_plain);
Реализовал

2023-02-13 22:37 UTC, Hareshutit commented on source/plainify.js
> + * @param {obj_plain} - пустой объект предназначенный для содержания  plain-объекта
Поправил

2023-02-13 22:37 UTC, Hareshutit commented on source/plainify.js
> +let iterate = (obj, obj_plain, path = "") => {
Поправил)

2023-02-14 14:49 UTC, DPeshkoff commented
Привет! Напиши мне в телеграм или в ВК, пожалуйста)

2023-02-14 15:56 UTC, closed without merging