Попов Степан Variant 15
frontend-park-mail-ru/homework_2023_1 pull request #33
Opened 2023-02-09 14:16 UTC by stepanpopov

2023-02-13 12:56 UTC, sashanau commented
Привет, поздравляю с началом семестра! Я буду проверять твое ДЗ0! Вот мое тг для вопросов: @sasha12332154

2023-02-13 13:26 UTC, sashanau commented on source/filter.js
> +let extra = new Map([['>', "&gt;"],
Давай использовать const везде, где это возможно и положим эти поля в {}

2023-02-13 13:26 UTC, sashanau commented on source/filter.js
> +let filter = function(input, tags) {
Давай использовать arrow function, почитай тут https://learn.javascript.ru/arrow-functions-basics

2023-02-13 13:26 UTC, sashanau commented on source/filter.js
> +    for (let i = 0; i < input.length; ++i) {
Почитай и используй forEach https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2023-02-13 13:26 UTC, sashanau commented on source/filter.js
> +    for (let tag of tags) {
используй forEach

2023-02-13 13:26 UTC, sashanau commented on source/filter.js
> +            if (output[pos - 1] == '/') {
Давай откажемся от ==, в js принято использовать ===, знаешь в чем разница?

2023-02-13 13:26 UTC, sashanau commented on source/filter.js
> +            if (output[pos - 1] == '/') {
Также почитай про https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Conditional_Operator и попробуй применить тут

2023-02-13 13:26 UTC, sashanau commented on source/filter.js
> +    let output = ""
Обычно используют ''

2023-02-13 13:26 UTC, sashanau commented on tests/filter.js
> +	QUnit.test('filter проверяет несколько вложенных тегов', function (assert) {
Давай добавим еще пару тестов на краевые случаи

2023-02-13 21:09 UTC, stepanpopov commented on source/filter.js
> +            if (output[pos - 1] == '/') {
== использует касты в отличие от ===

2023-02-13 21:24 UTC, stepanpopov commented on source/filter.js
> +let extra = new Map([['>', "&gt;"],
Насколько я понял, чтобы использовать {} нужно будет перейти к объекту, а использование Map будет более уместным (эффективным и явным). Поправь меня, если я не прав.

2023-02-14 09:38 UTC, sashanau commented on source/filter.js
> +let extra = new Map([['>', "&gt;"],
Обычно Map используют, когда ключи не являются строкой или структура изменяемая.
В твоем случае это просто хранилище, поэтому рекомендую использовать объект.

Использование Map или object не сильно влияет на эффективность

2023-02-15 09:58 UTC, sashanau requested changes

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +let filter = (input, tags) => {
Используй const

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +        let changedSymb = extra[symb];
const

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +        if (changedSymb === undefined) {
Давай попробуем упростить так output += changedSymb || symb, расскажи как такое работает?

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +    if (tags === undefined) {
Чаще всего лучше проверять !variable вместо четкой проверки

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +        }
Попробуй упростить эту часть кода и используй const везде, где это возможно

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +        }
Используй https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Template_literals

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +        while ((pos = output.indexOf(tag, pos + 1)) != -1) {
!==

2023-02-15 09:58 UTC, sashanau commented on source/filter.js
> +        let changedSymb = extra[symb];
changedSymb? Давай использовать везде Snake case

2023-02-16 08:32 UTC, stepanpopov commented on source/filter.js
> +        if (changedSymb === undefined) {
Этот оператор возвращает первый аргумент, равный true, либо последний, если все false. Null/undefined приведется к false. Соответственно, если changed_symb является null/undefined, то вернется symb.

2023-02-16 11:57 UTC, sashanau requested changes

2023-02-16 11:57 UTC, sashanau commented on source/filter.js
> +        output += extra[symb] || symb
Давай поддерживать один код стайл и поставим тут ";"

2023-02-16 11:57 UTC, sashanau commented on source/filter.js
> +                : `${output.slice(0, pos - lt_sym_len)}<${tag}${output.slice(pos + tag_len, gt_sym_pos)}>${output.slice(gt_sym_pos + gt_sym_len)}`
;

2023-02-16 11:57 UTC, sashanau commented on source/filter.js
> +    });
Давай тут использовать reduce. Почти везде, где накопление принято использовать его.

2023-02-16 12:30 UTC, sashanau approved these changes

2023-02-16 19:39 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-16 19:39 UTC, DPeshkoff commented on source/filter.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-16 19:39 UTC, DPeshkoff commented on source/filter.js
> +const filter = (input, tags) => {
Давай проверять входные значения - вдруг там не строка, например

2023-02-16 19:39 UTC, DPeshkoff commented on tests/filter.js
> +	});
Давай еще добавим тестов на некорректный ввод

2023-02-16 19:39 UTC, DPeshkoff commented on source/filter.js
> +const filter = (input, tags) => {
Кстати, а чем стрелочные функции отличаются от обычных?

2023-02-16 20:31 UTC, stepanpopov commented on source/filter.js
> +'use strict';
Весь код ниже этой директиве начинает работать в современном режиме (стандарт ES5). Включается поддержка нового функционала, а старый код может работать некорректно или не работать.

2023-02-16 20:40 UTC, stepanpopov commented on source/filter.js
> +const filter = (input, tags) => {
У стрелочных функций нет this. При обращении к this, его значение берётся снаружи. В отличие от обычных функций, которые будут обращаться к собственном this. Также у них нет переменной arguments, поэтому их удобно использовать в декораторах.

2023-02-16 21:02 UTC, stepanpopov commented
У меня случайно сбилась дата, поэтому новые коммиты с исправлениями показывает до ревью((

2023-02-17 10:29 UTC, DPeshkoff approved these changes

2023-02-17 10:29 UTC, closed without merging