Нигматуллин Алик Вариант 11
frontend-park-mail-ru/homework_2023_1 pull request #34
Opened 2023-02-09 14:37 UTC by BigBullas

2023-02-13 13:12 UTC, AntonElagin requested changes
Привет, приветствую тебя на курсе фронтенда. Я буду проверять твое дз0.

У тебя получилось неплохое решение, но его все равно можно чуточку улучшить

- [x]  Давай еще разок проверим, что код оформлен в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для этих целей можно использовать [eslint](https://eslint.org/)
- [x] Стоит пробрасывать ошибки для неверных входных данных и в целом обрабатывать все возможные случаи со всеми возможными ошибками

PS Если будут какие-то вопросы, пиши тут или мне в телегу [@Anton_ELagin](https://t.me/Anton_Elagin)

2023-02-13 13:12 UTC, AntonElagin commented on .gitignore
> +node_modules
Слишком много лишних файлов, достаточно оставить diff с функцией, html и тесты

2023-02-13 13:12 UTC, AntonElagin commented on source/rle.js
> +//First version
Все лишние комментарии надо убрать

2023-02-13 13:12 UTC, AntonElagin commented on source/rle.js
> +    function (substr, sym) { return sym + (substr.length > 1 ? substr.length : ''); });
давай будем использовать везде функции стрелки, это более современный подход в js

https://learn.javascript.ru/arrow-functions-basics

2023-02-13 13:12 UTC, AntonElagin commented on tests/rle.js
> +			"rle('AVVVBBBVVXDHJFFFFDDDDDDHAAAAJJJDDSLSSSDDDD') === 'AV3B3V2XDHJF4D6HA4J3D2SLS3D4'");
стоит написать тесты на невалидные входные данные

2023-02-15 09:04 UTC, AntonElagin requested changes
Давай еще немного доработаем твое решение.

Еще раз обрати внимание на оформление твоего кода. Самы очевидный пример ```;```: на первой строчке есть, дальше нету(Давай пока использовать везде ```;```).
Стрелочные функции обычно оборачиваем в скобки всегда(даже когда у нас 1 аргумент). Так все выглядит одинаково, и удобно расширять аргументы, если потребуется

Я бы еще слегка обратил внимание на нейминг переменных. Имя должно как можно лучше отражаться сущность и назаначение переменной. Например: даже ```str``` будет лучше ```s``` с точки зрения читаемости

2023-02-15 10:54 UTC, AntonElagin requested changes

2023-02-15 10:54 UTC, AntonElagin commented on source/rle.js
> +    if (typeof str !== "string") {
Вспомнил тут еще вот такой кейс. Попробуй прокинуть в свою функцию в качестве аргумента ```new String('AAABBBCCC')```. Технически - это тож валидная строка, но у нас упадет функция с ошибкой.

Тоже вспомнил только что, что будем делать если нам передадут ```'123AAAXX#'``` Кажется такое свернуть мы валидно не сможем. Как определить какая цифра к чему относится? Обычно в такой задаче ограничиваются только буквами, возможно символами, но числа тут как-то плохо подходят)

2023-02-15 10:54 UTC, AntonElagin commented on source/rle.js
> +}
в конце функций стрелок принято ставить ```;```

2023-02-15 12:38 UTC, AntonElagin requested changes

2023-02-15 12:38 UTC, AntonElagin commented on source/rle.js
> +    if (typeof str == "object" && str !== null) {
Советую воспользоваться [instanceOf](https://learn.javascript.ru/instanceof)

2023-02-15 12:38 UTC, AntonElagin commented on source/rle.js
> +        str = str.valueOf();
В целом ничего страшного не произойдет, если мы не преобразуем объект String в примитив

2023-02-15 12:38 UTC, AntonElagin commented on source/rle.js
> +    if (typeof str !== "string" || !str.split('').every((sym) => isNaN(sym))) {
```str.split('').every((sym) => isNaN(sym))``` что-то как-то не сильно смахивает на typeError^ может лучше отдельную ошибку?

2023-02-15 17:37 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-15 17:37 UTC, DPeshkoff commented on source/rle.js
> +        throw new TypeError('Error');
Лайк, но давай напишем, что же все-таки за Error)

2023-02-15 17:37 UTC, DPeshkoff commented on source/rle.js
> +    if (typeof str !== "string" && !(str instanceof String)) {
Традиционно принято в одиночные кавычки)

2023-02-15 17:37 UTC, DPeshkoff commented on source/rle.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-15 17:37 UTC, DPeshkoff commented on source/rle.js
> +    if (!str.split('').every((sym) => isNaN(sym))) {
А чем отличаются между собой `Number.isNaN()` и `isNaN()` ? Почему выбрал именно второе?

2023-02-15 17:37 UTC, DPeshkoff commented on tests/rle.js
> -		assert.strictEqual(rle('AVVVBBBVVXDHJFFFFDDDDDDHAAAAJJJDDSLSSSDDDD'), 'AV3B3V2XDHJF4D6HA4J3D2SLS3D4');
Давай вернем)

2023-02-15 17:37 UTC, DPeshkoff commented on tests/rle.js
> +	QUnit.test('Функция работает с new String', function (assert) {
Нужны тесты на кейс, если аргументы вообще некорректные)

2023-02-15 19:12 UTC, BigBullas commented on source/rle.js
> +    if (!str.split('').every((sym) => isNaN(sym))) {
Вообще Number.isNan более строгая версия функции isNan. Первая вначале проверяет, является ли аргумент числом, а уже затем преобразует его в число, в отличие от функции isNan, которая первым делом преобразует аргумент в число. Из-за таких различий Number.isNan считается более надёжной. Так, для нечисловых данных, которые при приведении к числовому типу приводят к допустимому числовому значению, отличному от NaN (в частности, пустая строка и логические примитивы, которые при принуждении дают числовые значения ноль или один), возвращаемое значение «ложь» может быть неожиданным.
Я же выбрал вторую, потому что даю функции строку из одного элемента, поэтому изначально, без преобразования в число, Number.isNan будет давать неверный ответ, в отличие от isNan, который прекрасно справляется с данной мной задачей)

2023-02-16 09:39 UTC, DPeshkoff approved these changes

2023-02-16 09:40 UTC, closed without merging