HW Naberezhnaya variant10
frontend-park-mail-ru/homework_2023_1 pull request #35
Opened 2023-02-09 16:01 UTC by mashanab

2023-02-09 18:12 UTC, wd055 commented on source/letters.js
> +const letters = (string, flag) => {
Давай добавим JSDoc

2023-02-09 18:12 UTC, wd055 commented on source/letters.js
> +    [...(flag) ? string : string.split("").reverse().join("")].forEach(letter => {
Советую посмотреть методы массивов, может получится сделать сильно эффективнее

2023-02-09 18:12 UTC, wd055 commented on tests/letters.js
> +	QUnit.test('Дополнительная проверка различных случаев', function (assert) {
Маловато разных кейсов. Подумай, какие еще крайние кейсы можно добавить?

2023-02-09 18:12 UTC, wd055 commented on tests/letters.js
> +		assert.strictEqual(letters('jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjd'), 'd', "letters('irys    ssd') === 'iryd'");
Для чего так много одинаковых символов подряд?)

2023-02-09 18:21 UTC, wd055 commented
Привет! Я буду проверять твоё ДЗ0. Хорошая первая итерация, давай займемся улучшениями!

2023-02-09 23:09 UTC, wd055 commented
Удали лишние файлы, пожалуйста)

2023-02-09 23:11 UTC, mashanab commented
> Удали лишние файлы, пожалуйста)

То есть не создавать папку out?

2023-02-09 23:13 UTC, wd055 commented
Не, не нужно

2023-02-09 23:16 UTC, mashanab commented on source/letters.js
> +    let seen = new Set();
string? это тип данных.

2023-02-09 23:18 UTC, mashanab commented
Исправила

2023-02-09 23:18 UTC, wd055 commented on source/letters.js
> +    let seen = new Set();
Я про `let seen = new Set();`

2023-02-09 23:19 UTC, mashanab commented on source/letters.js
> +    let seen = new Set();
Лучше не называть как типы данных

2023-02-09 23:21 UTC, wd055 commented on source/letters.js
> +    for (let letter of line) {
Опять же. Тут лучше использовать не цикл, а метод массива

2023-02-09 23:21 UTC, wd055 commented on source/letters.js
> +        delete result_array[result_array.indexOf(letter)];
Решение не очень оптимально. На каждую букву ты пробегаешь по всему собранному результату. Может есть решение оптимальнее?

2023-02-09 23:21 UTC, wd055 commented on source/letters.js
> +const letters = (line, flag) => {
Что будет, если переданы некорректные вводные? Давай добавим валидацию

2023-02-09 23:32 UTC, wd055 commented
И файл/папка .DS_Store явно лишний)

2023-02-10 08:10 UTC, wd055 commented on source/letters.js
> +    let seen = new Set();
Вообще я имел в виду const)

2023-02-10 10:30 UTC, mashanab commented on source/letters.js
> +        delete result_array[result_array.indexOf(letter)];
Подойдёт, если я  сделаю через регулярные выражения? 
Я делала через реверс строки и работу в одном цикле, без усложнений в работе, а вы все равно сказали, что это не оптимально… оптимальнее не придумаю… регулярки сократят код

2023-02-10 14:32 UTC, mashanab commented on source/letters.js
> +    let seen = new Set();
Да, потому что он не меняется дальше и const производительность увеличит.

2023-02-11 10:40 UTC, wd055 commented on source/letters.js
> +            return '';
Тут точно пустая строка должна возвращаться?

2023-02-11 10:40 UTC, wd055 commented on source/letters.js
> +    return [...line].filter((item, idx, arr) => {
Это очень сложно алгоритмически. На каждый символ проходишь весь массив. Может есть решение оптимальнее?

2023-02-11 10:40 UTC, wd055 commented on source/letters.js
> +        delete result_array[result_array.indexOf(letter)];
Регулярка быстрее прохода, но она тоже не оптимальна. Может тебе как-то аккумулировать какие-то данные?

2023-02-11 10:56 UTC, mashanab commented on source/letters.js
> +        delete result_array[result_array.indexOf(letter)];
Я не знаю, что значит аккумулировать в программировании. Но я предложила новый способ после прочтения методов массива.

2023-02-11 10:56 UTC, mashanab commented on source/letters.js
> +            return '';
А есть пример, что может возвращаться ?

2023-02-11 10:57 UTC, mashanab commented on source/letters.js
> +    return [...line].filter((item, idx, arr) => {
Не весь массив , а только часть

2023-02-11 11:00 UTC, wd055 commented on source/letters.js
> +    return [...line].filter((item, idx, arr) => {
Все равно можно сделать сильно оптимальнее. Например, аккумулировать прошедшую часть в какой-то оптимальной структуре

2023-02-11 11:00 UTC, mashanab commented on source/letters.js
> +            return '';
Ок

2023-02-11 11:01 UTC, wd055 commented on source/letters.js
> +    return [...line].filter((item, idx, arr) => {
Ранее была реализация с new Set, как пример

2023-02-11 11:03 UTC, wd055 commented on source/letters.js
> +        delete result_array[result_array.indexOf(letter)];
У тебя был уже Set. В целом стоит свести решение к одному проходу по массиву в идеале

2023-02-11 11:06 UTC, mashanab commented on source/letters.js
> +    return [...line].filter((item, idx, arr) => {
Я тогда за регулярку. Можно?

2023-02-11 11:15 UTC, wd055 commented on source/letters.js
> +    return [...line].filter((item, idx, arr) => {
К сожалению, нельзя

2023-02-11 11:48 UTC, mashanab commented on source/letters.js
> +        delete result_array[result_array.indexOf(letter)];
Как свести ПОЛНОЕ удаление символов, которые повторяются, к одному проходу? Ладно в случая с оставлением символа, можно разворачивать массив и все равно оставлять просто первые символы, которые встречались.

2023-02-11 22:20 UTC, mashanab commented
Теперь финально. Когда flag - true или false, то сложность O(n), а если второй флаг не передается, то O(2n), что и есть O(n). Так что алгоритм МАКСИМАЛЬНО оптимизирован.

2023-02-12 13:18 UTC, wd055 commented on source/letters.js
> +    if (typeof line !== "string") {
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String#%D1%80%D0%B0%D0%B7%D0%BD%D0%B8%D1%86%D0%B0_%D0%BC%D0%B5%D0%B6%D0%B4%D1%83_%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%BE%D0%B2%D1%8B%D0%BC%D0%B8_%D0%BF%D1%80%D0%B8%D0%BC%D0%B8%D1%82%D0%B8%D0%B2%D0%B0%D0%BC%D0%B8_%D0%B8_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%B0%D0%BC%D0%B8_string

2023-02-12 14:30 UTC, wd055 commented on source/letters.js
> +    if (typeof line !== "string") {
Добавь еще условие в проверку и аппрувну)

2023-02-13 12:03 UTC, mashanab commented on source/letters.js
> +    if (typeof line !== "string") {
Готово!

2023-02-13 12:46 UTC, mashanab commented on source/letters.js
> +'use strict';
Директива "use strict" или 'use strict'. Она находится в начале скрипта, тогда весь сценарий работает в «строгом» режиме.
Строгий режим вносит в семантику JavaScript некоторые изменения. Он не даёт системе закрывать глаза на ошибки, выдавая соответствующие исключения. Это приводит к остановке выполнения программ.
В этом режиме также запрещено использование элементов синтаксиса, которые могут получить особый смысл в будущих версиях языка.
В исходном коде был уже использован данный режим, а лучше всего не смешивать «строгие» и «нестрогие» скрипты, так как при объединении кода возникнет спорная ситуация, какой режим использовать.

2023-02-13 12:47 UTC, mashanab commented on source/letters.js
> + * @param {line} line - Исходная строка
Понятно, поменяю line на string.

2023-02-13 12:48 UTC, mashanab commented on tests/letters.js
> +
Понятно. Сделаю.

2023-02-13 13:33 UTC, DPeshkoff commented on source/letters.js
> +        if (flag === false) line = line.reverse();
Лучший вариант лучше приемлемого) 
![изображение](https://user-images.githubusercontent.com/31134795/218471605-bf95796c-fe19-43e1-9355-8903b33a759d.png)

2023-02-13 13:37 UTC, mashanab commented on source/letters.js
> +        if (flag === false) line = line.reverse();
Понятно, использовать alert надо :)

2023-02-13 13:38 UTC, mashanab commented
Готово ✅

2023-02-13 13:49 UTC, DPeshkoff requested changes

2023-02-13 13:49 UTC, DPeshkoff commented on tests/letters.js
> +		}
Давай сделаем немного [почище](https://api.qunitjs.com/assert/throws/)

2023-02-13 14:45 UTC, mashanab commented on tests/letters.js
> +		}
Не получается. Я долго пыталась уже. Выдает ошибку, так как сравнивает объекты ошибок двойным равенством.
assert.throws(letters(false), new TypeError('The first parameter is not a string!'), '');
Выдает на сайте в итоге
Expected: 	null
Message: 	Diff suppressed as the expected and actual results have an equivalent serialization
Source: 	TypeError: The first parameter is not a string!
    at letters (http://127.0.0.1:5500/source/letters.js:15:15)
    at Object.<anonymous> (http://127.0.0.1:5500/tests/letters.js:85:17)

2023-02-13 15:12 UTC, DPeshkoff approved these changes

2023-02-13 15:13 UTC, closed without merging