Тонкоштан Андрей (hw#0 front)
frontend-park-mail-ru/homework_2023_1 pull request #36
Opened 2023-02-09 21:34 UTC by TonL

2023-02-09 22:25 UTC, rflban commented on source/euclid.js
> +      tmp = a % b;
Попробуй подумать как сделать своп синтаксически без дополнительной переменной

2023-02-09 22:25 UTC, rflban commented on source/euclid.js
> +    while (numbers.length > 1) {
Постарайся обойтись встроенными методами массива, а не циклом

2023-02-09 22:25 UTC, rflban commented on source/euclid.js
> +const euclid = (...numbers) => {
Давай добавим валидацию для входных данных

2023-02-09 22:27 UTC, rflban commented
Привет! Я буду проверять твоё ДЗ0! У тебя очень хорошее решение, давай немного улучшим его

2023-02-11 10:26 UTC, rflban requested changes

2023-02-11 10:26 UTC, rflban commented on source/euclid.js
> +        return typeof element === 'number';
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/Number

2023-02-11 10:26 UTC, rflban commented on source/euclid.js
> +    if (!err) {
на первый взгляд кажется, что ты кидаешь исключение если нет ошибки, думаю, лучше переименовать эту переменную

2023-02-11 10:26 UTC, rflban commented on source/euclid.js
> +    }, numbers[0]);
если не передавать второй аргумент в reduce, что произойдет?

2023-02-11 10:26 UTC, rflban commented on source/euclid.js
> +    let result = numbers.reduce(function(result, current) {
почему переменная объявлена именно через let? какие другие варианты есть и чем они отличаются?

2023-02-11 10:26 UTC, rflban commented on source/euclid.js
> +    let result = numbers.reduce(function(result, current) {
а зачем здесь функция-обертка над gcd?

2023-02-11 15:07 UTC, TonL commented on source/euclid.js
> +    }, numbers[0]);
Разобрался, если не передавать второй аргумент, то result будет равен значению первого элемента, поэтому можно убрать `numbers[0]`

2023-02-11 15:12 UTC, TonL commented on source/euclid.js
> +    let result = numbers.reduce(function(result, current) {
Лишняя, сейчас уберу

2023-02-11 15:27 UTC, TonL commented on source/euclid.js
> +    let result = numbers.reduce(function(result, current) {
всего 3 способа: 
- var - устаревший, можно обращаться (в отличие от остальных) до момента объявления (ошибки не будет, вернет undefined)
- let - для нового кода
- const - для констант

2023-02-11 16:03 UTC, TonL commented
Исправил ошибки

2023-02-11 17:06 UTC, rflban commented on source/euclid.js
> +    let result = numbers.reduce(function(result, current) {
верно, только const скорее для неизменяемых переменных, защита от выстрела себе в ногу. тут по логике result не меняется, поэтому лучше использовать const. а вообще лучше без переменной, потому что следующей строкой у тебя return

2023-02-13 13:19 UTC, TonL commented on source/euclid.js
> +    let result = numbers.reduce(function(result, current) {
Убрал переменную перед return

2023-02-13 13:47 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Хорошая работа, но есть вопрос к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 13:47 UTC, DPeshkoff commented on source/euclid.js
> +'use strict';
Можешь, пожалуйста, объяснить в реплае, зачем нужен use strict и почему он используется в работе?

2023-02-13 17:46 UTC, TonL commented on source/euclid.js
> +'use strict';
@DPeshkoff use strict включает строгий режим выполнения js. Запрещает использовать некоторые небезопасные конструкции языка, устаревший функционал. Включает новые функции языка. Нужен, чтобы старые браузеры продолжали работать

2023-02-13 18:10 UTC, DPeshkoff approved these changes

2023-02-13 18:10 UTC, closed without merging