Домашнее задание №0
frontend-park-mail-ru/homework_2023_1 pull request #37
Opened 2023-02-09 22:32 UTC by Rioskill

Добрый день, отправляю на проверку домашнее задание №0.

С уважением, Скворцов Никита (WEB-21)

2023-02-12 11:06 UTC, code1cult commented
Скажи пожалуйста почему не используешь "use strict" ?

2023-02-12 11:06 UTC, code1cult commented on source/solve.js
> +const solve = (expression, argument) => {
Скажи пожалуйста почему не используешь "use strict" ?

2023-02-12 11:07 UTC, code1cult commented on source/solve.js
> +    const flip_arguments = f => (...args) => f(...args.reverse())
Давай добавим к твоему коду документацию. Для этого идеально подойдет JsDoc.

Ссылочки:
https://jsdoc.app/

2023-02-12 11:13 UTC, code1cult commented on source/solve.js
> +        return {priority: priority, exec: flip_arguments(func)};
Давай будем придерживаться код стайла 
https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2023-02-12 11:17 UTC, code1cult commented on source/solve.js
> +    const apply = (op_stack, num_stack) => num_stack.push(ops[op_stack.pop()].exec(num_stack.pop(), num_stack.pop()));
Что произойдет, если на вход дать невалидные данные?

2023-02-12 17:20 UTC, Rioskill commented on source/solve.js
> +const solve = (expression, argument) => {
Спасибо за замечание, добавил 'use strict'

2023-02-12 17:31 UTC, Rioskill commented on source/solve.js
> +    const apply = (op_stack, num_stack) => num_stack.push(ops[op_stack.pop()].exec(num_stack.pop(), num_stack.pop()));
Условия основного цикла гарантируют, что в момент вызова apply на верху op_stack находится валидный оператор; повторная проверка показалась мне излишней. Однако, при передаче в функцию невалидного математического выражения, в num_stack может оказаться меньше 2 элементов: добавил проверку.

2023-02-14 19:51 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-14 19:51 UTC, DPeshkoff commented on source/solve.js
> +    for (const symbol of expression) {
Гоу попробуем использовать встроенные методы языка)

2023-02-14 19:51 UTC, DPeshkoff commented on source/solve.js
> +            continue;
А еще лучше ставить {} )

2023-02-14 19:51 UTC, DPeshkoff commented on source/solve.js
> +    let num_stack = [];
Кажется, можно [получше](https://t.me/makingweb/148)

2023-02-14 19:51 UTC, DPeshkoff commented on tests/solve.js
> +        assert.strictEqual(solve('((5 - x) * (x + 5)) * x * x', 3), 144);
Давай уберем diff и вернем, как было)

2023-02-14 19:51 UTC, DPeshkoff commented on tests/solve.js
>  	});
отступ поехал

2023-02-14 19:51 UTC, DPeshkoff commented on tests/solve.js
> +    });
Давай добавим тесты на некорректный ввод - например, undefined, null

2023-02-16 22:16 UTC, Rioskill commented on source/solve.js
> +'use strict';
"use strict" указывает интерпретатору, что код надо выполнять в "строгом режиме", при котором так называемые "тихие" ошибки преобразуются в исключения. В строгом режиме запрещены некоторые конструкции, потенциально приводящие к ошибкам, вроде дублирования имён параметров функции,  а также конструкции, мешающие интерпретатору производить оптимизации, например, ключевое слово with. Помимо этого, в строгом режиме предусмотрены механизмы, повышающие общую безопасность кода, в частности ограничение eval  и arguments.

2023-02-17 10:30 UTC, DPeshkoff approved these changes

2023-02-17 10:30 UTC, closed without merging