Никита Горячев, вариант 13
frontend-park-mail-ru/homework_2023_1 pull request #39
Opened 2023-02-10 16:34 UTC by niki-gor

2023-02-13 13:33 UTC, AntonElagin requested changes
Привет, приветствую тебя на курсе фронтенда. Я буду проверять твое дз0.

У тебя получилось неплохое решение, но его все равно можно чуточку улучшить

- [ ] Давай проверим еще разок код. Нужно стараться оформлять код в едином стиле. [Вот советы по оформлению кода](https://learn.javascript.ru/coding-style). В дальнейшем для этих целей можно использовать [eslint](https://eslint.org/)
- [ ] Стоит пробрасывать ошибки для неверных входных данных и в целом обрабатывать все возможные случаи со всеми возможными ошибками

PS Если будут какие-то вопросы, пиши тут или мне в телегу [@Anton_ELagin](https://t.me/Anton_Elagin)

2023-02-13 13:33 UTC, AntonElagin commented on source/get.js
> + * @returns {Object} - object that can be interpreted as obj['attr1']['attr2']['attrN']
а точно ли всегда возвращается объект?

2023-02-13 13:33 UTC, AntonElagin commented on source/get.js
> +        return eval('obj' + attrs.replaceAll(/\.(\w+)/g, "['$1']"));
Лучше не использовать ```eval```. Чаще всего это считается плохой практикой

2023-02-13 13:33 UTC, AntonElagin commented on source/get.js
> +    if (attrs == '.') {
В js надо стараться всегда использовать строгое равенство

2023-02-13 13:33 UTC, AntonElagin commented on source/get.js
> +class ValueError extends Error {
получилась какая-то очень расплывчатая ошибка, точно ли для нее нужно создавать отдельный класс?

Почему бы просто не написать что-то вроде: ```throw new Error("attrs must start with '.'")
    }```

2023-02-13 13:33 UTC, AntonElagin commented on source/get.js
> +function get(obj, attrs) {
давай использовать функции стрелки, это более современный и модный подход  в js

https://learn.javascript.ru/arrow-functions-basics

2023-02-13 13:33 UTC, AntonElagin commented on source/get.js
> +        return eval('obj' + attrs.replaceAll(/\.(\w+)/g, "['$1']"));
И давай попробуем обойтись без регулярок, они усложняют чтение кода

2023-02-13 13:33 UTC, AntonElagin commented on source/get.js
> +    try {
а зачем тут вообще нам try нужен?

2023-02-13 13:33 UTC, AntonElagin commented on tests/get.js
> +	});
давай напишем тесты на невалидные данные

2023-02-13 16:33 UTC, niki-gor commented on source/get.js
> + * @returns {Object} - object that can be interpreted as obj['attr1']['attr2']['attrN']
{Object|undefined}

2023-02-13 16:33 UTC, niki-gor commented on source/get.js
> +function get(obj, attrs) {
_Стильно, модно, молодежно_ != читаемо.

"Стрелочки" выглядят уместно только как аргумент функции высшего порядка. В глобальной области видимости это не более, чем финт от пишущего, и боль для читающего

2023-02-13 16:56 UTC, AntonElagin commented on source/get.js
> +function get(obj, attrs) {
Достаточно большое количество моих коллег и я готовы с тобой поспорить. 

И все же я настаиваю на функциях стрелках)

2023-02-13 17:17 UTC, AntonElagin requested changes
Возможно возникло какое-то недопонимания условия задачки, глянь еще разок.

PS Еще попрошу тебя не резолвить самому мои комменты, если несложно, я потом по ним проверяю и вспоминаю)

2023-02-13 17:17 UTC, AntonElagin commented on source/get.js
> +                .reduce((obj, attr) => obj === undefined ? obj : obj[attr], object);
а почему возвращаем obj, если свойство не нашли? Кажется, надо возврщать ```undefined``` в таком кейсе

2023-02-13 17:17 UTC, AntonElagin commented on tests/get.js
> +						get(objectInvalidType(), attrsInvalidType());
кажется, вот эти вызовы будут не для всех кейсов валидны ```objectInvalidType(), attrsInvalidType()```

2023-02-13 17:17 UTC, AntonElagin commented on tests/get.js
> +				assert.throws(
какой-то странный тест, хотелось бы более конкретные ошибки проверять, а не просто факт падения функции. + отдельным комментов указал, что тест будет падать сам по себе

2023-02-13 17:17 UTC, AntonElagin commented on tests/get.js
> +				assert.throws(
И необязательно проверять все комбинации всех типов, достаточно проверить все основные группы ошибок

2023-02-13 17:17 UTC, AntonElagin commented on tests/get.js
> +		assert.throws(
Нужно обрабатывать конкретные ошибки, а не просто падения. Пользователь функции должен понимать, почему она упала без знания реализации

2023-02-13 18:24 UTC, niki-gor commented on source/get.js
> +                .reduce((obj, attr) => obj === undefined ? obj : obj[attr], object);
>obj === undefined
>нужно вернуть не obj, а undefined

2023-02-13 18:51 UTC, niki-gor commented on source/get.js
> + * @returns {Object|undefined} - object that can be interpreted as obj['attr1']['attr2']['attrN']
Не нашел места для комментариев в первом комменте, напишу здесь.
>Давай проверим еще разок код. Нужно стараться оформлять код в едином стиле
Я в повторил тот же кодстайл, который был в примере тестирования дефолтного max. Если у меня проблемы со стилем, то и в выданном примере тоже.

2023-02-13 20:27 UTC, AntonElagin commented on source/get.js
> + * @returns {Object|undefined} - object that can be interpreted as obj['attr1']['attr2']['attrN']
any - это тип TypeScript-а, * - принятый вариант обозначения любого типа в - jsDoc. JSDoc появился сильно раньше чем TypeScript, поэтому и может возникать путаница в современных средах. Про TypeScript вам расскажу ближе к концу семестра)

2023-02-13 20:29 UTC, AntonElagin commented on source/get.js
> + * @returns {Object|undefined} - object that can be interpreted as obj['attr1']['attr2']['attrN']
Не смотри на стиль оформления тестов как на эталон.) От вас требуется написать свой код в самом популярном и современном виде для знакомства с языком. В тестах нужно сохранить стиль тестов. Да, возможно звучит странно, но так исторически сложилось + данным заданиям уже достаточно много лет, поэтому некоторые вещи слегка устарели)

2023-02-13 20:33 UTC, AntonElagin commented on source/get.js
> +                .reduce((obj, attr) => obj === undefined ? obj : obj[attr], object);
Ок, не подумал, хотя кмк лучше воспользоваться [опциональной цепочкой](https://learn.javascript.ru/optional-chaining). Тут я настаивать не буду, но штука полезная

2023-02-14 07:48 UTC, AntonElagin requested changes

2023-02-14 07:48 UTC, AntonElagin commented on source/get.js
> +    if (!attrs.startsWith('.')) {
Мы все еще никак не обрабатываем ошибки с неверными типами

2023-02-14 07:48 UTC, AntonElagin commented on source/get.js
> +}
После стрелочных функций принято ставить ```;``` + проверь наличие  ```;``` и в других местах

2023-02-14 14:09 UTC, niki-gor commented on source/get.js
> + * @returns {Object|undefined} - object that can be interpreted as obj['attr1']['attr2']['attrN']
Спасибо за развернутый ответ)

2023-02-14 14:09 UTC, niki-gor commented on source/get.js
> + * @returns {Object|undefined} - object that can be interpreted as obj['attr1']['attr2']['attrN']
Но я нигде не могу найти место, где кодстайл отличается от основного (4 таба, camelCase) — если ты можешь показать место несоответствия, буду признателен)

2023-02-14 14:27 UTC, niki-gor commented on source/get.js
> +				.split('.')
Поехало...
Это надо фиксить? Почти все, кроме гитхаба, используют таб в 4 пробела

2023-02-14 14:51 UTC, AntonElagin requested changes

2023-02-14 14:51 UTC, AntonElagin commented on source/get.js
> +    // обращение к строке тоже валидно (можно обратиться по индексу)
И еще лучше убрать все комменты кроме jsDoc. Нам нужен самодокументируемый код)

2023-02-14 14:51 UTC, AntonElagin commented on source/get.js
> +    if (typeof object !== 'object' && typeof object !== 'string') {
Вот ты и попался на исторический баг js. Если кратко ```typeof null === 'object'```

Подробнее тут: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/typeof#null

2023-02-14 14:51 UTC, AntonElagin commented on source/get.js
> + * @returns {Object|undefined} - object that can be interpreted as obj['attr1']['attr2']['attrN']
Был косяк с кавычками, но кажется ты его исправил) Сейчас вроде ничего не нашел

2023-02-14 14:51 UTC, AntonElagin commented on source/get.js
> +		throw new Error("attrs must start with '.'");
Закрыл тред и нашел косяки) Кавычки везде должны быть одинаковыми. Чаще всего стайл гайды предлагают использовать одинарные```'```

2023-02-14 14:51 UTC, AntonElagin commented on source/get.js
> +				.split('.')
Это спорный вопрос. Обычно я такое линтером правлю.

Я бы написал примерно так: 
```
return arr
          .methodOne(callback)
          .methodN(callback);
```

2023-02-14 15:09 UTC, niki-gor commented on source/get.js
> +		throw new Error("attrs must start with '.'");
Я использовал в строке сообщения одинарные кавычки, поэтому применил двойные снаружи. Делать экранизацию одинарных (когда можно просто использовать двойные снаружи) кажется оверхедом

2023-02-14 19:59 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-14 19:59 UTC, DPeshkoff commented on source/get.js
> +    if (typeof attrs !== 'string') {
Кажется, проверка не полная)

![изображение](https://user-images.githubusercontent.com/31134795/218846785-283bd2ae-788d-4d11-b204-5f9d8a46ea89.png)

2023-02-14 19:59 UTC, DPeshkoff commented on source/get.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе

2023-02-14 19:59 UTC, DPeshkoff commented on source/get.js
> +    if (typeof object !== 'object' || object === null) {
Можно [просто](https://developer.mozilla.org/en-US/docs/Glossary/Truthy)....

2023-02-14 19:59 UTC, DPeshkoff commented on tests/get.js
> +		for (let invalidAttr of invalidAttrs) {
Гоу заюзаем методы массивов)

2023-02-14 19:59 UTC, DPeshkoff commented on source/get.js
> +        throw new TypeError('typeof object (param) should be "object"');
Кажется, такого быть не должно)

![изображение](https://user-images.githubusercontent.com/31134795/218847934-2d39233c-45ad-4449-9108-aab228f251a3.png)

2023-02-16 10:09 UTC, DPeshkoff commented on source/get.js
> +    if (!(object instanceof Object && [Array, Object].includes(object.constructor))) {
На массив лучше проверять [по-другому ](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array)

2023-02-17 10:31 UTC, DPeshkoff approved these changes

2023-02-17 10:31 UTC, closed without merging