Variant 10
frontend-park-mail-ru/homework_2023_1 pull request #4
Opened 2023-02-08 12:47 UTC by dyndtikj

Власов Максим

2023-02-09 18:05 UTC, rflban requested changes

2023-02-09 18:05 UTC, rflban commented on source/letters.js
> +    return str.split('').filter((element, idx, array) => {
Напиши пожалуйста, какая асимптотическая сложность у твоего решения и можно ли сделать лучше?

2023-02-09 18:06 UTC, rflban commented
Привет! Я буду проверять твоё ДЗ0. Ты хорошо справился с первой итерацией, давай займемся улучшениями!

2023-02-12 11:15 UTC, DPeshkoff requested changes
Привет! Есть пара вопросов по ДЗ:

2023-02-12 11:15 UTC, DPeshkoff commented on index.html
> -<script src="source/max.js"></script>
Оригинальные файлы можно было бы и не убирать) 

2023-02-12 11:15 UTC, DPeshkoff commented on source/letters.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-12 11:15 UTC, DPeshkoff commented on source/letters.js
> +function letters(str, flag) {
Кажется, здесь лучше использовать [функцию-стрелку](https://learn.javascript.ru/arrow-functions-basics)

2023-02-12 12:14 UTC, dyndtikj commented on source/letters.js
> +'use strict';
Строка обозначает использование строгого режима, в таком режиме интерпретатор явно выбрасывает ошибки на действия, которые раньше прорускал - небезопасные конструкции, предотвращает использование ключевых слов как названий
Запрещено в строгом режиме:
-Использовать переменные без объявления
-Менять поля, если это нельзя
-this не ссылается на глобальный объект

Использовал в коде , тк это считается хорошим тоном и заранее позволяет предотвратить некоторые ошибки

2023-02-12 12:22 UTC, dyndtikj commented on index.html
> -<script src="source/max.js"></script>
Вернул обратно)

2023-02-12 12:22 UTC, dyndtikj commented on source/letters.js
> +function letters(str, flag) {
Изменил на стрелочную функцию

2023-02-12 12:25 UTC, DPeshkoff requested changes

2023-02-12 12:25 UTC, DPeshkoff commented on index.html
> +<script src="tests/max.js"></script>
Тут какой-то лишний diff с main-веткой - лишний diff сильно мешает при ревью, если ПР большой, поэтому давай вставим на оригинальное место, чтобы ничего не менялось)

2023-02-12 12:36 UTC, DPeshkoff approved these changes

2023-02-12 12:36 UTC, closed without merging