Димитриев Евгений вариант 6 группа WEB-21
frontend-park-mail-ru/homework_2023_1 pull request #40
Opened 2023-02-10 21:18 UTC by UjinIaly

Димитриев Евгений вариант 6 группа WEB-21

2023-02-12 10:51 UTC, code1cult commented on .idea/homework_2023_1.iml
> +<?xml version="1.0" encoding="UTF-8"?>
А почему .idea хранится в репозитории? Логично его скрыть в .gitignore

2023-02-12 10:59 UTC, code1cult commented on source/tree.js
> +
Давай добавим JsDoc

2023-02-12 11:02 UTC, code1cult commented
На данный момент отсутствует код стайл давай попробуем это исправить [Отсутствие код-стайла](https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda)

2023-02-12 11:13 UTC, code1cult commented on source/tree.js
> +    for(let  i = 0;i<count;++i) yield symbol;
Давай будем придерживаться код стайла 
https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2023-02-12 11:14 UTC, code1cult commented on source/tree.js
> +    if((isNaN(height))||n===null||(!Number.isInteger(height))||(!isFinite(height))){
Скажи пожалуйста почему ты решил сделать именно такое решение?

2023-02-14 15:19 UTC, UjinIaly commented on .idea/homework_2023_1.iml
> +<?xml version="1.0" encoding="UTF-8"?>
убрал

2023-02-14 15:19 UTC, UjinIaly commented on source/tree.js
> +
проверьте, вроде сделал

2023-02-14 15:20 UTC, UjinIaly commented on source/tree.js
> +    for(let  i = 0;i<count;++i) yield symbol;
попробовал автоматическое форматирование в webstrom, так подойдёт?

2023-02-14 15:28 UTC, UjinIaly commented on source/tree.js
> +    if((isNaN(height))||n===null||(!Number.isInteger(height))||(!isFinite(height))){
если вы про длинную строчку с проверками, то когда я тестил код, то подумал, что будет круто добавить проверку(привычка с плюсов). А если в целом про решение, то я пытался найти как вывести текст и нашёл только alert и document.write(). А потом наткнулся на статью где используется генератор и yield, попробовал сделать по ней и получилось.

2023-02-14 17:24 UTC, code1cult commented on source/tree.js
> +
Женя посмотри внимательно нет описание входных данных, а так же описание что за все отвечает

2023-02-14 17:24 UTC, code1cult commented on source/tree.js
> +    for(let  i = 0;i<count;++i) yield symbol;
использовать [eslint](https://eslint.org/)

2023-02-14 17:24 UTC, code1cult commented on source/tree.js
> +    if((isNaN(height))||n===null||(!Number.isInteger(height))||(!isFinite(height))){
Предлагаю разбить логику, в данный момент код тяжело будет поддерживать

2023-02-14 17:43 UTC, UjinIaly commented on source/tree.js
> +    for(let  i = 0;i<count;++i) yield symbol;
вроде бы по нему всё хорошо

2023-02-14 17:44 UTC, UjinIaly commented on source/tree.js
> +    if((isNaN(height))||n===null||(!Number.isInteger(height))||(!isFinite(height))){
что именно вы хотите, чтобы я сделал

2023-02-14 18:02 UTC, UjinIaly commented on source/tree.js
> +
а теперь?

2023-02-15 14:58 UTC, code1cult commented on source/tree.js
> +    if((isNaN(height))||n===null||(!Number.isInteger(height))||(!isFinite(height))){
На данный момент код не читаем я бы попросил разбить на модули

2023-02-15 14:59 UTC, code1cult commented
Женя напиши плиз тесты для кода

2023-02-15 14:59 UTC, code1cult commented
А так для случаев когда на вход мы подаем не валидные данные

2023-02-15 15:00 UTC, code1cult commented on source/tree.js
> +    for(let  i = 0;i<count;++i) yield symbol;
Посмотри внимательно пожалуйста https://learn.javascript.ru/coding-style#rukovodstva-po-stilyu-koda

2023-02-15 15:01 UTC, code1cult commented on source/tree.js
> +    for (let i = 1; i < height; i++)
Скажи чем отличается var let const?

2023-02-15 21:22 UTC, UjinIaly commented on source/tree.js
> +    for (let i = 1; i < height; i++)
var может быть глобальной, а let и const существует только в пределах {}.

2023-02-15 21:24 UTC, UjinIaly commented on source/tree.js
> +    for (let i = 1; i < height; i++)
const задаётся при объявлении и потом её нельзя менять, а let и var можно.
И ещё var можно переопределить, а let нельзя, const вообще можно определить только при объявлении.

2023-02-15 21:31 UTC, UjinIaly commented on source/tree.js
> +    if((isNaN(height))||n===null||(!Number.isInteger(height))||(!isFinite(height))){
так подойдёт?

2023-02-15 21:31 UTC, UjinIaly commented on source/tree.js
> +    for(let  i = 0;i<count;++i) yield symbol;
если не так, то я не понимаю как...

2023-02-16 10:15 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-16 10:15 UTC, DPeshkoff commented on source/tree.js
> +    }
Давай объединим все эти проверки

Чем отличаются между собой `Number.isNaN()` и `isNaN()` ? Почему выбрал именно второе? Аналогично с isFinite

2023-02-16 10:15 UTC, DPeshkoff commented on source/tree.js
> +const tree = (n) => {
JSDoc бы)

2023-02-16 10:15 UTC, DPeshkoff commented on source/tree.js
> +}
круто, что сделал генератор!

Давай добавим jsdoc ко всем функциям

2023-02-16 10:15 UTC, DPeshkoff commented on source/tree.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-16 10:15 UTC, DPeshkoff commented on source/tree.js
> +const tree = (n) => {
А чем стрелочные функции отличаются от обычных?

2023-02-16 14:11 UTC, UjinIaly commented on source/tree.js
> +    }
.isNaN проверяет равен ли аргумент NaN. А isNaN() проверяет не число ли это. А мне как раз нужно проверить является ли аргумент числом или нет. А с .isFinite и isFinite() можно было использовать и то и то, но isFinite() преобразует число и проверяет, и если нельзя преобразовать выкидывает false, а .isFinite только проверяет число ли это.

2023-02-16 14:11 UTC, UjinIaly commented on source/tree.js
> +'use strict';
Она нужна, чтобы перейти в строгий режим. Так можно избежать ненужных ошибок, в обычном режиме может быть так, что интерпретатор не скажет, что где-то есть ошибка

2023-02-16 14:11 UTC, UjinIaly commented on source/tree.js
> +const tree = (n) => {
В обычных фукнциях this может вести себя по-разному, а в стрелочных это всегда родительская функция.
В обычных нужно явно добавлять return, а в стрелочных можно не добавлять, если там 1 выражение.
И в стрелочных нет своего arguments

2023-02-16 14:14 UTC, UjinIaly commented on source/tree.js
> +const tree = (n) => {
Так нормально?

2023-02-16 19:35 UTC, DPeshkoff approved these changes

2023-02-16 19:36 UTC, closed without merging