Булгаков Иван, Вариант 7
frontend-park-mail-ru/homework_2023_1 pull request #41
Opened 2023-02-11 17:37 UTC by ivan12093

2023-02-12 11:47 UTC, Nikita-Boyarskikh requested changes
Привет, добро пожаловать на курс фронтенда!
Меня зовут Никита, я буду проверять твое дз0

Здорово, что ты изучил встроенные возможности языка, очень метко использовал метод flat. Если бы это было не учебное ДЗ, а код для продакшена, это был бы наилучший вариант. А так как цель этого ДЗ, научиться писать на JS, давай представим, что у массива нет метода flat и реализуем аналогичный своими силами. Все остальные средства языка и методы доступны

PS По любым вопросам можешь писать тут или мне в телегу [@Nikita_Boyarskikh](https://t.me/Nikita_Boyarskikh)

2023-02-12 11:47 UTC, Nikita-Boyarskikh commented on tests/plain.js
> +		assert.throws(() => plain(NaN), new TypeError('arr must be an array!'), exception);
Кажется, в следующих трёх тестах ты не совсем правильно используешь `assert.throws` и передаёшь лишний аргумент
Если использовать `assert.throws` с тремя аргументами, последний будет использоваться, как комментарий, где можно человеческим языком написать, что проверяет данный assert, а ты передаёшь туда экземпляр исключения, что не очень человеко-читаемо :)
Ссылка на доку на всякий: https://api.qunitjs.com/assert/throws/

2023-02-12 12:00 UTC, ivan12093 commented
Заменил реализацию функции `plain`, исправил ошибки в описании негативных кейсов.

2023-02-13 09:20 UTC, Nikita-Boyarskikh requested changes
Идея с `while` классная, без рекурсии обошлись 👍 
Остался один небольшой момент, который ещё можно улучшить

2023-02-13 09:20 UTC, Nikita-Boyarskikh commented on source/plain.js
> +        const popped = copy.pop();
В массивы можно добавлять и доставать элементы и с начала: методы [`shift`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift) и [`unshift`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift)

2023-02-13 09:20 UTC, Nikita-Boyarskikh commented on source/plain.js
> +        const popped = copy.pop();
Можно, используя эти методы, сразу собрать массив в нужном порядке без необходимости дополнительно переворачивать его в конце

2023-02-13 11:23 UTC, ivan12093 commented on source/plain.js
> +        const popped = copy.pop();
Специально обошел стороной эти методы, так как их алгоритмическая сложность О(n). Гораздо эффективнее использовать методы `push` и `pop` с сложностью O(1) (в случае `push` амортизированной) и один раз перевернуть массив в конце.

2023-02-13 11:26 UTC, Nikita-Boyarskikh approved these changes

2023-02-13 12:26 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр! 

Работа хорошая, но есть пара вопросов)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 12:26 UTC, DPeshkoff commented on source/plain.js
> +const plain = arr => {
Лучше оборачивать в () - так проще добавлять новые аргументы)

2023-02-13 12:26 UTC, DPeshkoff commented on source/plain.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-13 23:49 UTC, ivan12093 commented on source/plain.js
> +const plain = arr => {
Исправил

2023-02-13 23:54 UTC, ivan12093 commented on source/plain.js
> +'use strict';
Данная директива включает строгий режим. При его включении интерпретатор начнет выбрасывать ошибки на некоторые небезопасные конструкции, отключает функции, которые запутывают код и предотвращает использование слов, которые могут в качестве ключевых в будущем. Таким образом, строгий режим позволяет писать более безопасный код.

2023-02-14 09:44 UTC, DPeshkoff approved these changes

2023-02-14 09:45 UTC, closed without merging