Чичикин Тимофей Variant 4
frontend-park-mail-ru/homework_2023_1 pull request #42
Opened 2023-02-13 05:22 UTC by ned8800

2023-02-13 10:44 UTC, inerc commented
Привет, добро пожаловать на курс фронтенда!
Меня зовут Женя, я буду проверять твое дз0

Здорово, что у тебя получилось реализовать функцию чтобы прошли тесты. А теперь предлагаю сделать красиво, и используя встроенные возможности языка Js.

Также я бы очень хотел увидеть тесты написанные тобой на эту функцию.
Подробнее по коду написать в ревью.

PS По любым вопросам можешь писать тут или мне в телегу [@inerc](https://t.me/inerc)

2023-02-13 10:54 UTC, inerc requested changes

2023-02-13 10:54 UTC, inerc commented on source/inverse.js
> +const inverse = (given_array, position = 0) => {
Давай сделаем JsDoc

https://jsdoc.app/

2023-02-13 10:54 UTC, inerc commented on source/inverse.js
> +    if ((!Array.isArray(given_array)) || (!Number.isInteger(position))) {
Давай декомпозируем обработку ошибок, чтобы разработчик использовавший твою функцию понимал какой именно аргумент он указал не верно, и что от него ожидается.

2023-02-13 16:39 UTC, ned8800 commented
добавил тесты и заменил реализацию на встроенные функции. Сейчас  перемещусь на линукс и доделаю JsDoc

2023-02-13 17:51 UTC, ned8800 commented
Сделал JsDoc

2023-02-13 19:54 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 19:54 UTC, DPeshkoff commented on source/inverse.js
> +        throw new Error("First parameter is not an array!")
Лучше вот [это](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

А еще традиционно принято использовать одиночные кавычки)

2023-02-13 19:54 UTC, DPeshkoff commented on source/inverse.js
> +    return temp_given_array
Не пренебрегай ;

Здесь и на 13-17

Может привести вот к такому:

![изображение](https://user-images.githubusercontent.com/31134795/218560753-50c6b58e-e3ca-4dd4-83ba-240852e54be1.png)

2023-02-13 19:54 UTC, DPeshkoff commented on source/inverse_old.js
> +// ЭТО СТАРАЯ РЕАЛИЗАЦИЯ БЕЗ ИСПОЛЬЗОВАНИЯ ВСТРОЕННЫХ ФУНКЦИЙ JS
А зачем это в ПРе?)

2023-02-13 19:54 UTC, DPeshkoff commented on tests/inverse_my_tests.js
> +        assert.deepEqual(inverse([], -5), []);
отступ поехал

2023-02-13 19:54 UTC, DPeshkoff commented on tests/inverse_my_tests.js
> +		}, Error,"First parameter is not an array!");
и тут поехало

2023-02-13 19:54 UTC, DPeshkoff commented on source/inverse.js
> +function inverse (given_array, position = 0) {
Какие еще есть способы задать функцию?

2023-02-13 19:55 UTC, DPeshkoff commented on source/inverse.js
> +/**
Что ты знаешь про режимы выполнения кода?

2023-02-13 20:00 UTC, ned8800 commented on source/inverse_old.js
> +// ЭТО СТАРАЯ РЕАЛИЗАЦИЯ БЕЗ ИСПОЛЬЗОВАНИЯ ВСТРОЕННЫХ ФУНКЦИЙ JS
Евгений сказал оставить для случая, если понадобится другому преподавателю

2023-02-13 20:17 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
можно "стрелочно" задать:
const inverse = (given_array, position = 0) => {

(given_array, position = 0) -- это props

2023-02-13 20:46 UTC, ned8800 commented on source/inverse.js
> +/**
Есть обычный режим, на котором работают старые браузеры и строгий, введенный с ES5
я знаю, что если добавить вызов директивы 'use strict' в начало, то включится строгий режим.

2023-02-13 20:48 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
const, потому что функция должна быть неизменяемой

2023-02-14 10:00 UTC, DPeshkoff commented on source/inverse.js
> +/**
А почему не стал включать строгий режим?

2023-02-14 11:09 UTC, ned8800 commented on source/inverse.js
> +/**
Я исправил и включил, перепроверьте

2023-02-14 11:10 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
Обычная функция глобальна

2023-02-14 11:15 UTC, ned8800 commented on source/inverse.js
> +/**
Не знаю почему, но в "conversation" гитхаб не показывает изменения сейчас, они есть в "Files changed"

2023-02-14 11:19 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
А стрелочные функции можно динамически создать в любом месте программы, как переменную. Они хороши для коротких действий

2023-02-14 19:39 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
Я переделал на стрелочную

2023-02-14 19:40 UTC, ned8800 commented on tests/inverse_my_tests.js
> +        assert.deepEqual(inverse([], -5), []);
Поправил, изменения в "Files changed"

2023-02-14 19:40 UTC, ned8800 commented on tests/inverse_my_tests.js
> +		}, Error,"First parameter is not an array!");
Поправил, изменения в "Files changed"

2023-02-14 19:41 UTC, ned8800 commented on tests/inverse_my_tests.js
> +		}, Error,"First parameter is not an array!");
Я часть на windows делал, часть на linux, возможно это была проблема различия отступов в разных ОС

2023-02-14 19:43 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
А еще компилятор запоминает реализацию функции через function, поэтому простые функции предпочтительнее писать через =>

2023-02-14 20:05 UTC, DPeshkoff requested changes

2023-02-14 20:05 UTC, DPeshkoff commented on source/inverse_old.js
> +// ЭТО СТАРАЯ РЕАЛИЗАЦИЯ БЕЗ ИСПОЛЬЗОВАНИЯ ВСТРОЕННЫХ ФУНКЦИЙ JS
Можно выпиливать, разрешаю)

2023-02-14 20:05 UTC, DPeshkoff commented on source/inverse.js
> +    let temp_given_array = [...given_array];
[тык](https://t.me/makingweb/148)

2023-02-14 20:16 UTC, ned8800 commented
Выпилил старую реализацию

2023-02-14 20:17 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
а стрелочная функция еще не создает свой контекст исполнения, то есть можно еще на этом соптимизировать

2023-02-14 20:25 UTC, ned8800 commented on source/inverse.js
> +function inverse (given_array, position = 0) {
и стрелочная функция объект функции не может создать

2023-02-14 21:00 UTC, DPeshkoff approved these changes

2023-02-14 21:00 UTC, closed without merging