Верин Дмитрий вариант 8 WEB-21
frontend-park-mail-ru/homework_2023_1 pull request #43
Opened 2023-02-14 17:19 UTC by Carthago1

2023-02-15 14:29 UTC, SergTyapkin requested changes

2023-02-15 20:33 UTC, SergTyapkin requested changes

2023-02-15 20:33 UTC, SergTyapkin commented on source/sort.js
> +    words.forEach((word, index) =>{
Забыл пробел после стрелки

2023-02-15 20:33 UTC, SergTyapkin commented on tests/myTestSort.js
> +            sort(1);
А почему тут используешь обычные функции через `function`, а не стрелочные? Объясни

2023-02-15 20:33 UTC, SergTyapkin commented
Всё круто. Пробел, пару слов, и я ставлю аппрув)

2023-02-15 20:39 UTC, Carthago1 commented on tests/myTestSort.js
> +            sort(1);
Чтобы все тесты были написаны в одном стиле, как с функцией max (на самом деле я не подумал, а просто сделал по примеру тех тестов)

2023-02-15 20:58 UTC, SergTyapkin commented on tests/myTestSort.js
> +            sort(1);
Я хотел услышать мысли в другом русле. ("потому что так было сделано" - не катит)))
Чем отличаются обычные функции и стрелочные?

2023-02-15 21:18 UTC, Carthago1 commented on tests/myTestSort.js
> +            sort(1);
В стрелочных функциях можно не использовать return для возврата значения, если тело состоит из 1 инструкции (нужно опустить фигурные скобки). Стрелочные функции не имеют собственного контекста выполнения и наследуют this и arguments от родительской функции

2023-02-15 21:37 UTC, SergTyapkin commented on tests/myTestSort.js
> +            sort(1);
Вооот. Как раз мы используем тут обычные функции для выполнения тестов в "более изолированной" среде с собственным контекстом

2023-02-15 21:38 UTC, SergTyapkin approved these changes

2023-02-16 10:18 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-16 10:18 UTC, DPeshkoff commented on index.html
> -<script src="tests/max.js"></script>
Пример можно не убирать - давай оставим, как было)

2023-02-16 10:18 UTC, DPeshkoff commented on source/sort.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-16 10:18 UTC, DPeshkoff commented on source/sort.js
> +    if (typeof str !== 'string') {
Кажется, проверка не полная

![изображение](https://user-images.githubusercontent.com/31134795/219337054-93abdaae-3c46-445e-9154-cf3b1ff3a683.png)

2023-02-16 14:05 UTC, Carthago1 commented on source/sort.js
> +'use strict';
Включение строго режима для отлова некоторых ошибок и более безопасного выполнения

2023-02-16 14:05 UTC, Carthago1 commented on source/sort.js
> +    if (typeof str !== 'string') {
Добавил еще одно условие

2023-02-16 19:36 UTC, DPeshkoff approved these changes

2023-02-16 19:36 UTC, closed without merging