Долгих Артём Вариант 1
frontend-park-mail-ru/homework_2023_1 pull request #44
Opened 2023-02-14 20:08 UTC by Hareshutit

2023-02-15 10:15 UTC, SergTyapkin commented
Привет!
Во-первых поздравляю с поступлением на второй семестр! Здесь ~~нам~~ вам предстоит ещё больше ~~боли~~ веселья)

Я - Сергей, один из менторов этого семестра по курсу фронтенда, и буду проверять твоё ДЗ0. Сразу оговорюсь, что буду сильно докапываться до [стиля кода](https://learn.javascript.ru/coding-style), до стрелочных функций и до `const` вместо `let`, где это возможно.

В общем то всё, желаю удачи, и давай смотреть на твои ошибки в этом дз)

2023-02-15 15:32 UTC, SergTyapkin requested changes

2023-02-15 15:32 UTC, SergTyapkin commented on source/zip.js
> +            throw new TypeError('Не объект или null', 'planify.js');
Откуда взялось `plainify.js` и зачем оно нужно?

2023-02-15 15:32 UTC, SergTyapkin commented on source/zip.js
> +const zip = (...objects) => {
А чем вообще отличается стрелочная функция от обычной?

2023-02-15 15:32 UTC, SergTyapkin commented on tests/zip.js
> +	QUnit.test('Функция не принимает неправомерные входные данные', function (assert) {
"Неправомерные" - не совсем то слово, тебе не кажется?)

2023-02-15 15:32 UTC, SergTyapkin commented on tests/zip.js
> +//Хотел уточнить, а что делать с тестом на неправильные входные данные, так как задача с входным массивом объектов, то получается он выйдет плюс минус таким же с использованием assert.throws?
Получается, так.

_Такие сообщения можно писать в комментариях к ПР_

2023-02-15 15:32 UTC, SergTyapkin commented on source/zip.js
> +    const uni_object = {};
В JS принят CamelCase стиль названия переменных

2023-02-15 15:32 UTC, SergTyapkin commented on tests/zip.js
> +//Хотел уточнить, а что делать с тестом на неправильные входные данные, так как задача с входным массивом объектов, то получается он выйдет плюс минус таким же с использованием assert.throws?
19-ая строка в этом файле - дублированный тест

2023-02-15 15:32 UTC, SergTyapkin commented on tests/zip.js
> +				zip(null);
Давай вызовем ещё с undefined, NaN, и вообще без аргументов

2023-02-15 15:32 UTC, SergTyapkin commented on source/zip.js
> +}
Нужна пустая строка в конце файла. Ну так принято

2023-02-15 15:32 UTC, SergTyapkin commented on source/zip.js
> +        })
;

2023-02-15 15:32 UTC, SergTyapkin commented on source/zip.js
> +    }
Не
}
)

А
});

2023-02-15 15:32 UTC, SergTyapkin commented on tests/zip.js
> +//Хотел уточнить, а что делать с тестом на неправильные входные данные, так как задача с входным массивом объектов, то получается он выйдет плюс минус таким же с использованием assert.throws?
Пустая строка в конце

2023-02-15 15:32 UTC, SergTyapkin commented
В целом круто, но нужны исправления по мелочам

2023-02-15 16:45 UTC, Hareshutit commented on tests/zip.js
> +//Хотел уточнить, а что делать с тестом на неправильные входные данные, так как задача с входным массивом объектов, то получается он выйдет плюс минус таким же с использованием assert.throws?
Поправил

2023-02-15 16:45 UTC, Hareshutit commented on source/zip.js
> +    }
Поправил

2023-02-15 16:45 UTC, Hareshutit commented on source/zip.js
> +        })
Поправил

2023-02-15 16:46 UTC, Hareshutit commented on tests/zip.js
> +				zip(null);
Реализовал

2023-02-15 16:46 UTC, Hareshutit commented on tests/zip.js
> +//Хотел уточнить, а что делать с тестом на неправильные входные данные, так как задача с входным массивом объектов, то получается он выйдет плюс минус таким же с использованием assert.throws?
Ой забыл удалить)

2023-02-15 16:46 UTC, Hareshutit commented on source/zip.js
> +    const uni_object = {};
Поправил

2023-02-15 16:47 UTC, Hareshutit commented on tests/zip.js
> +//Хотел уточнить, а что делать с тестом на неправильные входные данные, так как задача с входным массивом объектов, то получается он выйдет плюс минус таким же с использованием assert.throws?
Так было в базовых тестах, но поправил)

2023-02-15 16:47 UTC, Hareshutit commented on tests/zip.js
> +	QUnit.test('Функция не принимает неправомерные входные данные', function (assert) {
Поправил

2023-02-15 16:48 UTC, Hareshutit commented on source/zip.js
> +            throw new TypeError('Не объект или null', 'planify.js');
Это указание на файл в котором возникла ошибка, поправил

2023-02-15 16:48 UTC, Hareshutit commented on source/zip.js
> + * @returns {Object} uni_object возращает обьединенный объект
Поправил

2023-02-15 16:49 UTC, Hareshutit commented on source/zip.js
> +const zip = (...objects) => {
Поведение this внутри стрелочной функции отличается от поведения this внутри обычной функции. Не имеет значения как она была вызвана, значение this внутри стрелочной функции всегда эквивалентно значения this внешней функции. Более компактный синтаксис. Как следствие того, что стрелочные функции не имеют собственного this они не могут быть использованы для создания объектов.

2023-02-17 11:45 UTC, SergTyapkin requested changes

2023-02-17 11:45 UTC, SergTyapkin commented on tests/zip.js
> +	QUnit.test('Функция работает со свойствами объекта на utf-8', function (assert) {
Смотри, у тебя тут функция обычная, а в тестах стрелочные. Негоже. 
Либо объясни, почему так и должно быть - все имеет место быть

2023-02-17 11:45 UTC, SergTyapkin commented on tests/zip.js
> +			}, RangeError
Не RangeError

2023-02-17 14:17 UTC, Hareshutit commented on tests/zip.js
> +			}, RangeError
Поправил

2023-02-17 16:29 UTC, Hareshutit commented on tests/zip.js
> +	QUnit.test('Функция работает со свойствами объекта на utf-8', function (assert) {
Поправил

2023-02-17 16:59 UTC, SergTyapkin approved these changes

2023-02-17 20:26 UTC, DPeshkoff requested changes

2023-02-17 20:26 UTC, DPeshkoff commented on source/zip.js
> +'use strict';
Можешь, пожалуйста, расписать, что делает эта строчка?

2023-02-17 20:29 UTC, Hareshutit commented on source/zip.js
> +'use strict';
Директива: "use strict" или 'use strict'. Когда она находится в начале скрипта, весь сценарий работает в «современном» режиме.

2023-02-17 20:30 UTC, closed without merging