Данилин Максим ДЗ№0 Вариант 16
frontend-park-mail-ru/homework_2023_1 pull request #45
Opened 2023-02-23 16:45 UTC by MaksimDanilin

2023-02-25 12:01 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-25 12:01 UTC, DPeshkoff commented on source/format.js
> +	for (let i = 0; i < numbers.length; i++) {
Давай используем перебирающие методы массива?

2023-02-25 12:01 UTC, DPeshkoff commented on source/format.js
> +}
\n в конце файла

2023-02-27 18:25 UTC, MaksimDanilin commented on source/format.js
> +"use strict";
Активирует "современный" режим для более безопасного написания кода и отслеживания некоторых ошибок, которые могли встречаться в более старых версиях языка.

2023-02-27 22:19 UTC, DPeshkoff approved these changes

2023-02-27 22:19 UTC, closed without merging