Анохина Карина, вариант 3
frontend-park-mail-ru/homework_2023_1 pull request #5
Opened 2023-02-08 12:51 UTC by ArKarina

2023-02-08 12:52 UTC, ArKarina commented
Анохина Карина, вариант 3

2023-02-09 19:22 UTC, rflban requested changes

2023-02-09 19:22 UTC, rflban commented on source/roman.js
> +    if (typeof input === 'string' || input instanceof String) {
Хорошая проверка! Можешь объяснить почему именно так?

2023-02-09 19:22 UTC, rflban commented on source/roman.js
> +        const romanSymbols = /^[MDCLXVI]*$/;
Тут не лучшее место для регулярки, подумай пожалуйста почему и где лучше ее объявлять

2023-02-09 19:22 UTC, rflban commented on source/roman.js
> +        return romanSymbols.test(input.toUpperCase());
Можно дописать регулярку так, чтобы toUpperCase было не нужно

2023-02-09 19:22 UTC, rflban commented on source/roman.js
> +const isRoman = input => {
https://learn.javascript.ru/coding-style
Давай придерживаться этого стиля написания кода

2023-02-09 19:22 UTC, rflban commented on source/roman.js
> +    while (num > 0) {
Используй, пожалуйста, встроенные методы языка вместо циклов, они сужают семантику и упрощают чтение кода

2023-02-09 19:22 UTC, rflban commented on source/roman.js
> +const roman = input => {
Давай добавим jsdoc

2023-02-09 19:22 UTC, rflban commented
Привет! Я буду проверять твоё ДЗ0! Хорошая первая попытка, давай поработаем над улучшениями

2023-02-10 11:23 UTC, ArKarina commented on source/roman.js
> +    if (typeof input === 'string' || input instanceof String) {
Если использовать только typeof, то он вернет object для строк, созданных с помощью new String(). Оператор instanceof решает эту проблему.

2023-02-10 11:23 UTC, ArKarina commented
Добавила исправления

2023-02-11 10:40 UTC, rflban requested changes

2023-02-11 10:40 UTC, rflban commented on source/roman.js
> +const romanSymbols = /^[MDCLXVI]*$/i;
теперь хорошо! расскажи пожалуйста, почему регулярки лучше объявлять глобально?

2023-02-11 10:40 UTC, rflban commented on source/roman.js
> +    for (let item of Object.keys(ROMAN_ARAB)) {
тут тоже перепиши, пожалуйста, с использованием метода массива вместо цикла

2023-02-11 10:40 UTC, rflban commented on source/roman.js
> +        let i = Math.floor(num / ROMAN_ARAB[item]);
почему переменная объявлена через let? какие есть другие варианты и чем они будут отличаться?

2023-02-11 10:40 UTC, rflban commented on source/roman.js
> +    } else if (isRoman(input)) {
здесь точно нужен else?

2023-02-11 10:40 UTC, rflban commented on source/roman.js
> +        } else {
здесь точно нужен else?

2023-02-11 11:29 UTC, ArKarina commented on source/roman.js
> +        let i = Math.floor(num / ROMAN_ARAB[item]);
Переменная объявлена через let, потому что она изменяемая. Еще есть варианты объявить через var и const. const используется при объявлении константных переменных, а var является устаревшим вариантом.

2023-02-11 11:32 UTC, ArKarina commented on source/roman.js
> +const romanSymbols = /^[MDCLXVI]*$/i;
Потому что это константа, которая, если потребуется, может быть использована и в других частях кода.

2023-02-11 11:37 UTC, ArKarina commented on source/roman.js
> +    } else if (isRoman(input)) {
Да, потому что проверка на римское число нужна в любом случае. Иначе это придется вынести в отдельный if.

2023-02-11 12:10 UTC, ArKarina commented
Исправила замечания

2023-02-11 17:19 UTC, rflban requested changes

2023-02-11 17:19 UTC, rflban commented on source/roman.js
> +const romanSymbols = /^[MDCLXVI]*$/i;
это тоже, но в случае с регулярками есть еще одно но. при вычислении регулярного выражения, происходит его компиляция, если оставить его в теле функции, то на каждый вызов будет происходить по сути ненужная компиляция регулярки

2023-02-11 17:19 UTC, rflban commented on source/roman.js
> +    } else if (isRoman(input)) {
в данном случае
```js
if (/*...*/) {
  return
} else if (/*...*/) {
  return
}
```
```js
if (/*...*/) {
  return
} 
if (/*...*/) {
  return
}
```

будут делать одно и то же, но второй вариант читается лучше, так как все условия выровнены по вертикали

2023-02-11 17:19 UTC, rflban commented on source/roman.js
> +        let [roman, arab] = result;
так как result ты больше нигде не используешь, деструктуризацию лучше делать в списке параметров функции

2023-02-11 17:19 UTC, rflban commented on source/roman.js
> +        let i = Math.floor(num / ROMAN_ARAB[item]);
верно. по сути i ты не изменяешь в функции, тогда лучше объявлять ее как неизменяемую, чтобы застраховаться от непредвиденных изменений

2023-02-11 17:26 UTC, ArKarina commented
Изменила

2023-02-11 17:28 UTC, rflban commented on source/roman.js
> +console.log( roman('v') );
думаю, это уже не нужно

2023-02-11 17:28 UTC, ArKarina commented on source/roman.js
> +console.log( roman('v') );
Ой)

2023-02-12 11:21 UTC, DPeshkoff commented on source/roman.js
> +'use strict';
Привет и добро пожаловать на второй семестр! 

Работа хорошая, но можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовала в работе?

2023-02-12 11:44 UTC, ArKarina commented on source/roman.js
> +'use strict';
Use strict отвечает за строгий режим. Если эта директива указана в начале скрипта, весь сценарий работает в современном режиме, позволяющим использовать новые возможности языка. Если код состоит из классов и модулей, use strict можно не указывать, так как они автоматически включают строгий режим.

2023-02-12 11:56 UTC, DPeshkoff approved these changes

2023-02-12 11:56 UTC, closed without merging