Variant 1. Абдуллин Хасбулат
frontend-park-mail-ru/homework_2023_1 pull request #6
Opened 2023-02-08 13:33 UTC by Yakwilik

2023-02-09 18:29 UTC, rflban requested changes

2023-02-09 18:29 UTC, rflban commented on source/zip.js
> +function zip(...objects) {
Давай добавим jsdoc

2023-02-09 18:29 UTC, rflban commented on source/zip.js
> +	  for (let key in obj) {
а если на вход придут невалидные данные?

2023-02-09 18:29 UTC, rflban commented on source/zip.js
> +	for (let obj of objects) {
Давай вместо обычных циклов будем пользоваться встроенными в язык методами

2023-02-09 18:29 UTC, rflban commented on source/zip.js
> +  }
не хватает пустой строки в конце файла

2023-02-09 18:29 UTC, rflban commented on tests/zip.js
> +
мало тест кейсов, нужно покрыть все варианты использования

2023-02-11 10:41 UTC, rflban commented on tests/zip.js
> +});
в конце не хватает пустой строки

2023-02-14 14:56 UTC, rflban requested changes

2023-02-14 14:56 UTC, rflban commented on tests/zip.js
> -'use strict';
а точно это надо было удалять?

2023-02-14 14:56 UTC, rflban commented on source/zip.js
> +	let result = {};
отступ неправильный

2023-02-14 14:56 UTC, rflban commented on source/zip.js
> +	let result = {};
какие есть еще варианты объявить переменную кроме let?

2023-02-14 14:56 UTC, rflban commented on source/zip.js
> +    objects.forEach(obj => {
подумай как это можно записать лаконичнее с использованием другого метода массива

2023-02-14 14:56 UTC, rflban commented on source/zip.js
> +        Object.keys(obj).forEach((key) => {
объекты можно слить без явного цикла, есть подходящий синтаксис

2023-02-14 16:31 UTC, Yakwilik commented on tests/zip.js
> -'use strict';
случайно удалил, верну.

2023-02-14 16:32 UTC, Yakwilik commented on source/zip.js
> +	let result = {};
странно, локально отображается, как один таб, пофикшу, спасибо.

2023-02-14 16:35 UTC, Yakwilik commented on source/zip.js
> +    return value.toString() === '[object Object]';
Сейчас изменил метод проверки на сравнение прототипов.

2023-02-14 16:36 UTC, Yakwilik commented on source/zip.js
> +	let result = {};
Есть var и конст, но var лучше не использовать, тк это создает глобальную переменную.

2023-02-14 16:43 UTC, Yakwilik commented on source/zip.js
> +        Object.keys(obj).forEach((key) => {
Хорошо, сейчас сделаю и запушу, думал явный цикл более понятен.

2023-02-14 16:47 UTC, Yakwilik commented
Поправил по замечаниям.

2023-02-14 16:51 UTC, rflban commented on source/zip.js
> +    return value.toString() === '[object Object]';
тоже нехорошо

2023-02-14 16:51 UTC, rflban commented on source/zip.js
> +	let result = {};
а чем здесь let лучше, чем const?

2023-02-14 16:59 UTC, Yakwilik commented on source/zip.js
> +	let result = {};
В данном случае ничем. Мы просто можем обновить эту переменную, в случае с const мы бы не могли этого сделать.

2023-02-14 17:03 UTC, Yakwilik commented on source/zip.js
> +    return value.toString() === '[object Object]';
подойдет такая проверка?
`    return value instanceof Object;`

2023-02-14 17:16 UTC, Yakwilik commented on source/zip.js
> +    return value.toString() === '[object Object]';
Если проверять так:
`return value.toString() === '[object Object]';`
то мы точно знаем, что это кастомный объект.
А другие методы могут вернуть true даже в случае, если это массив. 
Поэтому хочу уточнить, что от меня требуется.

2023-02-14 17:30 UTC, Yakwilik commented on source/zip.js
> +    return value.toString() === '[object Object]';
Оставил такую проверку, надеюсь ок.
`    return value.constructor.name === 'Object';`

2023-02-14 19:16 UTC, rflban commented on source/zip.js
> +	let result = {};
если переменную не надо менять, то лучше использовать const, чтобы застраховаться от нечаянных изменений

2023-02-14 19:16 UTC, rflban commented on source/zip.js
> +    return value.toString() === '[object Object]';
instanceof

2023-02-14 19:17 UTC, rflban commented on source/zip.js
> +    return value.toString() === '[object Object]';
но в данном случае лучше использовать typeof и дополнительную проверку на null

2023-02-14 19:28 UTC, Yakwilik commented on source/zip.js
> +    return value.toString() === '[object Object]';
Через имя конструктора не пойдёт?

2023-02-14 20:30 UTC, rflban commented on source/zip.js
> +    return value.toString() === '[object Object]';
нет

2023-02-14 20:32 UTC, rflban commented on source/zip.js
> +    return value.toString() === '[object Object]';
на вход могут передать:
null
undefined
объект, у которого в цепочке прототипов нет constructor

тогда проверка упадет с исключением

2023-02-14 22:04 UTC, Yakwilik commented on source/zip.js
> +	let result = {};
Хорошо. В текущем решении уже нет объявления переменной.

2023-02-14 22:25 UTC, Yakwilik commented on source/zip.js
> +    return value.toString() === '[object Object]';
typeof с проверкой на null и undefined:
`const isObject = (value) => {
    return value && typeof value === 'object';
}`

2023-02-14 22:31 UTC, rflban requested changes

2023-02-14 22:31 UTC, rflban commented on source/zip.js
> +    if (!objects.length) {
objects тоже может быть null
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray

2023-02-15 00:22 UTC, Yakwilik commented on source/zip.js
> +    if (!objects.length) {
добавил проверку

2023-02-15 09:44 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-15 09:44 UTC, DPeshkoff commented on index.html
> -<body>
а зачем тут дифф? давай уберем

2023-02-15 09:44 UTC, DPeshkoff commented on index.html
> +        <script src="tests/zip.js"></script>
и тут

2023-02-15 09:44 UTC, DPeshkoff commented on source/zip.js
> +'use strict';
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-15 09:44 UTC, DPeshkoff commented on source/zip.js
> +    return value && typeof value === 'object';
А если так?)
![изображение](https://user-images.githubusercontent.com/31134795/218991296-9423c074-4065-49f7-ad04-37c5a41b45f6.png)

2023-02-15 09:44 UTC, DPeshkoff commented on source/zip.js
> +const isObject = (value) => {
А чем стрелочные функции отличаются от обычных?

2023-02-15 09:44 UTC, DPeshkoff commented on tests/zip.js
> +	});
Давай добавим тесты на некорректный ввод - undefined, NaN, null

2023-02-15 10:34 UTC, Yakwilik commented on source/zip.js
> +'use strict';
Использовал, потому что в других файлах js эта директива уже была использована. Раз она была использована других файлах, тот же режим кодирования нужно сохранить и в новом файле. Эта строчка включает строгий режим написания кода.

2023-02-15 10:38 UTC, Yakwilik commented on source/zip.js
> +const isObject = (value) => {
Главное отличие стрелочных функций в том, что у них нет своего контекста, поэтому они получают его по переданному аргументу. Стрелочная функция записывается короче.

2023-02-15 11:34 UTC, Yakwilik commented on source/zip.js
> +    return value && typeof value === 'object';
добавил доп проверку.

2023-02-15 11:34 UTC, Yakwilik commented on tests/zip.js
> +	});
Ok

2023-02-15 11:36 UTC, Yakwilik commented on index.html
> +        <script src="tests/zip.js"></script>
убрал. из-за автоформаттера файл поменялся при сохранении.

2023-02-15 12:34 UTC, DPeshkoff commented on source/zip.js
> +const isObject = (value) => {
[Не соглашусь ](https://vc.ru/dev/133379-5-otlichiy-mezhdu-obychnymi-i-strelochnymi-funkciyami)

2023-02-15 12:34 UTC, DPeshkoff commented on source/zip.js
> +'use strict';
А что такое "строгий режим"?

2023-02-15 12:44 UTC, Yakwilik commented on source/zip.js
> +'use strict';
Режим, при котором устаревший код перестает работать. Устаревшим считается код, который не соответствует стандарту ES5 2009 года.

2023-02-15 12:52 UTC, Yakwilik commented on source/zip.js
> +const isObject = (value) => {
Выразился  неправильно. Контекст стрелочный функции статический, он берется из текущего контекста, где создается функция. У обычных функций контекст динамический.

2023-02-15 13:02 UTC, DPeshkoff approved these changes

2023-02-15 13:03 UTC, closed without merging