Задание выполнено, тесты добавлены
frontend-park-mail-ru/homework_2023_1 pull request #7
Opened 2023-02-08 13:53 UTC by thxtomslf

## ДЗ № 0 по фронтенду.
Скрипт написан, добавлено три теста.

Выполнил: Павел Репин.

2023-02-09 10:50 UTC, rflban commented
Привет! Я буду проверять твое ДЗ0, а пока что есть просьба - добавь в имя пулл реквеста свое имя, фамилию и номер варианта

2023-02-09 12:39 UTC, thxtomslf commented
Исправил именование пр

2023-02-11 14:49 UTC, rflban requested changes

2023-02-11 14:49 UTC, rflban commented on source/format.js
> +function format(values, columnsNumber) {
давай добавим валидацию и jsdoc

2023-02-11 14:49 UTC, rflban commented on source/format.js
> +function getNumberLength(number) {
а как еще можно получить длину числа? менее эффективно, но чтобы запись была короче

2023-02-12 09:28 UTC, thxtomslf commented on source/format.js
> +function format(values, columnsNumber) {
Использую function declaration, т.к. на мой взгляд, в условиях поставленной задачи нет значимых поводов выбрать именно function expression. Как я понял, function expression считается более аккуратным, компактным вариантом + можно решать в каком скоупе будет видна функция, а также функция становится доступна только после исполнения соответствующих строк кода (при использовании function declaration интерпретатор до исполнения кода их находит). Но в данной задаче это без разницы, а мне больше по душе такой вариант.

2023-02-12 09:39 UTC, thxtomslf commented on source/format.js
> +	let maxLengths = Array(columnsNumber).fill(0);
Существуют еще var и const. Var считается устаревшим вариантом. Различие между var и let в том, что переменная, объявленная с помощью var, будет доступна в пределах скоупа всей функции, а c let - только в пределах скоупа, в котором она объявлена. А также если не определить перeменную с var, то она получить значение undefined. let же такого сделать не даст. При обращении к неопределнной переменной получим ReferenceError.
const - то же самое, что и let, только переменную нельзя изменять

2023-02-12 09:43 UTC, thxtomslf commented on source/format.js
> +function getNumberLength(number) {
Можно конвертировать число в строку, а затем получить длину строки:
function getNumberLength(number) {
    stringedNumber = number.toString();
    return stringedNumber.length
}

+- так

2023-02-12 18:57 UTC, rflban commented on source/format.js
> +function format(values, columnsNumber) {
кроме function expression есть еще один способ объявления функции

2023-02-12 18:59 UTC, rflban commented on source/format.js
> +	let maxLengths = Array(columnsNumber).fill(0);
верно, но еще лучше не объявлять переменные через let, если логика программы не подразумевает их изменение

2023-02-12 19:15 UTC, rflban requested changes

2023-02-12 19:15 UTC, rflban commented on source/format.js
> +	if (typeof columnsNumber !== 'number') {
бывают такие числа, у которых typeof != 'number'

2023-02-12 19:15 UTC, rflban commented on source/format.js
> +		columnIndex++;
ты ниже используешь параметр index, используй его тут тоже вместо columnIndex

2023-02-12 19:15 UTC, rflban commented on source/format.js
> +	columnIndex = 0;
тут тоже можно обойтись без этой переменной

2023-02-12 19:15 UTC, rflban commented on source/format.js
> +	values.forEach((value, index, values) => {
вместо forEach можно использовать более подходящий метод

2023-02-12 19:15 UTC, rflban commented on source/format.js
> +		stringedNumber = " ".repeat(spacesAmount) + stringedNumber;
вместо конкатенации строк предпочтительнее использовать интерполяцию

2023-02-12 19:15 UTC, rflban commented on source/format.js
> +		stringedNumber = " ".repeat(spacesAmount) + stringedNumber;
подумай как можно написать так, чтобы не переопределять `stringedNumber`

2023-02-12 19:15 UTC, rflban commented on tests/format.js
> +
не хватает тест кейсов на невалидные входные параметры

2023-02-12 20:24 UTC, thxtomslf commented on source/format.js
> +	if (typeof columnsNumber !== 'number') {
Да, бывают, добавлю поддержку BigInt

2023-02-12 20:43 UTC, thxtomslf commented on source/format.js
> +		columnIndex++;
Исправил, теперь вычисляю columnIndex внутри цикла из index. Лишнюю логику убрал

2023-02-12 21:09 UTC, rflban commented on source/format.js
> +	if (typeof columnsNumber !== 'number') {
нет, я не про bigint, они с обычными числами несовместимы все равно
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/Number

2023-02-13 14:00 UTC, thxtomslf commented on source/format.js
> +function format(values, columnsNumber) {
Можно еще как стрелочную функцию записать

2023-02-13 14:03 UTC, thxtomslf commented on source/format.js
> +	let maxLengths = Array(columnsNumber).fill(0);
добавил const, где это возможно

2023-02-13 14:22 UTC, rflban commented on source/format.js
> +function format(values, columnsNumber) {
а чем отличаются стрелочные от обычных?

2023-02-13 14:32 UTC, thxtomslf commented on source/format.js
> +	values.forEach((value, index, values) => {
для второго выбрал reduce; для первого цикла при данной логике получается только сложнее, если убирать forEach

2023-02-13 15:22 UTC, thxtomslf commented on source/format.js
> +	if (typeof columnsNumber !== 'number') {
понял, могут передать new Number(), который будет объектом-оберткой над числом. Но не думаю, что надо добавлять поддержку этого случая, ведь это уже не чисто число, а составной объект может быть

2023-02-13 15:27 UTC, rflban commented on source/format.js
> +	if (typeof columnsNumber !== 'number') {
надо, этот тип поддерживает все числовые операции

2023-02-13 17:15 UTC, thxtomslf commented on source/format.js
> +	if (typeof columnsNumber !== 'number') {
фикс сделал: добавил условие + тест накинул на new Number()

2023-02-13 17:17 UTC, thxtomslf commented on source/format.js
> +function format(values, columnsNumber) {
в них нельзя использовать ключевое слово this, которое служит ссылкой на объект, не доступен список аргументов через arguments + их нельзя использовать как конструкторы (это из первого ограничения и следует)

2023-02-13 18:05 UTC, rflban requested changes

2023-02-13 18:06 UTC, rflban commented on source/format.js
> +function format(values, columnsNumber) {
а надо ли позволять использовать эти функции как конструкторы?

2023-02-13 18:14 UTC, wd055 commented on source/format.js
> +function format(values, columnsNumber) {
`нельзя использовать ключевое слово this` это неправильно

2023-02-13 18:36 UTC, thxtomslf commented on source/format.js
> +	}, "");
будут ""

2023-02-13 18:38 UTC, thxtomslf commented on source/format.js
> +		let columnIndex = index % columnsNumber;
все, все, что можно const

2023-02-13 18:40 UTC, thxtomslf commented on source/format.js
> +function format(values, columnsNumber) {
если this - bad practice, то стоит ограничить сценарий с конструктором. заменю на =>

2023-02-13 18:52 UTC, thxtomslf commented on source/format.js
> +	values.forEach((value, index) => {
разобрался

2023-02-13 18:59 UTC, thxtomslf commented on source/format.js
> +	if (typeof columnsNumber !== 'number' && columnsNumber.constructor != Number) {
через isPrototypeOf выглядит неплохо

2023-02-13 19:06 UTC, rflban commented on source/format.js
> +	if (typeof columnsNumber !== 'number' && columnsNumber.constructor != Number) {
уже лучше, внезапного исключения не будет, но принято делать так: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/instanceof

2023-02-13 19:18 UTC, rflban requested changes

2023-02-13 19:18 UTC, rflban commented on source/format.js
> +	const output = values.reduce((previousValue, currentElement, index, arr) => {
я что-то только сейчас обратил внимание, строки не очень эффективно таким образом формировать, каждая конкатенация будет приводить к очередному копированию. лучше собрать все строки в массив и соединить их в конце в одну

2023-02-13 19:18 UTC, rflban commented on source/format.js
> +	}, Array(columnsNumber).fill(0));
если использовать объект, можно написать лаконичнее

2023-02-13 19:52 UTC, thxtomslf commented on source/format.js
> +	const output = values.reduce((previousValue, currentElement, index, arr) => {
исправил

2023-02-14 19:35 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Работа хорошая, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-14 19:35 UTC, DPeshkoff commented on source/format.js
> +	if (typeof columnsNumber !== "number" && !(columnsNumber instanceof Number)) {
Традиционно принято использовать одиночные кавычки для строк)

2023-02-14 19:35 UTC, DPeshkoff commented on source/format.js
> +	}
здесь происходит что-то страшное... но зачем?

2023-02-14 19:35 UTC, DPeshkoff commented on source/format.js
> +	const stringsArray = values.reduce((resultArray, currentElement, index) => {
Гоу попробуем покопать в методы строки?)

2023-02-14 19:35 UTC, DPeshkoff commented on tests/format.js
> +					  expected3);
Можно в анонимную стрелочную функцию

Кстати, чем отличаются стрелочные и обычные функции?

2023-02-14 19:35 UTC, DPeshkoff commented on source/format.js
> +"use strict"
Можешь, пожалуйста, расписать в реплае, что это за строчка - что она делает, почему использовал в работе?

2023-02-14 21:28 UTC, thxtomslf commented on source/format.js
> +"use strict"
Эта директивна активирует "современный" режим работы js. Ее ввели в каком-то стандарте, когда решили добавлять в язык фичи, ломающие обратную совместимость. То есть для работы старого кода остался старый режим (без 'use strict'), а для использования новых возможностей как раз и применяется директива

2023-02-14 21:29 UTC, thxtomslf commented on tests/format.js
> +					  expected3);
В стрелочных нельзя использовать ключевое слово this, которое служит ссылкой на объект, не доступен список аргументов через arguments + их нельзя использовать как конструкторы (это из первого ограничения и следует). Исправлю на стрелочную

2023-02-14 21:33 UTC, thxtomslf commented on source/format.js
> +	}
Можно было +-так:

function getNumberLength(number) {
stringedNumber = number.toString();
return stringedNumber.length
}

Но это точно менее эффективно по памяти, а возможно и по скорости (не знаю, как реализовано преобразование типов, но кажется, что мой вариант все же более эффективен).

2023-02-14 21:58 UTC, thxtomslf commented on source/format.js
> +	const stringsArray = values.reduce((resultArray, currentElement, index) => {
написал в тг с вопросом

2023-02-15 09:36 UTC, DPeshkoff approved these changes

2023-02-15 09:36 UTC, closed without merging