Гречко Георгий
frontend-park-mail-ru/homework_2023_1 pull request #8
Opened 2023-02-08 15:07 UTC by geogreck

2023-02-09 10:51 UTC, rflban commented
Привет! Я буду проверять твое ДЗ0, а пока что есть просьба - добавь в имя пулл реквеста номер варианта

2023-02-09 21:09 UTC, wd055 requested changes

2023-02-09 21:09 UTC, wd055 commented on source/set.js
> +function set(obj, property, new_val) {
Почему именно так объявлена функция? Есть ли другой способ ее проинициализировать, в чем разница?

2023-02-09 21:09 UTC, wd055 commented on source/set.js
> +    let arr = property.split('.')
Тут и еще в паре мест стоит по-другому объявлять переменные? Можешь сказать почему?

2023-02-09 21:09 UTC, wd055 commented on source/set.js
> +    for (let i = 0; i < length - 1; i++) {
Лучше использовать не цикл, а встроенный метод

2023-02-09 21:35 UTC, wd055 commented
Привет! Я буду проверять твоё ДЗ0. Хорошая первая итерация, давай займемся улучшениями!

2023-02-11 10:30 UTC, wd055 requested changes

2023-02-11 10:30 UTC, wd055 commented on source/set.js
> +            current[arr[length - 1]] = new_val;
Тут разве val не равен arr[length - 1]?

2023-02-12 13:12 UTC, wd055 commented
Вроде супер! Еще старший ментор проверит. Удачи на курсе! По любым вопросам можешь обращаться)

2023-02-13 11:23 UTC, DPeshkoff requested changes
Привет и добро пожаловать на второй семестр!

Хорошая работа, но есть пара вопросов к твоему решению)

Если будут вопросы - можешь писать в [телеграм](https://t.me/DmPesh)

2023-02-13 11:23 UTC, DPeshkoff commented on source/set.js
> +'use strict';
Можешь, пожалуйста, объяснить в реплае, зачем нужен use strict и почему он используется в работе?

2023-02-13 11:23 UTC, DPeshkoff commented on source/set.js
> +const set = (obj, property, new_val) => {
Не хватает проверки входных значений - что будет, если property окажется не строкой, а чем-то не очень приятным?

2023-02-13 11:23 UTC, DPeshkoff commented on source/set.js
> +        if (ind == length - 1) {
Строгие [проверки](https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness) лучше нестрогих)

2023-02-13 11:23 UTC, DPeshkoff commented on tests/set.js
> +    })
Тесты на некорректный ввод тоже нужно будет добавить)

2023-02-13 19:44 UTC, DPeshkoff requested changes

2023-02-13 19:44 UTC, DPeshkoff commented on source/set.js
> +    if (Object.prototype.toString.call(property) !== '[object String]') {
нужно что-то еще)

![изображение](https://user-images.githubusercontent.com/31134795/218558508-723c8ff8-1b3a-441a-af0a-97647c0b82e5.png)

2023-02-13 19:44 UTC, DPeshkoff commented on source/set.js
> +        throw new Error('first argument must be an object');
[Лучше так](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/TypeError)

2023-02-13 19:47 UTC, geogreck commented on source/set.js
> +    if (Object.prototype.toString.call(property) !== '[object String]') {
Немного не понял, что не так..

2023-02-13 19:47 UTC, geogreck commented on source/set.js
> +    if (Object.prototype.toString.call(property) !== '[object String]') {
![image](https://user-images.githubusercontent.com/74151984/218559721-8ab03e90-d09f-4ca5-ae0b-73f17fa9d719.png)

2023-02-14 09:54 UTC, geogreck commented on source/set.js
> +    if (Object.prototype.toString.call(property) !== '[object String]') {
![Screenshot_2023-02-14-12-54-05-24_21da60175e70af211acc4f26191b7a77](https://user-images.githubusercontent.com/74151984/218701001-a1db19fb-98b8-4715-8070-d98b2ade5636.jpg)
Так тоже работает...

2023-02-14 14:40 UTC, DPeshkoff commented on source/set.js
> +    if (Object.prototype.toString.call(property) !== '[object String]') {
Да, ошибся с условием, запроверялся, ты прав)

2023-02-14 14:41 UTC, DPeshkoff approved these changes

2023-02-14 14:41 UTC, closed without merging